import type { CalcOutput, Field, Inputs } from "@/lib/engineering";
import {
  columnas,
  edificioSismo,
  escaleraDescanso,
  escaleraDos,
  pilotes,
  platea,
  vigaCimentacion,
  vigaCompuesta,
  vigaCortante,
  vigaDoble,
  vigaFlexion,
  zapataAislada,
  zapataCombinada,
} from "@/lib/engines/edificaciones";
import {
  dispositivosApoyo,
  estriboGravedad,
  estriboPantalla,
  estriboVoladizo,
  losaPuente,
  placaApoyo,
  puenteCajon,
  puenteVehicular,
  travesano,
  vigaPresforzada,
} from "@/lib/engines/puentes";

const ENGINES: Record<string, (i: Inputs) => CalcOutput> = {
  "estribo-voladizo": estriboVoladizo,
  "estribo-gravedad": estriboGravedad,
  "estribo-pantalla": estriboPantalla,
  "losa-puente": losaPuente,
  "puente-vehicular": puenteVehicular,
  "viga-presforzada": vigaPresforzada,
  "dispositivos-apoyo": dispositivosApoyo,
  "placa-apoyo": placaApoyo,
  travesano,
  "puente-cajon": puenteCajon,
  columnas,
  "viga-flexion": vigaFlexion,
  "viga-cortante": vigaCortante,
  "viga-doble-armadura": vigaDoble,
  "viga-compuesta": vigaCompuesta,
  "zapata-aislada": zapataAislada,
  "zapata-combinada": zapataCombinada,
  "viga-cimentacion": vigaCimentacion,
  platea,
  pilotes,
  "escalera-dos-tramos": escaleraDos,
  "escalera-descanso": escaleraDescanso,
  "edificio-sismo": edificioSismo,
};

export function computeModule(slug: string, inputs: Inputs): CalcOutput {
  const fn = ENGINES[slug];
  if (!fn) throw new Error("Módulo no encontrado");
  return fn(inputs);
}

export const MODULE_FIELDS: Record<string, Field[]> = {
  "estribo-voladizo": [
    { key: "H", label: "Altura H", unit: "m", type: "number", group: "Geometría", step: 0.1 },
    { key: "B", label: "Ancho de zapata B", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "D", label: "Peralte zapata D", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "Lpunta", label: "Punta Lpunta", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "tsup", label: "Espesor superior tsup", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "tinf", label: "Espesor inferior tinf", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "Ltab", label: "Longitud de tablero", unit: "m", type: "number", group: "Puente", step: 0.5 },
    { key: "hviga", label: "Espesor tablero + viga", unit: "m", type: "number", group: "Puente", step: 0.05 },
    { key: "S", label: "Desviación S", unit: "°", type: "number", group: "Puente", step: 0.1 },
    { key: "hz", label: "Prof. de cimiento hz", unit: "m", type: "number", group: "Puente", step: 0.1 },
    { key: "PDC", label: "PDC", unit: "t/m", type: "number", group: "Cargas AASHTO", step: 0.1 },
    { key: "PDW", label: "PDW", unit: "t/m", type: "number", group: "Cargas AASHTO", step: 0.1 },
    { key: "PLLIM", label: "PLL + IM", unit: "t/m", type: "number", group: "Cargas AASHTO", step: 0.1 },
    { key: "BR", label: "Frenado BR", unit: "t/m", type: "number", group: "Cargas AASHTO", step: 0.05 },
    { key: "hBR", label: "Altura BR (norma)", unit: "m", type: "number", group: "Cargas AASHTO", step: 0.1 },
    { key: "phi", label: "φ fricción interna", unit: "°", type: "number", group: "Suelo", step: 0.5 },
    { key: "delta", label: "δ suelo-muro", unit: "°", type: "number", group: "Suelo", step: 0.5 },
    { key: "beta", label: "β suelo-horiz.", unit: "°", type: "number", group: "Suelo", step: 0.5 },
    { key: "theta", label: "θ muro-terreno", unit: "°", type: "number", group: "Suelo", step: 1 },
    { key: "gs", label: "γ suelo", unit: "t/m³", type: "number", group: "Suelo", step: 0.05 },
    { key: "qadm", label: "qadm", unit: "t/m²", type: "number", group: "Suelo", step: 0.05 },
    { key: "FS", label: "FS capacidad", unit: "", type: "number", group: "Suelo", step: 0.1 },
    { key: "PGA", label: "PGA", unit: "", type: "number", group: "Sismo", step: 0.05 },
    { key: "FPGA", label: "FPGA sitio", unit: "", type: "number", group: "Sismo", step: 0.1 },
    { key: "gc", label: "γ concreto", unit: "t/m³", type: "number", group: "Materiales", step: 0.05 },
    { key: "fc", label: "f'c", unit: "kg/cm²", type: "number", group: "Materiales", step: 10 },
    { key: "fy", label: "fy", unit: "kg/cm²", type: "number", group: "Materiales", step: 100 },
  ],
  "estribo-gravedad": [
    { key: "H", label: "Altura H", unit: "m", type: "number", group: "Puente", step: 0.1 },
    { key: "Ltab", label: "Long. tablero", unit: "m", type: "number", group: "Puente", step: 0.1 },
    { key: "e", label: "Espesor tablero e", unit: "m", type: "number", group: "Puente", step: 0.05 },
    { key: "eLosa", label: "Espesor losa de acercamiento", unit: "m", type: "number", group: "Puente", step: 0.05 },
    { key: "B", label: "Ancho de cimiento B", unit: "m", type: "number", group: "Predimensionado", step: 0.05 },
    { key: "a", label: "Coronación / puntera a", unit: "m", type: "number", group: "Predimensionado", step: 0.05 },
    { key: "bTalon", label: "Talón b", unit: "m", type: "number", group: "Predimensionado", step: 0.05 },
    { key: "h", label: "Peralte zapata h", unit: "m", type: "number", group: "Predimensionado", step: 0.05 },
    { key: "hz", label: "Prof. cimiento hz", unit: "m", type: "number", group: "Predimensionado", step: 0.05 },
    { key: "N", label: "Cajuela / neoprene N", unit: "m", type: "number", group: "Predimensionado", step: 0.05 },
    { key: "tBack", label: "Espesor asiento t", unit: "m", type: "number", group: "Predimensionado", step: 0.05 },
    { key: "PDC", label: "PDC", unit: "t/m", type: "number", group: "Cargas", step: 0.1 },
    { key: "PDW", label: "PDW", unit: "t/m", type: "number", group: "Cargas", step: 0.1 },
    { key: "PLLIM", label: "PLL+IM", unit: "t/m", type: "number", group: "Cargas", step: 0.1 },
    { key: "BR", label: "BR frenado", unit: "t/m", type: "number", group: "Cargas", step: 0.05 },
    { key: "WS", label: "WS viento", unit: "t/m", type: "number", group: "Cargas", step: 0.05 },
    { key: "CRSHTU", label: "CR+SH+TU", unit: "t/m", type: "number", group: "Cargas", step: 0.05 },
    { key: "hBR", label: "Brazo BR sobre tablero", unit: "m", type: "number", group: "Cargas", step: 0.1 },
    { key: "phi", label: "φ fricción interna", unit: "°", type: "number", group: "Suelo", step: 0.5 },
    { key: "delta", label: "δ suelo–muro", unit: "°", type: "number", group: "Suelo", step: 0.5 },
    { key: "beta", label: "β suelo–horizontal", unit: "°", type: "number", group: "Suelo", step: 0.5 },
    { key: "theta", label: "θ muro–terreno", unit: "°", type: "number", group: "Suelo", step: 0.5 },
    { key: "gc", label: "γ concreto simple", unit: "t/m³", type: "number", group: "Suelo", step: 0.01 },
    { key: "gs", label: "γ suelo", unit: "t/m³", type: "number", group: "Suelo", step: 0.05 },
    { key: "qr", label: "qr admisible", unit: "kg/cm²", type: "number", group: "Suelo", step: 0.1 },
    { key: "suelo", label: "Cimentación", type: "select", group: "Suelo", options: [
      { value: "no-rocoso", label: "No rocoso (q uniforme)" },
      { value: "rocoso", label: "Rocoso (qmáx / qmín)" },
    ] },
  ],
  "estribo-pantalla": [
    { key: "H", label: "Altura H", unit: "m", type: "number", group: "Geometría", step: 0.1 },
    { key: "B", label: "Ancho B", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "D", label: "Peralte D", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "Lpunta", label: "Punta", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "tsup", label: "tsup", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "tinf", label: "tinf", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "PDC", label: "PDC", unit: "t/m", type: "number", group: "Cargas", step: 0.1 },
    { key: "PDW", label: "PDW", unit: "t/m", type: "number", group: "Cargas", step: 0.1 },
    { key: "PLLIM", label: "PLL+IM", unit: "t/m", type: "number", group: "Cargas", step: 0.1 },
    { key: "BR", label: "BR", unit: "t/m", type: "number", group: "Cargas", step: 0.05 },
    { key: "phi", label: "φ", unit: "°", type: "number", group: "Suelo", step: 0.5 },
    { key: "delta", label: "δ", unit: "°", type: "number", group: "Suelo", step: 0.5 },
    { key: "gs", label: "γ suelo", unit: "t/m³", type: "number", group: "Suelo", step: 0.05 },
    { key: "qadm", label: "qadm", unit: "t/m²", type: "number", group: "Suelo", step: 0.05 },
    { key: "PGA", label: "PGA", unit: "", type: "number", group: "Sismo", step: 0.05 },
    { key: "FPGA", label: "FPGA", unit: "", type: "number", group: "Sismo", step: 0.1 },
    { key: "fc", label: "f'c", unit: "kg/cm²", type: "number", group: "Materiales", step: 10 },
    { key: "fy", label: "fy", unit: "kg/cm²", type: "number", group: "Materiales", step: 100 },
  ],
  "losa-puente": [
    { key: "L", label: "Luz del puente L", unit: "m", type: "number", group: "Geometría", step: 0.5 },
    { key: "S", label: "Separación de vigas S'", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "bViga", label: "Ancho de viga b", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "t", label: "Espesor de losa t", unit: "m", type: "number", group: "Geometría", step: 0.01 },
    { key: "eAsf", label: "Espesor asfalto", unit: "m", type: "number", group: "Cargas", step: 0.01 },
    { key: "nTramos", label: "N° de tramos", unit: "", type: "number", group: "Geometría", step: 1 },
    { key: "fc", label: "f'c", unit: "kg/cm²", type: "number", group: "Materiales", step: 10 },
    { key: "fy", label: "fy", unit: "kg/cm²", type: "number", group: "Materiales", step: 100 },
    { key: "gc", label: "γ C°A°", unit: "t/m³", type: "number", group: "Materiales", step: 0.05 },
    { key: "gAsf", label: "γ asfalto", unit: "t/m³", type: "number", group: "Materiales", step: 0.02 },
  ],
  "puente-vehicular": [
    { key: "L", label: "Longitud total", unit: "m", type: "number", group: "Geometría", step: 0.5 },
    { key: "Btot", label: "Ancho total", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "Blibre", label: "Ancho libre", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "nVigas", label: "N° vigas", unit: "", type: "number", group: "Geometría", step: 1 },
    { key: "S", label: "Separación S'", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "t", label: "Espesor losa", unit: "m", type: "number", group: "Geometría", step: 0.01 },
    { key: "hViga", label: "Peralte viga", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "bViga", label: "Ancho viga", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "eAsf", label: "Rodadura", unit: "m", type: "number", group: "Cargas", step: 0.01 },
    { key: "gBarrera", label: "Peso barrera", unit: "t/m", type: "number", group: "Cargas", step: 0.05 },
    { key: "fc", label: "f'c", unit: "kg/cm²", type: "number", group: "Materiales", step: 10 },
    { key: "fy", label: "fy", unit: "kg/cm²", type: "number", group: "Materiales", step: 100 },
  ],
  "viga-presforzada": [
    { key: "L", label: "Luz", unit: "m", type: "number", group: "Geometría", step: 0.5 },
    { key: "S", label: "Separación", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "t", label: "Espesor losa", unit: "m", type: "number", group: "Geometría", step: 0.01 },
    { key: "h", label: "Peralte h", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "b", label: "Ancho ala inf. b", unit: "m", type: "number", group: "Geometría", step: 0.02 },
    { key: "tf", label: "Espesor ala tf", unit: "m", type: "number", group: "Geometría", step: 0.02 },
    { key: "tw", label: "Alma tw", unit: "m", type: "number", group: "Geometría", step: 0.02 },
    { key: "fci", label: "f'ci transferencia", unit: "kg/cm²", type: "number", group: "Materiales", step: 10 },
    { key: "fcf", label: "f'c final", unit: "kg/cm²", type: "number", group: "Materiales", step: 10 },
    { key: "fpu", label: "fpu", unit: "kg/cm²", type: "number", group: "Materiales", step: 10 },
    { key: "perdidas", label: "Pérdidas (1-R)", unit: "%", type: "number", group: "Materiales", step: 1 },
    { key: "eAsf", label: "Rodadura", unit: "m", type: "number", group: "Cargas", step: 0.01 },
  ],
  "dispositivos-apoyo": [
    { key: "PDC", label: "PDC", unit: "kg", type: "number", group: "Cargas", step: 10 },
    { key: "PDW", label: "PDW", unit: "kg", type: "number", group: "Cargas", step: 10 },
    { key: "PLL", label: "PLL", unit: "kg", type: "number", group: "Cargas", step: 10 },
    { key: "bViga", label: "Ancho de viga", unit: "cm", type: "number", group: "Geometría", step: 1 },
    { key: "L", label: "Longitud de viga", unit: "m", type: "number", group: "Geometría", step: 0.5 },
    { key: "G", label: "G dureza 60", unit: "kg/cm²", type: "number", group: "Elastómero", step: 0.1 },
    { key: "sigma", label: "σ admisible", unit: "kg/cm²", type: "number", group: "Elastómero", step: 0.5 },
    { key: "dT", label: "ΔT", unit: "°C", type: "number", group: "Elastómero", step: 1 },
    { key: "fy", label: "Fy placas", unit: "kg/cm²", type: "number", group: "Elastómero", step: 10 },
  ],
  "placa-apoyo": [
    { key: "Pu", label: "Pu", unit: "kg", type: "number", group: "Cargas", step: 100 },
    { key: "fc", label: "f'c", unit: "kg/cm²", type: "number", group: "Materiales", step: 10 },
    { key: "fy", label: "Fy A-36", unit: "kg/cm²", type: "number", group: "Materiales", step: 10 },
    { key: "tipo", label: "Tipo de placa", type: "select", group: "Geometría", options: [
      { value: "circular", label: "Circular" },
      { value: "rectangular", label: "Rectangular" },
    ] },
  ],
  travesano: [
    { key: "b", label: "Base b", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "h", label: "Peralte h", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "rec", label: "Recubrimiento", unit: "m", type: "number", group: "Geometría", step: 0.01 },
    { key: "S", label: "Separación de vigas", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "nBar", label: "N° barras long.", unit: "", type: "number", group: "Acero", step: 1 },
    { key: "fc", label: "f'c", unit: "kg/cm²", type: "number", group: "Materiales", step: 10 },
    { key: "fy", label: "fy", unit: "kg/cm²", type: "number", group: "Materiales", step: 100 },
  ],
  "puente-cajon": [
    { key: "L", label: "Luz", unit: "m", type: "number", group: "Geometría", step: 0.5 },
    { key: "B", label: "Ancho B", unit: "m", type: "number", group: "Geometría", step: 0.1 },
    { key: "h", label: "Peralte h", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "tw", label: "Alma tw", unit: "m", type: "number", group: "Geometría", step: 0.02 },
    { key: "tf", label: "Losa superior tf", unit: "m", type: "number", group: "Geometría", step: 0.01 },
    { key: "tb", label: "Losa inferior tb", unit: "m", type: "number", group: "Geometría", step: 0.01 },
    { key: "fc", label: "f'c", unit: "kg/cm²", type: "number", group: "Materiales", step: 10 },
    { key: "fy", label: "fy", unit: "kg/cm²", type: "number", group: "Materiales", step: 100 },
  ],
  columnas: [
    { key: "b", label: "Base b", unit: "cm", type: "number", group: "Geometría", step: 5 },
    { key: "h", label: "Canto h", unit: "cm", type: "number", group: "Geometría", step: 5 },
    { key: "rec", label: "Recubrimiento", unit: "cm", type: "number", group: "Geometría", step: 0.5 },
    { key: "nBar", label: "N° barras", unit: "", type: "number", group: "Acero", step: 1 },
    { key: "bar", label: "Diámetro", type: "select", group: "Acero", options: [
      { value: '1/2"', label: '1/2"' }, { value: '5/8"', label: '5/8"' }, { value: '3/4"', label: '3/4"' }, { value: '1"', label: '1"' },
    ] },
    { key: "Pu", label: "Pu (combinación)", unit: "t", type: "number", group: "Solicitaciones", step: 1 },
    { key: "Mu", label: "Mu", unit: "t·m", type: "number", group: "Solicitaciones", step: 0.5 },
    { key: "fc", label: "f'c", unit: "kg/cm²", type: "number", group: "Materiales", step: 10 },
    { key: "fy", label: "fy", unit: "kg/cm²", type: "number", group: "Materiales", step: 100 },
  ],
  "viga-flexion": [
    { key: "b", label: "Base b", unit: "cm", type: "number", group: "Geometría", step: 5 },
    { key: "h", label: "Altura h", unit: "cm", type: "number", group: "Geometría", step: 5 },
    { key: "L", label: "Luz L", unit: "m", type: "number", group: "Geometría", step: 0.1 },
    { key: "rec", label: "Recubrimiento", unit: "cm", type: "number", group: "Geometría", step: 0.5 },
    { key: "L1", label: "Luz losa 1", unit: "m", type: "number", group: "Tributario", step: 0.1 },
    { key: "L2", label: "Luz losa 2", unit: "m", type: "number", group: "Tributario", step: 0.1 },
    { key: "cv", label: "Sobrecarga", unit: "kg/m²", type: "number", group: "Cargas", step: 10 },
    { key: "combo", label: "Combinación", type: "select", group: "Cargas", options: [
      { value: "e060", label: "1.4D+1.7L (E.060)" },
      { value: "aci", label: "1.2D+1.6L (ACI)" },
    ] },
    { key: "fc", label: "f'c", unit: "kg/cm²", type: "number", group: "Materiales", step: 10 },
    { key: "fy", label: "fy", unit: "kg/cm²", type: "number", group: "Materiales", step: 100 },
  ],
  "viga-cortante": [
    { key: "b", label: "Ancho b", unit: "cm", type: "number", group: "Geometría", step: 5 },
    { key: "h", label: "Altura h", unit: "cm", type: "number", group: "Geometría", step: 5 },
    { key: "L", label: "Luz L", unit: "m", type: "number", group: "Geometría", step: 0.1 },
    { key: "rec", label: "Recubrimiento", unit: "cm", type: "number", group: "Geometría", step: 0.5 },
    { key: "wu", label: "Wu", unit: "kg/m", type: "number", group: "Cargas", step: 50 },
    { key: "Av", label: "Av estribo", unit: "cm²", type: "number", group: "Acero", step: 0.1 },
    { key: "fc", label: "f'c", unit: "kg/cm²", type: "number", group: "Materiales", step: 10 },
    { key: "fy", label: "fy", unit: "kg/cm²", type: "number", group: "Materiales", step: 100 },
  ],
  "viga-doble-armadura": [
    { key: "b", label: "Base b", unit: "cm", type: "number", group: "Geometría", step: 5 },
    { key: "h", label: "Altura h", unit: "cm", type: "number", group: "Geometría", step: 5 },
    { key: "d", label: "Peralte d", unit: "cm", type: "number", group: "Geometría", step: 1 },
    { key: "dp", label: "d' compresión", unit: "cm", type: "number", group: "Geometría", step: 0.5 },
    { key: "L", label: "Luz", unit: "m", type: "number", group: "Cargas", step: 0.1 },
    { key: "wu", label: "Wu", unit: "t/m", type: "number", group: "Cargas", step: 0.1 },
    { key: "fc", label: "f'c", unit: "kg/cm²", type: "number", group: "Materiales", step: 10 },
    { key: "fy", label: "fy", unit: "kg/cm²", type: "number", group: "Materiales", step: 100 },
  ],
  "viga-compuesta": [
    { key: "D", label: "Peralte perfil D", unit: "cm", type: "number", group: "Perfil", step: 0.5 },
    { key: "Bf", label: "Ancho de ala B", unit: "cm", type: "number", group: "Perfil", step: 0.5 },
    { key: "tf", label: "Espesor ala tf", unit: "cm", type: "number", group: "Perfil", step: 0.1 },
    { key: "tw", label: "Alma tw", unit: "cm", type: "number", group: "Perfil", step: 0.05 },
    { key: "hc", label: "Espesor losa", unit: "cm", type: "number", group: "Losa", step: 1 },
    { key: "be", label: "Ancho efectivo be", unit: "cm", type: "number", group: "Losa", step: 5 },
    { key: "L", label: "Luz", unit: "m", type: "number", group: "Cargas", step: 0.5 },
    { key: "Fy", label: "Fy", unit: "kg/cm²", type: "number", group: "Materiales", step: 10 },
    { key: "fc", label: "f'c losa", unit: "kg/cm²", type: "number", group: "Materiales", step: 10 },
  ],
  "zapata-aislada": [
    { key: "t1", label: "Columna t1", unit: "m", type: "number", group: "Columna", step: 0.05 },
    { key: "t2", label: "Columna t2", unit: "m", type: "number", group: "Columna", step: 0.05 },
    { key: "PD", label: "PD", unit: "t", type: "number", group: "Cargas", step: 1 },
    { key: "PL", label: "PL", unit: "t", type: "number", group: "Cargas", step: 1 },
    { key: "qt", label: "σt", unit: "kg/cm²", type: "number", group: "Suelo", step: 0.1 },
    { key: "Df", label: "Df", unit: "m", type: "number", group: "Suelo", step: 0.1 },
    { key: "gt", label: "γ terreno", unit: "t/m³", type: "number", group: "Suelo", step: 0.05 },
    { key: "sc", label: "s/c piso", unit: "t/m²", type: "number", group: "Suelo", step: 0.05 },
    { key: "hc", label: "Peralte hc", unit: "m", type: "number", group: "Zapata", step: 0.05 },
    { key: "T", label: "Lado T", unit: "m", type: "number", group: "Zapata", step: 0.05 },
    { key: "S", label: "Lado S", unit: "m", type: "number", group: "Zapata", step: 0.05 },
    { key: "fc", label: "f'c", unit: "kg/cm²", type: "number", group: "Materiales", step: 10 },
    { key: "fy", label: "fy", unit: "kg/cm²", type: "number", group: "Materiales", step: 100 },
    { key: "rec", label: "Recubrimiento", unit: "cm", type: "number", group: "Materiales", step: 0.5 },
  ],
  "zapata-combinada": [
    { key: "Pd1", label: "Pd col. izq.", unit: "t", type: "number", group: "Columnas", step: 1 },
    { key: "Pl1", label: "Pl col. izq.", unit: "t", type: "number", group: "Columnas", step: 1 },
    { key: "t1", label: "t col. izq.", unit: "m", type: "number", group: "Columnas", step: 0.05 },
    { key: "Pd2", label: "Pd col. der.", unit: "t", type: "number", group: "Columnas", step: 1 },
    { key: "Pl2", label: "Pl col. der.", unit: "t", type: "number", group: "Columnas", step: 1 },
    { key: "t2", label: "t col. der.", unit: "m", type: "number", group: "Columnas", step: 0.05 },
    { key: "eje", label: "Distancia eje-eje", unit: "m", type: "number", group: "Geometría", step: 0.1 },
    { key: "Lz", label: "Longitud Lz", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "b", label: "Ancho b", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "hc", label: "Peralte hc", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "qt", label: "σt", unit: "kg/cm²", type: "number", group: "Suelo", step: 0.1 },
    { key: "Df", label: "Df", unit: "m", type: "number", group: "Suelo", step: 0.1 },
    { key: "gt", label: "γ terreno", unit: "t/m³", type: "number", group: "Suelo", step: 0.05 },
    { key: "fc", label: "f'c", unit: "kg/cm²", type: "number", group: "Materiales", step: 10 },
    { key: "fy", label: "fy", unit: "kg/cm²", type: "number", group: "Materiales", step: 100 },
  ],
  "viga-cimentacion": [
    { key: "b", label: "Ancho", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "h", label: "Peralte", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "L", label: "Longitud", unit: "m", type: "number", group: "Geometría", step: 0.1 },
    { key: "e", label: "Excentricidad", unit: "m", type: "number", group: "Cargas", step: 0.05 },
    { key: "Pexc", label: "Carga de zapata", unit: "t", type: "number", group: "Cargas", step: 1 },
    { key: "fc", label: "f'c", unit: "kg/cm²", type: "number", group: "Materiales", step: 10 },
    { key: "fy", label: "fy", unit: "kg/cm²", type: "number", group: "Materiales", step: 100 },
  ],
  platea: [
    { key: "Lx", label: "Lx", unit: "m", type: "number", group: "Geometría", step: 0.1 },
    { key: "Ly", label: "Ly", unit: "m", type: "number", group: "Geometría", step: 0.1 },
    { key: "t", label: "Espesor t", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "Df", label: "Df", unit: "m", type: "number", group: "Suelo", step: 0.1 },
    { key: "Ks", label: "Ks", unit: "kg/cm³", type: "number", group: "Suelo", step: 0.5 },
    { key: "qa", label: "qa", unit: "kg/cm²", type: "number", group: "Suelo", step: 0.1 },
    { key: "Ptot", label: "ΣP servicio", unit: "t", type: "number", group: "Cargas", step: 10 },
    { key: "fc", label: "f'c", unit: "kg/cm²", type: "number", group: "Materiales", step: 10 },
  ],
  pilotes: [
    { key: "b", label: "Columna b", unit: "m", type: "number", group: "Columna", step: 0.05 },
    { key: "t", label: "Columna t", unit: "m", type: "number", group: "Columna", step: 0.05 },
    { key: "PD", label: "PD", unit: "t", type: "number", group: "Cargas", step: 1 },
    { key: "PL", label: "PL", unit: "t", type: "number", group: "Cargas", step: 1 },
    { key: "Df", label: "Df estrato duro", unit: "m", type: "number", group: "Suelo", step: 0.1 },
    { key: "phi", label: "φ arena", unit: "°", type: "number", group: "Suelo", step: 1 },
    { key: "g", label: "γ arena", unit: "t/m³", type: "number", group: "Suelo", step: 0.05 },
    { key: "D", label: "Lado pilote D", unit: "m", type: "number", group: "Pilote", step: 0.05 },
    { key: "k", label: "k empujes", unit: "", type: "number", group: "Pilote", step: 0.1 },
  ],
  "escalera-dos-tramos": [
    { key: "p", label: "Paso p", unit: "m", type: "number", group: "Geometría", step: 0.01 },
    { key: "cp", label: "Contrapaso", unit: "m", type: "number", group: "Geometría", step: 0.005 },
    { key: "b", label: "Ancho", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "n1", label: "Escalones tramo 1", unit: "", type: "number", group: "Geometría", step: 1 },
    { key: "n2", label: "Escalones tramo 2", unit: "", type: "number", group: "Geometría", step: 1 },
    { key: "t", label: "Espesor t", unit: "m", type: "number", group: "Geometría", step: 0.01 },
    { key: "sc", label: "s/c", unit: "t/m²", type: "number", group: "Cargas", step: 0.05 },
    { key: "acab", label: "Acabados", unit: "t/m²", type: "number", group: "Cargas", step: 0.02 },
    { key: "fc", label: "f'c", unit: "kg/cm²", type: "number", group: "Materiales", step: 10 },
    { key: "fy", label: "fy", unit: "kg/cm²", type: "number", group: "Materiales", step: 100 },
  ],
  "escalera-descanso": [
    { key: "p", label: "Paso", unit: "m", type: "number", group: "Geometría", step: 0.01 },
    { key: "cp", label: "Contrapaso", unit: "m", type: "number", group: "Geometría", step: 0.005 },
    { key: "b", label: "Ancho", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "n", label: "N° escalones", unit: "", type: "number", group: "Geometría", step: 1 },
    { key: "Ld", label: "Long. descanso Ld", unit: "m", type: "number", group: "Geometría", step: 0.05 },
    { key: "t", label: "Espesor t", unit: "m", type: "number", group: "Geometría", step: 0.01 },
    { key: "sc", label: "s/c", unit: "t/m²", type: "number", group: "Cargas", step: 0.05 },
    { key: "acab", label: "Acabados", unit: "t/m²", type: "number", group: "Cargas", step: 0.02 },
    { key: "fc", label: "f'c", unit: "kg/cm²", type: "number", group: "Materiales", step: 10 },
    { key: "fy", label: "fy", unit: "kg/cm²", type: "number", group: "Materiales", step: 100 },
  ],
  "edificio-sismo": [
    { key: "Z", label: "Zona Z", unit: "", type: "number", group: "E.030", step: 0.05 },
    { key: "S", label: "Factor S", unit: "", type: "number", group: "E.030", step: 0.05 },
    { key: "Tp", label: "Tp", unit: "s", type: "number", group: "E.030", step: 0.05 },
    { key: "Tl", label: "TL", unit: "s", type: "number", group: "E.030", step: 0.1 },
    { key: "U", label: "Categoría U", unit: "", type: "number", group: "E.030", step: 0.1 },
    { key: "R0", label: "R0 sistema", unit: "", type: "number", group: "E.030", step: 0.5 },
    { key: "Ia", label: "Ia planta", unit: "", type: "number", group: "E.030", step: 0.05 },
    { key: "Ip", label: "Ip altura", unit: "", type: "number", group: "E.030", step: 0.05 },
    { key: "Ct", label: "Ct", unit: "", type: "number", group: "Periodo", step: 1 },
    { key: "nPisos", label: "N° pisos", unit: "", type: "number", group: "Edificio", step: 1 },
    { key: "hPiso", label: "Altura de piso", unit: "m", type: "number", group: "Edificio", step: 0.05 },
    { key: "P", label: "Peso sísmico P", unit: "t", type: "number", group: "Edificio", step: 10 },
    { key: "sistema", label: "Sistema (deriva)", type: "select", group: "E.030", options: [
      { value: "concreto", label: "Concreto armado (0.007)" },
      { value: "albañileria", label: "Albañilería (0.005)" },
    ] },
  ],
};

export const MODULE_DEFAULTS: Record<string, Inputs> = {
  "estribo-voladizo": { H: 7, B: 5.1, D: 1.1, Lpunta: 1.1, tsup: 0.3, tinf: 0.9, Ltab: 20, hviga: 1.5, S: 10.01, hz: 1.5, PDC: 12, PDW: 1.8, PLLIM: 9.494, BR: 1.99, hBR: 1.8, phi: 30, delta: 20, beta: 0, theta: 90, gs: 1.925, qadm: 2.67, FS: 3, PGA: 0.3, FPGA: 1.2, gc: 2.4, fc: 210, fy: 4200 },
  "estribo-gravedad": { H: 4, Ltab: 12, e: 0.8, eLosa: 0.3, hz: 1, B: 2.5, a: 0.3, bTalon: 0.3, h: 0.5, N: 0.5, tBack: 0.5, PDC: 7, PDW: 0.8, PLLIM: 9, BR: 0.3, WS: 0.15, CRSHTU: 0.9, hBR: 1.8, phi: 31, delta: 24, beta: 0, theta: 90, gc: 2.32, gs: 1.6, qr: 2, suelo: "no-rocoso" },
  "estribo-pantalla": { H: 7, B: 4.2, D: 0.8, Lpunta: 1.0, tsup: 0.3, tinf: 0.45, PDC: 12, PDW: 1.8, PLLIM: 9.494, BR: 1.99, phi: 30, delta: 0, gs: 1.925, qadm: 2.67, PGA: 0.3, FPGA: 1.2, fc: 210, fy: 4200, gc: 2.4, FS: 3, hBR: 1.8, Ltab: 20, hviga: 1.5, S: 10, hz: 1.5, beta: 0, theta: 90 },
  "losa-puente": { L: 24, S: 2.8, bViga: 0.4, t: 0.2, eAsf: 0.05, nTramos: 1, fc: 280, fy: 4200, gc: 2.4, gAsf: 2.24 },
  "puente-vehicular": { L: 25, Btot: 8.4, Blibre: 7.6, nVigas: 4, S: 2.1, t: 0.2, hViga: 1.4, bViga: 0.35, eAsf: 0.05, gBarrera: 0.6, fc: 280, fy: 4200 },
  "viga-presforzada": { L: 30, S: 2, t: 0.18, h: 1.7, b: 0.3, tf: 0.25, tw: 0.18, fci: 280, fcf: 350, fpu: 18984, perdidas: 15, eAsf: 0.05 },
  "dispositivos-apoyo": { PDC: 29790, PDW: 8131, PLL: 7985, bViga: 30, L: 33, G: 9.14, sigma: 87.9, dT: 30, fy: 2530 },
  "placa-apoyo": { Pu: 192000, fc: 210, fy: 2530, tipo: "circular" },
  travesano: { b: 0.5, h: 0.6, rec: 0.05, S: 2.1, nBar: 5, fc: 210, fy: 4200 },
  "puente-cajon": { L: 28, B: 8.4, h: 1.6, tw: 0.3, tf: 0.22, tb: 0.2, fc: 280, fy: 4200 },
  columnas: { b: 40, h: 40, rec: 4, nBar: 8, bar: '3/4"', Pu: 180, Mu: 12, fc: 210, fy: 4200 },
  "viga-flexion": { b: 25, h: 45, L: 8, rec: 5, L1: 4, L2: 4, cv: 170, combo: "e060", fc: 250, fy: 4200 },
  "viga-cortante": { b: 30, h: 45, L: 5.6, rec: 6, wu: 7000, Av: 1.42, fc: 210, fy: 4200 },
  "viga-doble-armadura": { b: 30, h: 50, d: 44, dp: 5, L: 8, wu: 5, fc: 210, fy: 4200 },
  "viga-compuesta": { D: 121.92, Bf: 50.8, tf: 2.54, tw: 0.95, hc: 15, be: 180, L: 35.5, Fy: 2532, fc: 210 },
  "zapata-aislada": { t1: 0.55, t2: 0.8, PD: 180, PL: 65, qt: 3.5, Df: 1.7, gt: 2.1, sc: 0.5, hc: 0.7, T: 3, S: 2.75, fc: 280, fy: 4200, rec: 7.5 },
  "zapata-combinada": { Pd1: 75, Pl1: 35, t1: 0.5, Pd2: 125, Pl2: 50, t2: 0.65, eje: 5, Lz: 7.35, b: 2.4, hc: 0.7, qt: 2, Df: 1.5, gt: 2.1, fc: 210, fy: 4200 },
  "viga-cimentacion": { b: 0.3, h: 0.5, L: 5, e: 0.4, Pexc: 80, fc: 210, fy: 4200 },
  platea: { Lx: 20, Ly: 17.45, t: 0.45, Df: 1.1, Ks: 8, qa: 1.2, Ptot: 1800, fc: 210 },
  pilotes: { b: 0.3, t: 0.6, PD: 80, PL: 40, Df: 6.5, phi: 24, g: 1.5, D: 0.4, k: 1 },
  "escalera-dos-tramos": { p: 0.28, cp: 0.175, b: 1.2, n1: 9, n2: 8, t: 0.15, sc: 0.4, acab: 0.1, fc: 210, fy: 4200 },
  "escalera-descanso": { p: 0.3, cp: 0.18, b: 1.2, n: 10, Ld: 1.2, t: 0.18, sc: 0.4, acab: 0.12, fc: 210, fy: 4200 },
  "edificio-sismo": { Z: 0.45, S: 1.1, Tp: 1, Tl: 1.6, U: 1, R0: 6, Ia: 1, Ip: 1, Ct: 35, nPisos: 4, hPiso: 2.7, P: 1200, sistema: "concreto" },
};
