import { art, type Noticia } from "./tipos";

/** Tecnología y ciencia · 7 categorías × 3 noticias. */
export const NOTICIAS_TECNO: Noticia[] = [
  // ── 6 · Tecnología ──
  art("tecnologia", 1,
    "Fibra óptica llega a 1 200 nuevas localidades con la Red Dorsal",
    "Pronatel conecta colegios y postas de salud en zonas altoandinas y amazónicas.",
    [
      "El Programa Nacional de Telecomunicaciones culminó la conexión de 1 200 localidades a la Red Dorsal de Fibra Óptica. Colegios, postas y comisarías acceden por primera vez a internet de alta velocidad.",
      "La inversión supera los 400 millones de soles y prioriza corredores de Cusco, Puno, Huancavelica y Loreto. Cada nodo incluye wifi comunitario gratuito en la plaza principal.",
      "Operadores regionales alquilarán capacidad mayorista para llevar 4G y 5G a los anexos. Osiptel supervisará que las tarifas rurales no superen a las urbanas.",
      "El reto es la energía: 300 localidades requieren paneles solares para alimentar las estaciones. Pronatel licitará ese componente antes de fin de año.",
      "Cada nodo dorsal entrega 10 Gbps compartidos entre instituciones públicas y operadores. La latencia hacia Lima bajó de 120 a 35 milisegundos en los tramos ya iluminados.",
      "El modelo de sostenibilidad exige que los gobiernos regionales asuman el mantenimiento desde el tercer año. Pronatel capacita a 600 técnicos locales en fibra y energía solar.",
    ],
    [
      { medio: "Pronatel – MTC", nota: "Reporte de avance de la Red Dorsal, setiembre 2026." },
      { medio: "Osiptel", nota: "Supervisión de tarifas rurales." },
    ],
    "19 sep 2026"),
  art("tecnologia", 2,
    "5G cubre ya el 60% de Lima y se expande a seis regiones",
    "Arequipa, Trujillo y Chiclayo lideran la adopción fuera de la capital.",
    [
      "La cobertura 5G alcanzó al 60% de la población de Lima y empezó su despliegue en seis regiones. Los operadores activaron 800 nuevas radiobases en el último trimestre.",
      "La velocidad promedio móvil subió a 85 Mbps, casi el doble que con 4G. Los planes con 5G bajaron de precio y ya representan el 30% de las líneas pospago.",
      "El MTC subastará un nuevo bloque de espectro en 3,5 GHz para completar la cobertura nacional. La meta oficial es 70% de la población con 5G al 2028.",
      "Especialistas piden usar la red para telemedicina y educación rural. Pilotos en Puno y Ayacucho muestran consultas remotas con buena calidad de video.",
      "La red privada 5G despega en minería: tres operaciones usan teleoperación de camiones con latencias de 10 milisegundos. Cada mina conectada invierte unos 8 millones de dólares.",
      "El apagado progresivo del 2G liberará espectro para ampliar cobertura rural. Osiptel fijó 2028 como fecha límite con teléfonos básicos de recambio subsidiados.",
    ],
    [
      { medio: "MTC", nota: "Balance de despliegue 5G, 2026." },
      { medio: "Osiptel", nota: "Medición de velocidades móviles." },
    ],
    "17 sep 2026"),
  art("tecnologia", 3,
    "Semiconductores: Perú se suma a la cadena regional de ensamblaje",
    "Una planta en Lurín producirá chips de prueba y empaques desde 2027.",
    [
      "El Perú ingresó a la cadena regional de semiconductores con una planta de ensamblaje y pruebas en Lurín. La inversión de 90 millones de dólares generará 600 empleos calificados.",
      "La planta producirá empaques y pruebas para chips de uso automotriz e industrial. Universidades como la UNI y San Marcos firmaron convenios de formación de técnicos.",
      "El gobierno ofrece una zona económica especial con beneficios tributarios por diez años. Se negocia además un centro de diseño con ingenieros peruanos.",
      "Analistas consideran el paso modesto pero estratégico frente a la guerra comercial de chips. Recomiendan asegurar agua, energía estable y talento bilingüe.",
      "El ensamblaje (OSAT) es la puerta de entrada: Malasia y Vietnam empezaron igual hace 20 años. El proceso usa salas limpias clase 10 000 y agua ultrapura en grandes volúmenes.",
      "La segunda fase apuntaría al diseño de chips maduros para agro y minería. Un centro de diseño emplea 200 ingenieros con salarios que triplican el promedio industrial.",
    ],
    [
      { medio: "ProInversión", nota: "Anuncio de inversión tecnológica." },
      { medio: "Agencia Andina", nota: "Convenios con universidades." },
    ],
    "15 sep 2026"),
  // ── 7 · Inteligencia Artificial ──
  art("inteligencia-artificial", 1,
    "El 45% de grandes empresas peruanas ya usa IA en sus procesos",
    "Atención al cliente y detección de fraude lideran los casos de uso.",
    [
      "El 45% de las grandes empresas del país ya emplea inteligencia artificial en al menos un proceso crítico. Los usos más extendidos son chatbots de atención, scoring crediticio y detección de fraude.",
      "El estudio, elaborado con 300 compañías, muestra que la productividad sube 18% en áreas que adoptan IA generativa. Banca, retail y minería lideran la inversión.",
      "La barrera principal es el talento: siete de cada diez firmas no encuentran científicos de datos. Universidades e institutos duplicaron vacantes en carreras afines.",
      "El Ejecutivo prepara una estrategia nacional de IA con sandbox regulatorio y compras públicas innovadoras. El documento se someterá a consulta antes de fin de año.",
      "En minería, los gemelos digitales con IA predicen fallas de chancadoras con 90% de acierto. Cada hora de parada evitada ahorra hasta 200 000 dólares en una gran operación.",
      "El sector público ensaya IA en expedientes: la Sunat y el Poder Judicial pilotean clasificación automática. Los gremios exigen auditorías de sesgo antes de decisiones que afecten derechos.",
    ],
    [
      { medio: "Secretaría de Gobierno Digital – PCM", nota: "Encuesta de adopción de IA 2026." },
      { medio: "Diario Gestión", nota: "Casos de uso en banca y retail." },
    ],
    "19 sep 2026"),
  art("inteligencia-artificial", 2,
    "Modelos abiertos en español impulsan quechua y aimara digitales",
    "Comunidades lingüísticas entrenan traductores con IA de código abierto.",
    [
      "Colectivos de hablantes de quechua y aimara entrenan modelos abiertos de traducción automática. El proyecto reúne 50 000 frases paralelas validadas por docentes bilingües.",
      "Las herramientas ya traducen documentos educativos y actas comunales con precisión creciente. El Ministerio de Cultura evalúa adoptarlas en sus servicios de interpretación.",
      "Lingüistas advierten que los modelos comerciales ignoran las lenguas originarias por falta de datos. Los proyectos abiertos corrigen ese sesgo con licencias libres.",
      "La próxima fase incluye reconocimiento de voz para alfabetización de adultos. Se buscan voluntarios hablantes en Cusco, Puno y Apurímac.",
      "Técnicamente, el quechua exige modelos morfológicos: una palabra aglutina lo que en español son frases. Los equipos usan tokenizadores propios entrenados desde cero.",
      "El proyecto libera datasets con licencias abiertas para que startups creen subtitulado y doblaje. YouTube y TikTok ya prueban subtítulos automáticos en quechua collao.",
    ],
    [
      { medio: "Ministerio de Cultura", nota: "Programa de lenguas originarias digitales." },
      { medio: "Agencia Andina", nota: "Cobertura del proyecto de traducción." },
    ],
    "16 sep 2026"),
  art("inteligencia-artificial", 3,
    "Congreso debate ley de IA: transparencia y sanciones por deepfakes",
    "El dictamen exige etiquetar contenido sintético en campañas electorales.",
    [
      "La Comisión de Ciencia del Congreso aprobó el dictamen de la ley de inteligencia artificial. La norma exige transparencia en sistemas de decisión automatizada y sanciona los deepfakes electorales.",
      "Las plataformas deberán etiquetar contenido generado por IA y responder en 48 horas ante denuncias. Las multas llegan a 500 UIT para casos de fraude o suplantación.",
      "Gremios tecnológicos apoyan la regulación basada en riesgos pero piden no frenar la innovación. Proponen un periodo de adecuación de 18 meses para las mypes.",
      "De aprobarse en el Pleno, el Perú se sumaría a Chile y Brasil con marco propio. La votación final está prevista para octubre.",
      "El enfoque de riesgo clasifica los sistemas en prohibidos, altos y limitados, siguiendo el modelo europeo. El reconocimiento facial masivo quedaría prohibido salvo orden judicial.",
      "La autoridad de aplicación sería la Secretaría de Gobierno Digital con un consejo multisectorial. Las sanciones llegan al 4% de la facturación para infracciones muy graves.",
    ],
    [
      { medio: "Congreso de la República", nota: "Dictamen de la Comisión de Ciencia." },
      { medio: "RPP", nota: "Reacciones de gremios tecnológicos." },
    ],
    "15 sep 2026"),
  // ── 8 · Ingeniería ──
  art("ingenieria", 1,
    "Puente Santa Rosa del Callao entra a su fase final de construcción",
    "La obra de 900 metros unirá la Costa Verde con el puerto en 2027.",
    [
      "El puente Santa Rosa, de 900 metros sobre el río Rímac, entró a su fase final con el izaje de las vigas principales. La obra conectará la Costa Verde con el terminal portuario del Callao.",
      "El MTC informó un avance del 82% y una inversión de 380 millones de soles. La estructura, atirantada y sismorresistente, soportará 6 000 vehículos por hora.",
      "La supervisión técnica incluye instrumentación con sensores de deformación en tiempo real. El Colegio de Ingenieros participa como veedor del control de calidad del concreto.",
      "Transportistas del puerto estiman ahorrar 40 minutos por viaje hacia Lima norte. La inauguración está prevista para el primer semestre de 2027.",
      "El tablero atirantado usa concreto de 60 MPa con vainas de pretensado de 19 torones. Cada tirante se tesó a 1 200 toneladas con control de alargamiento milimétrico.",
      "La cimentación resolvió el suelo licuable del Rímac con pilotes de 40 metros. El estudio de peligro sísmico exigió diseño para 0,65 g de aceleración.",
    ],
    [
      { medio: "MTC – Provías Nacional", nota: "Reporte de avance de obra." },
      { medio: "Colegio de Ingenieros del Perú", nota: "Informe de veeduría técnica." },
    ],
    "18 sep 2026"),
  art("ingenieria", 2,
    "Represa Palo Redondo retoma obras tras una década paralizada",
    "Chavimochic III irrigará 63 000 hectáreas en La Libertad.",
    [
      "Las obras de la represa Palo Redondo, paralizadas hace una década, se retomaron con un nuevo contratista. La presa de 96 metros es la pieza clave de la tercera etapa de Chavimochic.",
      "El proyecto irrigará 63 000 hectáreas nuevas y mejorará otras 48 000 en los valles de Chao, Virú y Moche. La inversión comprometida es de 720 millones de dólares.",
      "El Gobierno Regional de La Libertad adjudicó la supervisión a un consorcio internacional con experiencia en presas andinas. El plazo de ejecución es de 42 meses.",
      "Agroexportadores proyectan 1 200 millones anuales adicionales en arándanos, paltas y espárragos. Piden que la subasta de tierras priorice a productores medianos.",
      "Palo Redondo es una presa de concreto compactado con rodillo de 96 metros. La técnica CCR permite vaciar 300 000 metros cúbicos con control térmico estricto.",
      "El canal madre de 127 kilómetros incluye túneles y sifones para cruzar quebradas. Su capacidad de 95 m³/s abastecerá también a Trujillo en época de estiaje.",
    ],
    [
      { medio: "Gobierno Regional de La Libertad", nota: "Cronograma Chavimochic III." },
      { medio: "Midagri", nota: "Metas de irrigación." },
    ],
    "16 sep 2026"),
  art("ingenieria", 3,
    "Supervisión técnica digital: drones y BIM obligatorios en obras mayores",
    "La norma exige modelado de información en proyectos de más de 50 millones de soles.",
    [
      "El Ejecutivo oficializó el uso obligatorio de BIM y drones en la supervisión de obras públicas mayores a 50 millones de soles. La medida busca cerrar sobrecostos y ampliaciones injustificadas.",
      "Cada proyecto deberá publicar su gemelo digital con avances mensuales verificables por la Contraloría. Los expedientes sin modelo no obtendrán conformidad.",
      "La Contraloría estima que la fiscalización digital reducirá 15% las controversias en arbitrajes. Capacitará a 2 000 supervisores en metodologías colaborativas.",
      "Constructoras grandes apoyan la norma, pero las mypes piden plazos de adecuación. Habrá un régimen de transición de dos años para gobiernos locales.",
      "El BIM nivel 2 exige modelos federados con detección de interferencias antes de licitar. Países que lo adoptaron recortaron 20% los adicionales de obra.",
      "Los drones con LiDAR generan nubes de 500 puntos por metro cuadrado para cubicar movimientos de tierra. La Contraloría cruzará esos volúmenes con las valorizaciones pagadas.",
    ],
    [
      { medio: "Presidencia del Consejo de Ministros", nota: "Decreto sobre BIM en obra pública." },
      { medio: "Contraloría General", nota: "Plan de fiscalización digital." },
    ],
    "15 sep 2026"),
  // ── 9 · Ciencias ──
  art("ciencias", 1,
    "Científicos peruanos publican hallazgo sobre glaciares tropicales en Nature",
    "El estudio advierte que el Perú perdió el 56% de su superficie glaciar.",
    [
      "Un equipo de la Universidad Cayetano Heredia y el Inaigem publicó en Nature el mayor estudio sobre glaciares tropicales andinos. Concluye que el país perdió el 56% de su superficie glaciar en seis décadas.",
      "El trabajo combina imágenes satelitales de 1962 a la fecha con mediciones de campo en la Cordillera Blanca. Es la serie más completa disponible para los Andes tropicales.",
      "Los autores advierten que 18 millones de peruanos dependen del agua glaciar en época seca. Proponen monitoreo comunitario y represas altoandinas como adaptación.",
      "El paper fue revisado por pares durante ocho meses y ya acumula citas internacionales. Sus datos alimentarán el próximo informe del IPCC.",
      "Metodológicamente, el equipo corrigió imágenes Landsat con modelos de elevación de 30 metros. El margen de error del área glaciar es menor al 5%.",
      "El retroceso acelera la formación de lagunas peligrosas: hay 30 identificadas con riesgo de aluvión. El Inaigem monitorea con sensores de nivel y alerta temprana.",
    ],
    [
      { medio: "Revista Nature", nota: "Artículo revisado por pares, setiembre 2026." },
      { medio: "Inaigem", nota: "Comunicado sobre el estudio." },
    ],
    "17 sep 2026"),
  art("ciencias", 2,
    "Nueva especie de rana de cristal descubierta en el Manu",
    "Biólogos de San Marcos registraron el anfibio a 1 800 metros de altitud.",
    [
      "Biólogos de la Universidad Nacional Mayor de San Marcos describieron una nueva especie de rana de cristal en el Parque Nacional del Manu. El anfibio, de vientre transparente, habita quebradas a 1 800 metros.",
      "El hallazgo se publicó tras cinco años de expediciones y análisis genéticos. Los autores la nombraron en honor a las guardaparques de la reserva.",
      "La especie es bioindicadora: su presencia revela agua limpia y bosque intacto. Los investigadores piden ampliar la zona de amortiguamiento frente a la minería ilegal.",
      "El Sernanp incorporará el registro a su plan de monitoreo. Se estima que el Manu alberga aún decenas de especies por describir.",
      "La rana de cristal respira en parte a través de su piel transparente, lo que la hace termómetro del bosque nublado. Su canto nocturno se graba con micrófonos autónomos.",
      "El análisis genético del gen 16S confirmó 8% de divergencia con su pariente más cercano. El holotipo quedó depositado en el Museo de Historia Natural.",
    ],
    [
      { medio: "UNMSM – Museo de Historia Natural", nota: "Descripción taxonómica." },
      { medio: "Sernanp", nota: "Registro en el Manu." },
    ],
    "16 sep 2026"),
  art("ciencias", 3,
    "Concytec quintuplica fondos para investigación universitaria",
    "El nuevo esquema financia 200 proyectos con hasta 500 000 soles cada uno.",
    [
      "El Concytec anunció la quintuplicación de su fondo concursable para investigación universitaria. Doscientos proyectos recibirán hasta 500 000 soles en dos años.",
      "Las líneas priorizadas son salud, agua, energía y biodiversidad, con puntaje extra para equipos regionales. El 60% de los fondos saldrá de Lima por primera vez.",
      "Rectores saludaron el anuncio pero exigen desembolsos puntuales, el histórico talón de Aquiles. El Concytec prometió pagos trimestrales automáticos.",
      "El Perú invierte apenas 0,15% del PBI en investigación. La meta oficial es llegar a 0,5% al 2030 con aporte privado.",
      "Los fondos concursables exigen contrapartida del 20% y publicación en revistas indexadas. El 40% de los proyectos ganadores incluye tesistas de pregrado.",
      "El canon minero podría financiar ciencia regional: solo se ejecuta el 30% disponible. Universidades piden ventanilla única para no perder los recursos.",
    ],
    [
      { medio: "Concytec", nota: "Bases del fondo concursable 2026." },
      { medio: "Agencia Andina", nota: "Reacciones de rectores." },
    ],
    "15 sep 2026"),
  // ── 10 · Medicina y Salud ──
  art("medicina-salud", 1,
    "Minsa inicia vacunación contra el dengue en 12 regiones",
    "La campaña prioriza a niños y adolescentes de zonas endémicas.",
    [
      "El Ministerio de Salud inició la vacunación contra el dengue en doce regiones endémicas. La primera fase cubre a 800 000 niños y adolescentes de 6 a 16 años.",
      "El Perú adquirió 1,6 millones de dosis de la vacuna tetravalente con eficacia superior al 80% contra hospitalizaciones. La aplicación es gratuita en establecimientos públicos.",
      "El dengue dejó 180 000 casos este año, con Piura, Loreto e Ica como focos. Las autoridades insisten en eliminar criaderos: la vacuna no reemplaza el control del zancudo.",
      "Colegios médicos piden extender la cobertura a adultos mayores con comorbilidades. El Minsa evaluará la ampliación según la llegada de nuevos lotes.",
      "La vacuna tetravalente requiere dos dosis separadas por tres meses y protege contra los cuatro serotipos. Su eficacia contra dengue grave supera el 85% en ensayos.",
      "El control vectorial combina abatización focal y fumigación espacial en horarios del mosquito. Sin eliminar criaderos, la transmisión persiste aunque se vacune.",
    ],
    [
      { medio: "Minsa", nota: "Plan nacional de vacunación contra el dengue." },
      { medio: "OPS/OMS Perú", nota: "Recomendaciones técnicas." },
    ],
    "19 sep 2026"),
  art("medicina-salud", 2,
    "Hospital Rebagliati estrena centro de cirugía robótica",
    "El sistema atenderá 1 200 operaciones anuales de alta complejidad.",
    [
      "El hospital Rebagliati Martins inauguró el primer centro público de cirugía robótica del país. El equipo permitirá 1 200 operaciones anuales de urología, ginecología y cirugía digestiva.",
      "La cirugía asistida reduce el sangrado, el dolor y los días de hospitalización a la mitad. Veinte cirujanos de EsSalud se entrenaron durante un año en el extranjero.",
      "La inversión fue de 45 millones de soles, financiados con recursos propios de la seguridad social. Se priorizará a pacientes en lista de espera oncológica.",
      "Especialistas piden replicar el modelo en Arequipa y Trujillo. EsSalud evalúa un segundo equipo para el sur en 2027.",
      "El sistema Da Vinci opera con brazos de 8 milímetros e imagen 3D magnificada diez veces. El cirujano controla desde una consola con pedales y mandos.",
      "Cada procedimiento robótico cuesta 30% más que el laparoscópico, pero el alta precoz compensa. El Rebagliati proyecta 300 prostatectomías anuales como primera línea.",
    ],
    [
      { medio: "EsSalud", nota: "Inauguración del centro robótico." },
      { medio: "Colegio Médico del Perú", nota: "Opinión técnica." },
    ],
    "17 sep 2026"),
  art("medicina-salud", 3,
    "Anemia infantil baja a 38% pero sigue lejos de la meta",
    "El Midis refuerza la suplementación con hierro en 800 distritos.",
    [
      "La anemia en niños menores de tres años bajó a 38%, dos puntos menos que el año pasado. El Midis reconoció, sin embargo, que el ritmo es insuficiente para la meta de 30% al 2027.",
      "El programa refuerza la suplementación con hierro y las visitas domiciliarias en 800 distritos priorizados. Madres gestantes reciben consejería nutricional mensual.",
      "Nutricionistas advierten que la crisis de precios redujo el consumo de carnes y sangrecita. Piden vales de alimentos proteicos para familias en pobreza extrema.",
      "Regiones como Puno y Huancavelica superan el 55% de prevalencia. El Ejecutivo firmó convenios con gobiernos locales para compras directas de alimentos ricos en hierro.",
      "La anemia se mide con hemoglobina capilar y el punto de corte se ajusta por altitud. Sobre los 3 000 metros, el umbral sube y la prevalencia real es menor a la reportada.",
      "La suplementación con hierro polimaltosado reduce el abandono por efectos gástricos. Los multimicronutrientes en polvo para papillas cubren al 70% de niños menores de tres años.",
    ],
    [
      { medio: "INEI – ENDES", nota: "Indicadores de anemia 2026." },
      { medio: "Midis", nota: "Estrategia de suplementación." },
    ],
    "15 sep 2026"),
  // ── 11 · Ciberseguridad ──
  art("ciberseguridad", 1,
    "Ransomware ataca a 40 municipalidades: exigen rescates en cripto",
    "La PCM activó el protocolo nacional de respuesta a incidentes.",
    [
      "Una oleada de ransomware afectó a 40 municipalidades del interior, cifrando sus sistemas de rentas y catastro. Los atacantes exigen rescates en criptomonedas equivalentes a 50 000 dólares por comuna.",
      "La Secretaría de Gobierno Digital activó el protocolo nacional y aisló las redes comprometidas. Recomendó no pagar y restaurar desde respaldos certificados.",
      "La mayoría de municipios no tenía copias actualizadas ni personal de seguridad informática. Solo el 12% de gobiernos locales cuenta con un oficial de seguridad de la información.",
      "Expertos piden una ley que obligue respaldos inmutables y reporte de incidentes en 72 horas. El Congreso incluyó el tema en la agenda de la ley de IA.",
      "El ransomware usado sería de la familia LockBit, que filtra datos antes de cifrar. El vector inicial habría sido un correo con macro maliciosa a Rentas.",
      "La respuesta sigue el marco NIST: contener, erradicar y recuperar con imágenes forenses. Sin cadena de custodia, la evidencia digital no sirve en juicio.",
    ],
    [
      { medio: "PCM – Segdi", nota: "Alerta de seguridad y protocolo activado." },
      { medio: "Divindat – PNP", nota: "Investigación del ataque." },
    ],
    "18 sep 2026"),
  art("ciberseguridad", 2,
    "Estafas por Yape falso crecen 60%: así operan los delincuentes",
    "Pantallazos adulterados y QR manipulados son el modus operandi.",
    [
      "Las denuncias por estafas con comprobantes falsos de billeteras digitales crecieron 60% en un año. Los delincuentes usan aplicativos que generan pantallazos y audios de transferencia falsos.",
      "Bodegas, taxistas y repartidores son las víctimas más frecuentes, con pérdidas promedio de 300 soles. La Divindat desarticuló tres bandas dedicadas a esta modalidad en Lima y Callao.",
      "Los bancos recomiendan verificar siempre el abono en la propia aplicación antes de entregar el producto. También habilitar notificaciones push y límites diarios.",
      "El BCRP evalúa un sistema de verificación instantánea por QR oficial. La norma técnica se publicaría antes de fin de año.",
      "Las apps falsas clonan el sonido y la animación de confirmación al milímetro. Solo el registro en el extracto del receptor confirma el abono real.",
      "La autenticación en dos pasos y los límites por operación reducen el daño. Los bancos deberán alertar en segundos ante patrones de vaciado de cuentas.",
    ],
    [
      { medio: "Divindat – PNP", nota: "Balance de denuncias 2026." },
      { medio: "BCRP", nota: "Medidas de seguridad en pagos." },
    ],
    "16 sep 2026"),
  art("ciberseguridad", 3,
    "Bancos deberán reponer fondos robados en 15 días, dispone la SBS",
    "La norma de protección al usuario financiero entra en vigencia en enero.",
    [
      "La SBS dispuso que los bancos repongan en 15 días los fondos sustraídos por fraudes electrónicos no atribuibles al cliente. La norma rige desde enero para todas las entidades.",
      "Las entidades deberán demostrar negligencia del usuario para negar la devolución. El silencio administrativo positivo aplicará a favor del reclamante.",
      "Asbanc advirtió sobre el riesgo de autofraudes y pidió una central de casos sospechosos. La SBS aseguró que habrá cruces biométricos para detectar patrones.",
      "Asociaciones de consumidores celebraron la medida como histórica. Estiman 120 000 reclamos anuales por operaciones no reconocidas.",
      "El procedimiento exige reclamo en 30 días y resolución bancaria en 15. Si el banco niega, debe probar negligencia grave con peritaje informático.",
      "El phishing con SIM swapping concentra las pérdidas mayores, de hasta 50 000 soles. La SBS obligará a validar biométricamente los cambios de chip.",
    ],
    [
      { medio: "SBS", nota: "Reglamento de protección al usuario financiero." },
      { medio: "Asbanc", nota: "Posición del gremio bancario." },
    ],
    "15 sep 2026"),
  // ── 12 · Espacio y Astronomía ──
  art("espacio-astronomia", 1,
    "PerúSAT-1 cumple 10 años y tendrá sucesor con resolución submétrica",
    "El nuevo satélite se contratará bajo esquema gobierno a gobierno.",
    [
      "El satélite PerúSAT-1 cumplió una década entregando 150 000 imágenes para defensa, catastro y gestión de desastres. El Ejecutivo anunció su reemplazo con resolución submétrica.",
      "El sucesor se contratará bajo esquema gobierno a gobierno con transferencia tecnológica. Incluirá capacitación de 50 ingenieros peruanos en operación satelital.",
      "Conida estima que cada sol invertido en imágenes evita diez en emergencias por huaicos e incendios. Los ministerios son los principales usuarios de la data.",
      "Astrónomos piden reservar capacidad para ciencia y educación. El nuevo sistema incluirá un canal abierto para universidades.",
      "El PerúSAT-1 orbita a 702 kilómetros en órbita heliosíncrona con revisita de 3 días. Su resolución pancromática de 70 centímetros detecta hasta vehículos.",
      "El sucesor apuntaría a 30 centímetros y video en vivo sobre zonas de desastre. La ventana de lanzamiento se negocia para 2028 con un cohete Vega-C.",
    ],
    [
      { medio: "Conida", nota: "Balance de 10 años del PerúSAT-1." },
      { medio: "Agencia Espacial del Perú", nota: "Plan del satélite sucesor." },
    ],
    "17 sep 2026"),
  art("espacio-astronomia", 2,
    "Eclipse lunar total se verá en todo el Perú este mes",
    "El Ingemmet y planetarios organizan vigilias públicas gratuitas.",
    [
      "Un eclipse total de Luna será visible en todo el territorio peruano en la madrugada del próximo fin de semana. La fase total durará 82 minutos con la Luna teñida de rojo.",
      "El fenómeno podrá observarse a simple vista sin riesgo, a diferencia de los eclipses solares. Los planetarios de Lima, Cusco y Arequipa abrirán vigilias gratuitas con telescopios.",
      "Astrónomos andinos recuerdan que las culturas preíncas interpretaban estos eventos en sus calendarios agrícolas. Habrá charlas bilingües en quechua en el planetario del Cusco.",
      "Se recomienda buscar cielos oscuros lejos de la contaminación lumínica. El siguiente eclipse total visible desde el Perú ocurrirá en 2028.",
      "El color rojizo se debe a la refracción de la luz solar en la atmósfera terrestre. Las cenizas volcánicas recientes podrían intensificar el tono cobrizo.",
      "Durante la totalidad, la Luna se atenúa 10 000 veces y emergen estrellas. Los fotógrafos recomiendan trípode y exposiciones de 1 a 4 segundos.",
    ],
    [
      { medio: "Instituto Geofísico del Perú", nota: "Guía de observación del eclipse." },
      { medio: "Planetario Nacional", nota: "Programa de vigilias." },
    ],
    "16 sep 2026"),
  art("espacio-astronomia", 3,
    "Base espacial de Talara entra a su etapa de diseño final",
    "El puerto espacial ecuatorial apunta a microlanzadores comerciales.",
    [
      "El proyecto del puerto espacial de Talara, en la línea ecuatorial, entró a su etapa de diseño final. La ubicación permite ahorrar hasta 15% de combustible en lanzamientos orbitales.",
      "Conida firmó memorandos con tres operadores de microlanzadores interesados en la base. El modelo será una concesión a 30 años con participación estatal.",
      "La inversión estimada es de 350 millones de dólares en pistas, integración y seguimiento. Piura podría recibir 2 000 empleos directos e indirectos.",
      "Expertos piden un marco de licencias y responsabilidad por desechos orbitales. El Congreso evalúa una ley de actividades espaciales este año.",
      "Talara ofrece latitud casi ecuatorial: la velocidad de rotación terrestre aporta 460 m/s gratis al lanzamiento. Esa ventaja recorta 15% el combustible.",
      "El segmento de microlanzadores mueve 200 despegues anuales en el mundo. Captar solo cinco al año dejaría 50 millones de dólares en servicios locales.",
    ],
    [
      { medio: "Conida", nota: "Avance del puerto espacial." },
      { medio: "Gobierno Regional de Piura", nota: "Impacto económico proyectado." },
    ],
    "15 sep 2026"),
];
