import { art, type Noticia } from "./tipos";

/** Seguridad y justicia · 3 categorías × 3 noticias. Deporte · 2 categorías × 3 noticias. */
export const NOTICIAS_SEGURIDAD: Noticia[] = [
  // ── 13 · Delincuencia y Seguridad Ciudadana ──
  art("delincuencia-seguridad-ciudadana", 1,
    "PNP desarticula 120 bandas y refuerza operativos en Lima norte",
    "Los homicidios bajaron 12% en el trimestre, según el Mininter.",
    [
      "La Policía Nacional desarticuló 120 bandas criminales en operativos simultáneos en Lima norte y Callao. Se incautaron 340 armas de fuego y 12 toneladas de droga.",
      "El Ministerio del Interior informó que los homicidios bajaron 12% en el trimestre. Los distritos con mayor reducción son Comas, San Martín de Porres y Ventanilla.",
      "El plan incluye 2 000 nuevos efectivos y 300 patrulleros con cámaras corporales. Serenazgos municipales se integrarán al patrullaje bajo mando policial.",
      "Vecinos piden sostener los operativos más allá de la coyuntura. El Mininter prometió publicar mapas del delito actualizados cada mes.",
      "El plan Amanecer Seguro concentra patrullaje entre las 4 y 7 de la mañana, la franja con más robos. Los serenazgos aportan 1 200 cámaras con reconocimiento de placas.",
      "En inteligencia, la Dirincri triplicó las escuchas autorizadas judicialmente este año. El 60% de las bandas cayó por seguimiento de celulares robados.",
    ],
    [
      { medio: "Mininter", nota: "Balance de operativos, setiembre 2026." },
      { medio: "PNP – Dirección de Investigación Criminal", nota: "Reporte de bandas desarticuladas." },
    ],
    "19 sep 2026"),
  art("delincuencia-seguridad-ciudadana", 2,
    "Percepción de inseguridad baja a 78% pero sigue entre las más altas",
    "El INEI reporta mejora en Lima y empeora en Trujillo y Piura.",
    [
      "La percepción de inseguridad bajó a 78% a nivel nacional, dos puntos menos que el año pasado. El INEI destaca mejoras en Lima centro y el sur andino.",
      "Trujillo y Piura, en cambio, empeoraron por la extorsión al transporte y el comercio. En el norte, nueve de cada diez ciudadanos se sienten inseguros.",
      "El 45% de hogares adoptó medidas como rejas, cámaras o alarmas comunitarias. El gasto en seguridad privada ya equivale al 1,2% del PBI.",
      "Expertos piden medir también la victimización real, que cayó menos que la percepción. Recomiendan alumbrado público y recuperación de espacios como política preventiva.",
      "La victimización alcanza al 27% de hogares urbanos: uno de cada cuatro sufrió un delito este año. El robo de celulares concentra el 40% de los casos.",
      "La encuesta del INEI cubre 28 000 viviendas con margen de 1,2%. Los resultados alimentan el ranking de comisarías que define ascensos policiales.",
    ],
    [
      { medio: "INEI", nota: "Encuesta de victimización y percepción 2026." },
      { medio: "IDL-Seguridad Ciudadana", nota: "Análisis regional." },
    ],
    "17 sep 2026"),
  art("delincuencia-seguridad-ciudadana", 3,
    "Serenazgo municipal recibe facultades de arresto ciudadano regulado",
    "La ley precisa límites, capacitación y uso de cámaras obligatorias.",
    [
      "El Congreso aprobó la ley que regula el arresto ciudadano por parte del serenazgo municipal. Solo procede en flagrancia y con entrega inmediata a la PNP.",
      "La norma exige 200 horas de capacitación en derechos humanos y uso de cámaras corporales activas. Los municipios tendrán un año para adecuarse.",
      "La Defensoría saludó la regulación pero pidió fiscalización para evitar abusos. Anunció un registro público de intervenciones con uso de la fuerza.",
      "Gremios de serenos piden además seguro de vida y estabilidad laboral. El 70% trabaja bajo contratos temporales, según su federación.",
      "El serenazgo suma 18 000 efectivos en todo el país, casi la mitad sin chaleco antibalas. La nueva ley obliga a los municipios a equiparlos en un año.",
      "La capacitación incluirá defensa personal, primeros auxilios y mediación de conflictos. Las cámaras corporales almacenarán 90 días de grabación auditable.",
    ],
    [
      { medio: "Congreso de la República", nota: "Texto de la ley de serenazgo." },
      { medio: "Defensoría del Pueblo", nota: "Opinión técnica." },
    ],
    "15 sep 2026"),
  // ── 14 · Extorsión y Sicariato ──
  art("extorsion-sicariato", 1,
    "Estado de emergencia en Trujillo: 500 militares apoyan a la PNP",
    "El Ejecutivo prorrogó la medida por 60 días ante el cobro de cupos.",
    [
      "El Gobierno prorrogó por 60 días el estado de emergencia en Trujillo y Pataz. Quinientos militares apoyan a la PNP en el control de vías y operativos contra extorsionadores.",
      "La extorsión al transporte urbano y a comerciantes dejó 40 asesinatos este año en La Libertad. Los gremios exigían medidas desde hace meses con paros escalonados.",
      "La Fiscalía creó un equipo especial con 20 fiscales dedicados solo a extorsión y sicariato. Ya se dictaron 120 prisiones preventivas en flagrancia.",
      "Transportistas piden una central única de denuncias con reserva de identidad. El Mininter habilitó la línea 111 con atención prioritaria.",
      "El modus operandi combina llamadas, videos de ejecuciones y visitas a paraderos. El cupo promedio subió a 2 000 soles mensuales por empresa.",
      "Pataz aporta el contexto minero: la minería ilegal mueve 1 000 millones anuales en la zona. El oro informal financia armas y sicarios, según inteligencia policial.",
    ],
    [
      { medio: "Presidencia del Consejo de Ministros", nota: "Decreto de prórroga." },
      { medio: "Ministerio Público", nota: "Equipo especial contra la extorsión." },
    ],
    "18 sep 2026"),
  art("extorsion-sicariato", 2,
    "Cupos a bodegas: caen 15 cobradores de red que operaba en tres distritos",
    "La banda exigía hasta 500 soles semanales a pequeños negocios.",
    [
      "La PNP capturó a 15 integrantes de una red que cobraba cupos a bodegas en San Juan de Lurigancho, Ate y Santa Anita. Exigían entre 200 y 500 soles semanales por negocio.",
      "La investigación duró cuatro meses con agentes encubiertos y escuchas autorizadas. Se incautaron armas, motos y cuadernos con 800 comercios extorsionados.",
      "El Poder Judicial dictó prisión preventiva para los cabecillas por organización criminal. La Fiscalía pide penas de hasta 25 años.",
      "Bodegueros agradecieron el operativo pero temen represalias. La PNP instaló patrullaje permanente en las zonas liberadas.",
      "La red usaba menores como cobradores para eludir detenciones largas. La Fiscalía de Familia abrió 8 investigaciones por explotación de menores.",
      "Los cuadernos incautados revelan contabilidad de 400 000 soles mensuales. El lavado se hacía por bodegas fachada y apuestas deportivas.",
    ],
    [
      { medio: "PNP – Dirincri", nota: "Operativo contra cobro de cupos." },
      { medio: "Poder Judicial", nota: "Prisiones preventivas dictadas." },
    ],
    "16 sep 2026"),
  art("extorsion-sicariato", 3,
    "Congreso endurece penas por sicariato hasta cadena perpetua",
    "La reforma incluye a menores reclutados como sicarios con tratamiento diferenciado.",
    [
      "El Pleno aprobó endurecer las penas por sicariato hasta cadena perpetua cuando la víctima sea transportista, comerciante o autoridad. La reforma alcanzó 78 votos.",
      "El dictamen crea el delito de reclutamiento de menores para sicariato con penas de 25 años. Los adolescentes infractores irán a centros especializados con programas de reinserción.",
      "Penalistas advierten que el populismo punitivo no reduce el crimen sin investigación criminal sólida. Piden fortalecer la inteligencia policial y la protección de testigos.",
      "El Ejecutivo promulgará la ley en los próximos días. El Poder Judicial capacitará a 300 jueces en su aplicación.",
      "La cadena perpetua aplica cuando concurren alevosía y cobro, y tras revisión a los 35 años. El TC ya validó su constitucionalidad en fallos previos.",
      "El tratamiento diferenciado para menores incluye centros con educación y oficio. Solo el 12% de adolescentes infractores reincide tras esos programas.",
    ],
    [
      { medio: "Congreso de la República", nota: "Votación del Pleno." },
      { medio: "Ministerio de Justicia", nota: "Opinión sobre la reforma." },
    ],
    "15 sep 2026"),
  // ── 15 · Derechos y Justicia ──
  art("derechos-justicia", 1,
    "Poder Judicial digitaliza un millón de expedientes en Lima",
    "El expediente electrónico reduce a la mitad los tiempos de trámite.",
    [
      "El Poder Judicial culminó la digitalización de un millón de expedientes físicos en la Corte de Lima. Los procesos civiles ahora se tramitan íntegramente en el expediente electrónico.",
      "Los tiempos promedio de resolución bajaron de 18 a 9 meses en juzgados piloto. Las audiencias virtuales representan el 60% de las programadas.",
      "El plan incluye firma digital para todos los jueces y casillas electrónicas obligatorias para abogados. La inversión es de 120 millones de soles hasta 2027.",
      "La OCMA advierte que la celeridad no debe sacrificar garantías. Monitoreará los juzgados con mayor carga procesal.",
      "El expediente electrónico usa firma digital con certificados del Reniec y sellado de tiempo. Cada actuación queda registrada con hash inalterable.",
      "La mora judicial bajó de 2,1 a 1,4 millones de expedientes en tres años. Los juzgados de flagrancia resuelven el 80% en menos de 72 horas.",
    ],
    [
      { medio: "Poder Judicial", nota: "Plan de digitalización." },
      { medio: "OCMA", nota: "Supervisión de celeridad procesal." },
    ],
    "17 sep 2026"),
  art("derechos-justicia", 2,
    "Fiscalía crea fiscalías especializadas en ciberdelincuencia",
    "Doce despachos atenderán estafas digitales y explotación en línea.",
    [
      "El Ministerio Público creó doce fiscalías especializadas en ciberdelincuencia en Lima y regiones. Atenderán estafas digitales, suplantación y explotación sexual en línea.",
      "Cada despacho contará con peritos informáticos y convenios con plataformas para preservar evidencia. La meta es reducir de 2 años a 8 meses la investigación promedio.",
      "La ciberdelincuencia creció 45% en denuncias, superando las 30 000 anuales. Solo el 8% llega a sentencia por falta de trazabilidad digital.",
      "Organizaciones civiles piden protocolos de atención a víctimas de violencia digital. La Fiscalía anunció una guía con enfoque de género.",
      "Los peritos usan herramientas de análisis forense con cadena de custodia certificada. La evidencia en la nube se preserva con oficios a empresas en 24 horas.",
      "El grooming y la sextorsión a menores crecen 30% anual y concentran la carga. Cada fiscalía contará con psicólogos forenses para cámaras Gesell virtuales.",
    ],
    [
      { medio: "Ministerio Público", nota: "Creación de fiscalías especializadas." },
      { medio: "Divindat – PNP", nota: "Estadística de denuncias." },
    ],
    "16 sep 2026"),
  art("derechos-justicia", 3,
    "Corte IDH ordena al Perú reparar a víctimas de esterilizaciones",
    "El fallo fija compensaciones y un registro nacional de afectadas.",
    [
      "La Corte Interamericana ordenó al Estado reparar a víctimas de esterilizaciones forzadas de los noventa. El fallo dispone compensaciones económicas y atención integral de salud.",
      "El tribunal exige además un registro nacional único de afectadas y un acto público de reconocimiento. El plazo de cumplimiento es de dos años con supervisión.",
      "Organizaciones de mujeres celebraron la sentencia como histórica tras 25 años de litigio. Estiman más de 2 000 víctimas con secuelas.",
      "El Ministerio de Justicia anunció una comisión de cumplimiento con participación de las afectadas. El Congreso deberá adecuar el marco de reparaciones.",
      "Las reparaciones incluyen indemnización, seguro integral y becas para hijas e hijos. El monto base se calcula sobre 100 000 soles por víctima.",
      "El caso abarca esterilizaciones entre 1995 y 2000 bajo el programa de salud reproductiva. La CVR documentó cuotas y presiones a personal de salud.",
    ],
    [
      { medio: "Corte Interamericana de DD.HH.", nota: "Sentencia del caso." },
      { medio: "Ministerio de Justicia", nota: "Compromiso de cumplimiento." },
    ],
    "15 sep 2026"),
];

export const NOTICIAS_DEPORTE: Noticia[] = [
  // ── 16 · Fútbol Peruano ──
  art("futbol-peruano", 1,
    "Universitario y Alianza definen el Clausura en un final de infarto",
    "Ambos llegan igualados a la última fecha con 34 puntos.",
    [
      "La Liga 1 vivirá una definición histórica: Universitario y Alianza Lima llegan igualados con 34 puntos a la última fecha del Clausura. La diferencia de goles favorece a los cremas por dos tantos.",
      "Universitario visita a un Cienciano ya clasificado a la Sudamericana, mientras Alianza recibe a Sporting Cristal en Matute. Ambos partidos se jugarán en simultáneo el domingo a las 3:30 p.m.",
      "La Policía desplegará 3 000 efectivos ante la expectativa de estadios llenos. Solo se permitirá hinchada local en ambos escenarios.",
      "El campeón del Clausura enfrentará al ganador del Apertura en la final nacional. Melgar espera en semifinales como mejor acumulado.",
      "El formato del Descentralizado premia la regularidad: el acumulado define localías y descensos. Los dos últimos pierden la categoría directo a Liga 2.",
      "Las taquillas de la definición superarán los 8 millones de soles con estadios llenos. La final nacional se jugará a ida y vuelta en diciembre.",
    ],
    [
      { medio: "Liga de Fútbol Profesional", nota: "Programación de la última fecha." },
      { medio: "RPP Deportes", nota: "Previa de la definición." },
    ],
    "19 sep 2026"),
  art("futbol-peruano", 2,
    "Selección peruana inicia microciclos con 12 jugadores del medio local",
    "El técnico apuesta por renovar con Sub-23 para las Eliminatorias 2030.",
    [
      "La selección peruana inició sus microciclos con doce jugadores del torneo local, la mayoría Sub-23. El comando técnico busca renovar el plantel de cara a las Eliminatorias 2030.",
      "Destacan tres juveniles de Cristal, dos de Melgar y el goleador de la Copa Perú invitado como sparring. Los trabajos se realizan en la Videna durante tres días.",
      "La FPF confirmó amistosos ante Paraguay y Bolivia en octubre. Serán la primera prueba del recambio generacional tras la eliminación pasada.",
      "Hinchas exigen resultados inmediatos, pero el técnico pidió paciencia. La meta trazada es pelear el repechaje desde el inicio.",
      "El recambio incluye laterales de 20 años y un enganche zurdo de la reserva crema. El comando técnico evalúa 40 jugadores en cuatro microciclos.",
      "El repechaje 2030 enfrentará al séptimo de Conmebol contra un asiático. El formato ampliado del Mundial da 6,5 cupos a Sudamérica.",
    ],
    [
      { medio: "FPF", nota: "Convocatoria a microciclos." },
      { medio: "Diario Líbero", nota: "Análisis del recambio." },
    ],
    "17 sep 2026"),
  art("futbol-peruano", 3,
    "Copa Perú: finalistas de Puno y Cajamarca sueñan con la Liga 1",
    "El campeón ascenderá directo y el subcampeón jugará la Liga 2.",
    [
      "La Copa Perú tiene finalistas: Alfonso Ugarte de Puno y ADA de Cajamarca definirán el ascenso a la Liga 1. La final única se jugará en el Estadio Nacional.",
      "Ambos equipos eliminaron a favoritos con campañas invictas de visita. Ugarte apuesta por su altura como aliada, mientras ADA llega con la valla menos batida.",
      "El torneo movilizó a 2 millones de hinchas en todo el país y generó 30 millones de soles en economías locales. Es considerado el torneo más democrático del continente.",
      "La FPF confirmó premios de 500 000 soles al campeón y 250 000 al subcampeón. Además, ambos aseguran su participación en la Liga 2 del próximo año como mínimo.",
      "La Copa Perú moviliza 2 000 equipos distritales en su etapa inicial. Solo 50 llegan a la fase nacional tras ocho meses de competencia.",
      "El ascenso exige estadio con 5 000 butacas y planilla sin deudas. La FPF auditará a los finalistas antes de otorgar la licencia.",
    ],
    [
      { medio: "FPF – Copa Perú", nota: "Programación de la final." },
      { medio: "Diario El Comercio", nota: "Historias de los finalistas." },
    ],
    "15 sep 2026"),
  // ── 17 · Fútbol Extranjero ──
  art("futbol-extranjero", 1,
    "Champions: peruanos en el extranjero viven semana decisiva",
    "Tres compatriotas disputan la segunda fecha de la fase de grupos.",
    [
      "La Champions entra a su segunda fecha con tres peruanos en acción. El delantero del Feyenoord llega como goleador de su equipo, mientras el volante del Malmö busca titularidad.",
      "El duelo más atractivo será el del lateral peruano ante el campeón inglés en Anfield. La prensa europea destaca su velocidad como arma para el contragolpe.",
      "Los tres suman minutos crecientes respecto a la temporada pasada. Sus rendimientos alimentan la ilusión de la hinchada de cara a las Eliminatorias.",
      "Los partidos se transmiten en horario estelar para el Perú. Se espera récord de audiencia en plataformas de streaming.",
      "El delantero del Feyenoord suma 9 goles en 12 fechas de la Eredivisie. Su cláusula de rescisión ronda los 25 millones de euros.",
      "El nuevo formato Champions con 36 equipos y 8 jornadas premia la regularidad. Cada victoria en fase liga paga 2,1 millones de euros.",
    ],
    [
      { medio: "UEFA", nota: "Programación de la Champions." },
      { medio: "ESPN Perú", nota: "Seguimiento a peruanos." },
    ],
    "18 sep 2026"),
  art("futbol-extranjero", 2,
    "Libertadores: semifinales con sabor a revancha",
    "Dos brasileños y dos argentinos definen a los finalistas en Lima.",
    [
      "La Copa Libertadores definió semifinales explosivas: Palmeiras ante River Plate y Flamengo frente a Boca Juniors. La final única se jugará en el Estadio Monumental de Lima.",
      "Conmebol confirmó que Lima recibirá su segunda final en siete años. Se esperan 60 000 visitantes y un impacto económico de 80 millones de dólares.",
      "Las semifinales de ida dejaron empates con polémica arbitral y VAR protagonista. La vuelta promete estadios llenos en São Paulo y Buenos Aires.",
      "La seguridad será coordinada con la PNP y Migraciones. Ya se agotaron los paquetes turísticos oficiales en Brasil y Argentina.",
      "El Monumental recibirá 80 000 espectadores con gramado híbrido renovado. La Conmebol exige 60 palcos y centro de prensa para 1 500 periodistas.",
      "La final única mueve 120 millones de dólares en la ciudad sede. Lima ya organizó la de 2019 entre Flamengo y River con balance positivo.",
    ],
    [
      { medio: "Conmebol", nota: "Sedes y programación." },
      { medio: "Diario Olé", nota: "Previa de semifinales." },
    ],
    "16 sep 2026"),
  art("futbol-extranjero", 3,
    "Mundial 2026: FIFA libera 500 000 entradas para la fase final",
    "Peruanos en EE.UU. lideran la demanda latinoamericana de boletos.",
    [
      "La FIFA liberó 500 000 entradas adicionales para el Mundial 2026 de EE.UU., México y Canadá. La demanda superó los 20 millones de solicitudes en la primera fase.",
      "La colonia peruana en Estados Unidos figura entre las cinco que más boletos solicitó en Latinoamérica. Agencias de viaje ofrecen paquetes desde 4 000 dólares.",
      "El torneo estrenará formato de 48 selecciones y 104 partidos. La final se jugará en el MetLife de Nueva Jersey.",
      "Indecopi advirtió sobre reventas fraudulentas y pidió comprar solo en canales oficiales. La Cancillería reforzará consulados durante el torneo.",
      "Las entradas van de 60 dólares en fase de grupos a 6 000 en la final. La FIFA usa precios dinámicos con verificación de identidad.",
      "Se esperan 5 millones de visitantes en 16 ciudades sede. El impacto económico proyectado supera los 25 000 millones de dólares.",
    ],
    [
      { medio: "FIFA", nota: "Venta de entradas Mundial 2026." },
      { medio: "Cancillería del Perú", nota: "Asistencia a hinchas." },
    ],
    "15 sep 2026"),
];
