import { art, type Noticia } from "./tipos";

/** Economía y producción · 5 categorías × 3 noticias. */
export const NOTICIAS_ECONOMIA: Noticia[] = [
  // ── 1 · Industria ──
  art("industria", 1,
    "Parques industriales de Lima norte superan el 90% de ocupación",
    "La demanda de lotes logísticos e industriales creció 18% en el último año por el efecto del puerto de Chancay.",
    [
      "Los parques industriales ubicados entre Puente Piedra y Ancón reportan una ocupación superior al 90%, el nivel más alto de la última década. Operadores del sector señalan que la cercanía al puerto de Chancay aceleró la demanda de almacenes y plantas de ensamblaje.",
      "El precio promedio del metro cuadrado en preventa subió de 95 a 120 dólares en doce meses. La escasez de suelo habilitado con zonificación industrial empuja a las empresas hacia Lurín y Chilca, donde aún hay disponibilidad.",
      "La Sociedad Nacional de Industrias pidió al Ejecutivo acelerar los trámites de habilitación urbana y la conexión de agua y energía. Estiman que cada 100 hectáreas habilitadas generan alrededor de 8 000 empleos directos.",
      "Para el próximo año se anuncian tres nuevos condominios industriales en el sur chico con una inversión conjunta de 240 millones de dólares. Los gremios proyectan que la manufactura crecerá 4,2% si se mantiene el ritmo de ocupación.",
      "El efecto Chancay también eleva la vara técnica: los nuevos parques exigen subestaciones propias, vías de 12 metros y patios de maniobra para bitrenes. Consultoras logísticas estiman que la renta de almacenes clase A subirá otro 10% antes de cerrar el año.",
      "En paralelo, el Ministerio de Vivienda evalúa un banco de tierras industriales con 2 000 hectáreas entre Lima y Callao. La propuesta incluye fideicomisos para agua y desagüe, el reclamo más repetido por los desarrolladores.",
    ],
    [
      { medio: "Sociedad Nacional de Industrias", nota: "Reporte de ocupación industrial, setiembre 2026." },
      { medio: "Agencia Andina", nota: "Cobertura de anuncios de inversión en parques industriales." },
    ],
    "19 sep 2026"),
  art("industria", 2,
    "Minería aporta el 58% de las exportaciones y acelera proyectos de cobre",
    "El Minem confirmó que cuatro proyectos cupríferos entrarán en construcción entre 2026 y 2027.",
    [
      "Las exportaciones mineras alcanzaron los 31 000 millones de dólares entre enero y agosto, con el cobre como protagonista. El Ministerio de Energía y Minas destacó que el Perú se mantiene como segundo productor mundial del metal rojo.",
      "Cuatro proyectos —entre ampliaciones y minas nuevas— iniciarán construcción en los próximos dieciocho meses. La inversión comprometida supera los 7 000 millones de dólares y generará 25 000 empleos en etapa de obra.",
      "Las comunidades del corredor minero del sur exigen que los convenios marco incluyan obras de agua y salud antes del inicio de operaciones. El Ejecutivo anunció mesas de diálogo con cronograma de 90 días.",
      "Analistas advierten que la conflictividad social sigue siendo el principal riesgo para la cartera. Recomiendan adelantar la inversión social y transparentar los aportes por canon en cada región.",
      "El precio del cobre, sobre los 4,6 dólares por libra, sostiene la rentabilidad de los proyectos en cartera. Cada diez centavos adicionales aportan unos 600 millones de dólares anuales a las exportaciones, según cálculos del BCRP.",
      "En refinación, el debate pendiente es fundir más cobre en casa: hoy el Perú exporta casi todo su concentrado. El Minem evalúa incentivos para una refinería en el sur que agregue valor y empleo calificado.",
    ],
    [
      { medio: "Ministerio de Energía y Minas", nota: "Boletín estadístico minero, agosto 2026." },
      { medio: "Diario Gestión", nota: "Entrevista a viceministro sobre cartera de proyectos." },
    ],
    "18 sep 2026"),
  art("industria", 3,
    "Manufactura no primaria crece por tercer trimestre consecutivo",
    "Bienes de consumo y confecciones lideran la recuperación fabril, según el Produce.",
    [
      "La manufactura no primaria creció 3,8% en el segundo trimestre, encadenando tres trimestres en positivo. El Ministerio de la Producción atribuyó el avance a la demanda interna y a la recuperación de las exportaciones de confecciones.",
      "El subsector de alimentos y bebidas aportó casi la mitad del crecimiento, seguido por plásticos y metalmecánica. Las mypes manufactureras aumentaron sus pedidos por la campaña de fin de año.",
      "El principal cuello de botella sigue siendo el costo logístico: trasladar un contenedor del Callao a Huachipa cuesta hasta 40% más que hace tres años. Los gremios piden intervenir en los peajes y en la congestión portuaria.",
      "El Produce lanzó una línea de cofinanciamiento para maquinaria con tasas preferenciales. La meta es formalizar 5 000 talleres y elevar la productividad del sector en dos dígitos al 2027.",
      "Las confecciones merecen capítulo aparte: las exportaciones a EE.UU. crecieron 14% por la demanda de algodón pima y prendas de alto valor. Gamarra reporta su mejor campaña en cinco años con pedidos anticipados de invierno.",
      "A futuro, el sector pide una política de clusters con centros de innovación textil y metalmecánico. Chile y Colombia ya operan ese modelo y captan parte de la inversión que antes miraba al Perú.",
    ],
    [
      { medio: "Ministerio de la Producción", nota: "Índice de producción manufacturera, julio 2026." },
      { medio: "RPP Economía", nota: "Análisis de costos logísticos con gremios." },
    ],
    "17 sep 2026"),
  // ── 2 · Economía y Finanzas ──
  art("economia-finanzas", 1,
    "BCRP mantiene la tasa en 4,25% y prevé inflación dentro del rango meta",
    "El directorio destacó que las expectativas inflacionarias siguen ancladas pese al ruido externo.",
    [
      "El Banco Central de Reserva mantuvo su tasa de referencia en 4,25% por tercer mes consecutivo. El comunicado señala que la inflación interanual se ubica en 2,4%, dentro del rango meta de 1% a 3%.",
      "El ente emisor proyecta un crecimiento del PBI de 3,1% para este año, impulsado por la minería y la agroexportación. Advirtió, sin embargo, que la volatilidad internacional del dólar exige cautela monetaria.",
      "El tipo de cambio cerró la semana en 3,72 soles por dólar, con intervenciones menores del BCRP. Los analistas prevén estabilidad cambiaria si la Reserva Federal de EE.UU. inicia su ciclo de recortes.",
      "Para los hogares, la medida implica que las tasas de créditos hipotecarios y vehiculares se mantendrán estables en el corto plazo. El banco recomendó a las familias evitar el sobreendeudamiento en dólares.",
      "El comunicado detalla que los indicadores adelantados de actividad —electricidad, cemento y confianza empresarial— apuntan a un tercer trimestre sólido. La inversión minera y la pesca industrial sostienen el impulso.",
      "La próxima reunión de política monetaria será en octubre con nuevo reporte de inflación. El mercado asigna 70% de probabilidad a que la tasa cierre el año sin cambios, salvo un shock externo.",
    ],
    [
      { medio: "BCRP", nota: "Comunicado de política monetaria, setiembre 2026." },
      { medio: "Diario El Comercio", nota: "Cobertura de la decisión del directorio." },
    ],
    "19 sep 2026"),
  art("economia-finanzas", 2,
    "MEF eleva a 3,4% la proyección del PBI por Chancay y agroexportación",
    "El Marco Macroeconómico Multianual incorpora el impacto logístico del megapuerto.",
    [
      "El Ministerio de Economía y Finanzas revisó al alza su proyección de crecimiento a 3,4% para el próximo año. El titular del sector explicó que el puerto de Chancay reducirá costos logísticos y atraerá manufactura.",
      "La inversión privada crecería 5,1% impulsada por minería e infraestructura, mientras la pública avanzaría 4%. El déficit fiscal se mantendría en 2,2% del PBI, dentro de la regla fiscal.",
      "Economistas independientes consideran la meta alcanzable pero condicionada a la estabilidad política. Recuerdan que cada punto de conflicto social prolongado resta hasta 0,3 puntos al crecimiento.",
      "El MEF anunció además un paquete de simplificación tributaria para mypes y la digitalización total de trámites aduaneros. Ambas medidas regirían desde el primer trimestre del próximo año.",
      "En ingresos fiscales, la recaudación minera por regalías y canon sumaría 9 000 millones de soles este año. El MEF destinará un fondo de estabilización para proteger la inversión pública si caen los precios.",
      "El Consejo Fiscal autónomo avaló las cifras pero pidió sincerar los supuestos de inversión privada. Su informe advierte que dos años seguidos de sobreestimación erosionan la credibilidad de la regla fiscal.",
    ],
    [
      { medio: "MEF", nota: "Marco Macroeconómico Multianual 2026-2029." },
      { medio: "Semana Económica", nota: "Reacciones de analistas a la proyección." },
    ],
    "18 sep 2026"),
  art("economia-finanzas", 3,
    "Empleo formal privado suma 210 000 puestos nuevos en doce meses",
    "Servicios y construcción explican dos de cada tres empleos creados, según el MTPE.",
    [
      "El empleo formal privado creció 4,6% interanual y sumó 210 000 nuevos puestos de trabajo. El Ministerio de Trabajo destacó que el avance se concentró en Lima, Arequipa y La Libertad.",
      "Los sectores servicios y construcción explican el 68% de los nuevos empleos, seguidos por comercio. La remuneración promedio real subió 2,1%, recuperando parte del poder adquisitivo perdido.",
      "Pese al avance, la informalidad laboral sigue en 71% a nivel nacional y supera el 85% en regiones andinas. Especialistas piden incentivos a la contratación juvenil y menor costo no salarial.",
      "El Ejecutivo enviará al Congreso una reforma de la ley de promoción del empleo formal con créditos tributarios por cada trabajador nuevo. Los gremios empresariales saludaron la iniciativa pero piden gradualidad.",
      "Lima concentra el 55% de los nuevos puestos, pero el interior acelera: Arequipa creció 7% por minería y servicios, y La Libertad 6% por agroindustria. Las mujeres explican el 48% de las contrataciones netas.",
      "El desempleo juvenil, en 11%, duplica el promedio nacional y sigue como tarea pendiente. El programa de primer empleo con subsidio parcial al salario se ampliará a 100 000 beneficiarios.",
    ],
    [
      { medio: "MTPE", nota: "Boletín de empleo formal, agosto 2026." },
      { medio: "INEI", nota: "Informe técnico de empleo e ingresos." },
    ],
    "16 sep 2026"),
  // ── 3 · Energía ──
  art("energia", 1,
    "Camisea garantiza gas hasta 2040 y alista ampliación del ducto al sur",
    "El nuevo contrato de suministro prioriza la demanda residencial e industrial del sur andino.",
    [
      "El consorcio Camisea confirmó reservas probadas que garantizan el abastecimiento de gas natural hasta 2040. El anuncio incluye la ampliación del ducto hacia Cusco, Puno y Arequipa con 1 200 millones de dólares de inversión.",
      "Más de 2,1 millones de hogares ya usan gas natural y la meta es llegar a 3 millones en 2028. El ahorro frente al balón de GLP supera los 25 soles mensuales por familia, según Osinergmin.",
      "La masificación en el sur contempla 180 000 nuevas conexiones y dos plantas satélite de regasificación. Las obras empezarían en el segundo semestre del próximo año.",
      "Expertos energéticos piden que parte de la renta se destine a un fondo de transición hacia renovables. El Ejecutivo evalúa incluir esa cláusula en la adenda del contrato.",
      "El lote 88, corazón de Camisea, opera con factor de recuperación superior al 70% gracias a la reinyección. Perupetro destaca que es uno de los yacimientos más eficientes de la región.",
      "La petroquímica sigue siendo la asignatura pendiente: el etano disponible podría alimentar un polo en el sur. ProInversión prepara la subasta de un complejo de fertilizantes para 2027.",
    ],
    [
      { medio: "Perupetro", nota: "Reporte de reservas y producción, 2026." },
      { medio: "Osinergmin", nota: "Cifras de masificación de gas natural." },
    ],
    "19 sep 2026"),
  art("energia", 2,
    "Solares y eólicas cubrirán el 12% de la matriz eléctrica en 2027",
    "Seis centrales renovables entrarán en operación en Arequipa, Moquegua e Ica.",
    [
      "La participación de la energía solar y eólica en la matriz eléctrica llegará al 12% el próximo año. El COES informó que seis centrales con 900 megavatios conjuntos entrarán en operación comercial.",
      "La inversión en estos proyectos supera los 1 100 millones de dólares, mayoritariamente capital extranjero. Las tarifas adjudicadas en subasta figuran entre las más bajas de la región.",
      "El reto pendiente es la transmisión: dos líneas de 500 kV deben terminarse para evacuar la energía del sur. El Minem declaró de interés nacional su culminación antes de fines de 2027.",
      "Gremios industriales celebran la diversificación porque reduce la exposición a sequías que afectan a las hidroeléctricas. Piden, además, reglas claras para el almacenamiento con baterías.",
      "El potencial solar del desierto costero figura entre los mejores del mundo, con irradiación 40% superior al promedio global. Moquegua y Arequipa concentran el 70% de los proyectos en cola.",
      "En eólica, Talara y la costa piurana ofrecen vientos de 9 metros por segundo. Dos parques en construcción sumarán 500 megavatios y contratos de 20 años con mineras.",
    ],
    [
      { medio: "COES", nota: "Plan de operación y entrada de centrales 2026-2027." },
      { medio: "Ministerio de Energía y Minas", nota: "Balance de la matriz eléctrica." },
    ],
    "17 sep 2026"),
  art("energia", 3,
    "Osinergmin congela tarifas eléctricas residenciales hasta fin de año",
    "La medida beneficia a 8 millones de usuarios regulados en todo el país.",
    [
      "El regulador Osinergmin dispuso el congelamiento de las tarifas eléctricas residenciales hasta diciembre. La decisión responde a la caída del costo marginal de generación por la mayor hidrología.",
      "Un hogar que consume 150 kWh al mes seguirá pagando alrededor de 118 soles. El FOSE continuará subsidiando a los usuarios de menores consumos en zonas rurales y urbano-marginales.",
      "Las distribuidoras advirtieron que el congelamiento no debe extenderse más allá del año para no afectar inversiones en redes. El regulador aseguró que revisará los costos en enero.",
      "Asociaciones de consumidores pidieron extender el beneficio a las mypes con tarifa BT5B. Osinergmin evaluará el pedido en la próxima fijación tarifaria.",
      "El pliego tarifario incluye cargos por transmisión y distribución que pesan 45% del recibo. La modernización de redes inteligentes permitiría recortes futuros, según el regulador.",
      "En comparación regional, la tarifa peruana sigue entre las más bajas de Sudamérica para consumos medios. Chile y Brasil cobran hasta 60% más por el mismo bloque horario.",
    ],
    [
      { medio: "Osinergmin", nota: "Resolución de fijación tarifaria, setiembre 2026." },
      { medio: "Agencia Andina", nota: "Alcances del congelamiento tarifario." },
    ],
    "15 sep 2026"),
  // ── 4 · Agricultura y Alimentación ──
  art("agricultura-alimentacion", 1,
    "Arándano peruano rompe récord: 320 000 toneladas exportadas",
    "El Perú consolida su liderazgo mundial con envíos a 32 mercados.",
    [
      "Las exportaciones de arándanos alcanzaron 320 000 toneladas en la campaña, un récord histórico. El Perú mantiene el primer lugar mundial, por encima de Chile y España, con EE.UU. y Europa como destinos principales.",
      "La Libertad y Lambayeque concentran el 78% de la producción, con rendimientos de hasta 18 toneladas por hectárea. La genética varietal y el riego tecnificado explican el salto productivo.",
      "El Midagri advirtió sobre la caída de precios internacionales por sobreoferta y recomendó diversificar hacia Asia. Ya se negocia el acceso fitosanitario a Indonesia y Vietnam.",
      "Pequeños productores piden asociatividad para no quedar fuera de la cadena de frío. Sierra Exportadora impulsa 40 cooperativas con asistencia técnica y financiamiento.",
      "El arándano requiere 1 200 horas de frío y suelos ácidos, condiciones que la costa norte ofrece casi todo el año. Esa ventaja climática permite dos cosechas y ventanas contraestación con EE.UU.",
      "El Senasa certificó 15 nuevas plantas empacadoras con tratamiento hidrotérmico. La meta es despachar fruta 48 horas después de cosechada para preservar la firmeza que premian los compradores.",
    ],
    [
      { medio: "Midagri", nota: "Boletín de comercio exterior agrario." },
      { medio: "ADEX", nota: "Balance de la campaña de arándanos." },
    ],
    "18 sep 2026"),
  art("agricultura-alimentacion", 2,
    "Café de especialidad duplica su precio en chacra por heladas en Brasil",
    "Productores de Junín y Cajamarca reciben hasta 1 200 soles por quintal.",
    [
      "El precio del café en chacra se duplicó hasta 1 200 soles por quintal tras las heladas en Brasil. Los productores de especialidad de la selva central son los más beneficiados por la coyuntura.",
      "La Junta Nacional del Café estima que las exportaciones del grano sumarán 1 100 millones de dólares este año. El 60% corresponde ya a cafés certificados y de especialidad.",
      "El desafío es la roya amarilla, que afecta al 15% de las plantaciones. El INIA distribuye 2 millones de plantones resistentes en cinco regiones cafetaleras.",
      "Tostadurías locales piden mayor oferta nacional para no importar café soluble. El Midagri evalúa una norma de mezcla mínima de café peruano en la industria.",
      "El café peruano crece entre 800 y 1 800 metros en sistemas agroforestales que conservan bosque. Esa producción bajo sombra obtiene primas de hasta 30% en mercados de especialidad.",
      "La trazabilidad es el siguiente salto: un piloto con QR en 5 000 sacos permite rastrear la finca de origen. Compradores europeos ya exigen ese estándar contra la deforestación.",
    ],
    [
      { medio: "Junta Nacional del Café", nota: "Reporte de precios en chacra." },
      { medio: "Midagri", nota: "Plan de renovación de cafetales." },
    ],
    "16 sep 2026"),
  art("agricultura-alimentacion", 3,
    "Majes Siguas II destraba 38 500 hectáreas para agroexportación",
    "El arbitraje favorable permite retomar las obras de la represa Angostura.",
    [
      "El proyecto Majes Siguas II retomó su cronograma tras resolverse el arbitraje a favor del Estado. La represa Angostura y el canal de derivación habilitarán 38 500 hectáreas nuevas en Arequipa.",
      "La inversión total supera los 650 millones de dólares bajo el esquema gobierno a gobierno. Se estima una agroexportación adicional de 1 400 millones anuales cuando opere a plena capacidad.",
      "El Gobierno Regional de Arequipa subastará las tierras con prioridad para medianos productores asociados. El 20% del área se reservará a agricultura familiar con riego presurizado.",
      "Colegios de ingenieros piden supervisión técnica independiente en la presa de 100 metros de altura. El Minem aseguró que el expediente incluye instrumentación sísmica completa.",
      "Angostura almacenará 1 140 millones de metros cúbicos y regulará el río Apurímac en época seca. El diseño contempla aliviadero para avenidas milenarias y galerías de inspección.",
      "El esquema gobierno a gobierno con contraparte técnica extranjera busca blindar el cronograma. La Contraloría realizará control concurrente con hitos de pago atados a avance físico.",
    ],
    [
      { medio: "Gobierno Regional de Arequipa", nota: "Cronograma de Majes Siguas II." },
      { medio: "Agencia Andina", nota: "Laudo arbitral y reinicio de obras." },
    ],
    "15 sep 2026"),
  // ── 5 · Emprendimiento y Startups ──
  art("emprendimiento-startups", 1,
    "Startups peruanas levantan 180 millones de dólares en lo que va del año",
    "Fintech y logtech concentran el 70% de la inversión de riesgo.",
    [
      "Las startups peruanas captaron 180 millones de dólares en capital de riesgo, superando todo lo levantado el año pasado. Fintech y logtech concentran siete de cada diez dólares invertidos.",
      "Tres rondas Serie A —dos de pagos digitales y una de logística— explican la mitad del monto. Fondos regionales como Kaszek y ALLVP lideraron las operaciones junto a ángeles locales.",
      "El ecosistema suma ya 1 100 startups activas y emplea a 18 000 personas. Lima concentra el 85%, aunque Arequipa y Trujillo empiezan a formar sus propios hubs.",
      "Emprendedores piden una ley de startups con sandbox regulatorio y stock options. Produce anunció una mesa técnica para presentar el proyecto al Congreso este trimestre.",
      "El ticket promedio de las rondas semilla subió a 1,2 millones de dólares, el doble que hace tres años. Los fondos de corporate venture de bancos y retailers explican parte del salto.",
      "En talento, los salarios de desarrolladores senior se acercan a niveles regionales y frenan la fuga. Platzi, Laboratoria y bootcamps locales gradúan 8 000 programadores al año.",
    ],
    [
      { medio: "Asociación Peruana de Capital Semilla", nota: "Reporte de inversión 2026." },
      { medio: "Diario Gestión", nota: "Cobertura de rondas Serie A." },
    ],
    "17 sep 2026"),
  art("emprendimiento-startups", 2,
    "E-commerce crece 22% y las mypes digitales ya son 400 000",
    "El ticket promedio subió a 180 soles por la confianza en pagos digitales.",
    [
      "El comercio electrónico peruano creció 22% y moverá 9 000 millones de dólares este año. Las mypes con canal digital suman 400 000, el doble que antes de la pandemia.",
      "El pago con billeteras digitales representa ya el 45% de las transacciones online. Yape y Plin lideran, seguidas por tarjetas y el pago contra entrega en provincias.",
      "La logística de última milla es el principal dolor: los envíos a regiones demoran hasta 5 días. Operadores anuncian hubs en Huancayo, Cusco y Piura para reducir tiempos.",
      "Indecopi reforzó la fiscalización de publicidad engañosa y devoluciones. Las tiendas con Libro de Reclamaciones virtual resuelven 30% más rápido, según el regulador.",
      "El live shopping y el social commerce crecen 40% anual impulsados por TikTok e Instagram. Influencers regionales venden artesanía y moda con conversión triple a la publicidad tradicional.",
      "La ciberseguridad es el nuevo frente: los fraudes con QR falsos subieron 60%. La cámara del sector impulsa un sello de tienda confiable con verificación de identidad.",
    ],
    [
      { medio: "Cámara Peruana de Comercio Electrónico", nota: "Estudio de e-commerce 2026." },
      { medio: "Indecopi", nota: "Balance de fiscalización digital." },
    ],
    "16 sep 2026"),
  art("emprendimiento-startups", 3,
    "Formalización: 60 000 mypes se acogieron al nuevo RUS simplificado",
    "El régimen permite emitir factura electrónica sin costo el primer año.",
    [
      "Sesenta mil mypes se acogieron al nuevo Régimen Único Simplificado en sus primeros seis meses. El esquema permite emitir facturas electrónicas gratuitas y pagar una cuota fija según ingresos.",
      "La Sunat reporta que el 40% de los acogidos son negocios que operaban en la informalidad. Bodegas, peluquerías y talleres mecánicos lideran las inscripciones.",
      "El MEF evalúa ampliar el tope de ingresos para incluir a restaurantes y pequeños hospedajes. Los contadores piden además interoperabilidad total con las billeteras digitales.",
      "Gremios mype saludan el avance pero exigen compras estatales: solo el 8% de las adquisiciones públicas va a microempresas. Perú Compras prometió una cuota del 15% para 2027.",
      "El monotributo propuesto unificaría impuestos y EsSalud en un pago único desde 60 soles. El MEF calcula que formalizaría a 300 000 negocios adicionales en tres años.",
      "La banca de desarrollo colocó 1 800 millones en garantías a mypes este año. Con el fondo Crecer, las tasas para microempresas bajaron de 40% a 28% en promedio.",
    ],
    [
      { medio: "Sunat", nota: "Balance del nuevo RUS, setiembre 2026." },
      { medio: "Ministerio de la Producción", nota: "Estrategia de formalización mype." },
    ],
    "15 sep 2026"),
];
