import { art, type Noticia } from "./tipos";

/** Mundo y sociedad · 8 categorías × 3 noticias. */
export const NOTICIAS_MUNDO: Noticia[] = [
  // ── 18 · Geopolítica Global ──
  art("geopolitica-global", 1,
    "ONU cumbre climática acuerda fondo de 300 000 millones para adaptación",
    "El Perú presidirá el comité de seguimiento de glaciares tropicales.",
    [
      "La cumbre climática de la ONU cerró con un fondo de 300 000 millones de dólares para adaptación en países vulnerables. El Perú fue elegido para presidir el comité de glaciares tropicales.",
      "El acuerdo incluye metas de reducción de metano y financiamiento para ciudades costeras frente a la subida del mar. Entrará en vigor en 2027 con aportes verificables.",
      "La delegación peruana logró incluir la Amazonía como prioridad de financiamiento. Se esperan 400 millones anuales para conservación y bioeconomía.",
      "ONG ambientales consideran el fondo insuficiente frente a los daños. Exigen que los desembolsos lleguen directo a comunidades y no solo a gobiernos.",
      "El mecanismo de pérdidas y daños operará con ventanilla directa para pueblos indígenas. Se acreditarán 50 entidades implementadoras regionales.",
      "El Perú presentará su inventario de glaciares como línea base del comité. El Inaigem aportará series satelitales de seis décadas.",
    ],
    [
      { medio: "ONU – Cambio Climático", nota: "Declaración final de la cumbre." },
      { medio: "Cancillería del Perú", nota: "Balance de la delegación." },
    ],
    "19 sep 2026"),
  art("geopolitica-global", 2,
    "Corredor bioceánico Brasil–Perú entra a fase de estudios definitivos",
    "La ruta unirá el Atlántico con Chancay y reducirá 20 días el flete a Asia.",
    [
      "El corredor ferroviario bioceánico entre Brasil y el puerto de Chancay entró a su fase de estudios definitivos. La ruta conectará el Atlántico con el Pacífico en 4 500 kilómetros.",
      "El proyecto, valorizado en 12 000 millones de dólares, reducirá de 45 a 25 días el flete de granos brasileños hacia Asia. El Perú captaría servicios logísticos y de valor agregado.",
      "Ambos gobiernos firmaron un memorando con cronograma de tres años para el expediente técnico. El financiamiento combinará banca multilateral y concesiones.",
      "Expertos piden trazar la ruta evitando áreas protegidas de la Amazonía. El Senace supervisará el estudio de impacto ambiental desde el inicio.",
      "El tramo peruano iría de Pucallpa a Chancay con 1 200 kilómetros de vía nueva. Requiere 40 túneles para cruzar la cordillera central.",
      "Brasil exporta 120 millones de toneladas de soya al año por el Atlántico. Cada día ahorrado equivale a 15 dólares menos por tonelada de flete.",
    ],
    [
      { medio: "MTC", nota: "Memorando del corredor bioceánico." },
      { medio: "CAF – Banco de Desarrollo", nota: "Estudios de prefactibilidad." },
    ],
    "17 sep 2026"),
  art("geopolitica-global", 3,
    "OTAN y potencias asiáticas acuerdan pacto de minerales críticos",
    "Litio, cobre y tierras raras tendrán cadena de suministro certificada.",
    [
      "Las potencias occidentales y asiáticas firmaron un pacto de minerales críticos para asegurar litio, cobre y tierras raras. El acuerdo crea una cadena certificada libre de trabajo forzoso.",
      "El Perú, segundo productor mundial de cobre, fue invitado como socio estratégico. Podría acceder a financiamiento para refinerías y valor agregado local.",
      "El pacto incluye un fondo de 5 000 millones para minas responsables en países en desarrollo. Las certificaciones ambientales serán requisito de compra.",
      "Analistas ven una oportunidad histórica si el país industrializa parte de su cobre. Advierten, eso sí, contra ceder soberanía regulatoria en la negociación.",
      "El cobre refinado vale 25% más que el concentrado y genera cinco empleos por cada uno en mina. Chile refina el 40%; el Perú, menos del 15%.",
      "Las tierras raras aparecen como subproducto en operaciones de la sierra central. Ingemmet mapea 12 ocurrencias con potencial económico.",
    ],
    [
      { medio: "Agencia Andina", nota: "Cobertura de la cumbre." },
      { medio: "Ministerio de Energía y Minas", nota: "Posición peruana." },
    ],
    "15 sep 2026"),
  // ── 19 · Geopolítica Regional ──
  art("geopolitica-regional-latam", 1,
    "Alianza del Pacífico elimina aranceles al 100% del comercio intrarregional",
    "Perú, Chile, Colombia y México profundizan su integración.",
    [
      "La Alianza del Pacífico acordó arancel cero para el 100% del comercio entre sus cuatro miembros. El protocolo regirá desde enero e incluye reglas de origen simplificadas.",
      "El bloque suma 230 millones de consumidores y es la octava economía del mundo. Las pymes exportadoras serán las principales beneficiadas con ventanillas únicas.",
      "Los presidentes anunciaron además un fondo de infraestructura digital y roaming sin costo. La próxima cumbre será en Lima a mediados del próximo año.",
      "Empresarios peruanos piden aprovechar el acuerdo para vender servicios y franquicias. Adex proyecta 2 000 millones adicionales en exportaciones no tradicionales.",
      "La acumulación de origen permitirá insumos de los cuatro países en un mismo producto. Textiles peruanos con botones colombianos ganan preferencia automática.",
      "El comercio intra Alianza apenas llega al 4% del total de sus miembros. La meta es duplicarlo en cinco años con cabotaje marítimo integrado.",
    ],
    [
      { medio: "Cancillería del Perú", nota: "Declaración de la cumbre." },
      { medio: "ADEX", nota: "Proyecciones de comercio." },
    ],
    "18 sep 2026"),
  art("geopolitica-regional-latam", 2,
    "CAN lanza pasaporte andino digital para sus cuatro países",
    "El documento facilitará el tránsito de 110 millones de ciudadanos.",
    [
      "La Comunidad Andina lanzó el pasaporte andino digital para Perú, Colombia, Ecuador y Bolivia. El documento con QR biométrico agilizará los controles fronterizos.",
      "Migraciones del Perú emitirá los primeros 500 000 pasaportes digitales este año. El trámite costará lo mismo y durará diez años para adultos.",
      "El sistema compartirá alertas de seguridad entre los cuatro países en tiempo real. Interpol Andina coordinará la base de datos.",
      "Viajeros frecuentes celebran la medida, que reduce colas en aeropuertos. La CAN evalúa extender el esquema a visas de trabajo temporales.",
      "El chip biométrico sigue el estándar OACI 9303 con foto y huellas cifradas. La lectura tarda 8 segundos frente a 2 minutos del control manual.",
      "El flujo entre países andinos supera 4 millones de viajes anuales. El turismo fronterizo genera 1 500 millones de dólares en la subregión.",
    ],
    [
      { medio: "Comunidad Andina", nota: "Resolución del pasaporte digital." },
      { medio: "Migraciones Perú", nota: "Cronograma de emisión." },
    ],
    "16 sep 2026"),
  art("geopolitica-regional-latam", 3,
    "Elecciones vecinas: observadores peruanos participarán en tres procesos",
    "La OEA y la UE invitaron a misiones con expertos del JNE y la ONPE.",
    [
      "Observadores electorales peruanos participarán en tres procesos vecinos este semestre. Las misiones de la OEA y la UE incluyen a expertos del JNE y la ONPE.",
      "Los comicios se realizarán en medio de tensiones por migraciones y disputas comerciales. La observación peruana aportará experiencia en voto electrónico y fiscalización.",
      "La Cancillería destacó que la participación refuerza el liderazgo democrático del país. Los informes se publicarán con recomendaciones técnicas.",
      "Analistas señalan que la estabilidad regional impacta directamente en el comercio fronterizo. Piden al Perú una diplomacia activa y principista.",
      "El comercio con Ecuador y Bolivia suma 2 800 millones anuales, 80% por pasos terrestres. Cada cierre fronterizo cuesta 8 millones diarios.",
      "Las misiones peruanas incluyen software de escrutinio donado por la ONPE. Ya se usó en dos elecciones vecinas con auditoría exitosa.",
    ],
    [
      { medio: "Cancillería del Perú", nota: "Designación de observadores." },
      { medio: "OEA", nota: "Misiones de observación." },
    ],
    "15 sep 2026"),
  // ── 20 · Cristianas / Devocional ──
  art("noticias-cristianas-devocional", 1,
    "Devocional del día: la fe que mueve montañas",
    "Versículo: Marcos 11:23 — Cree sin dudar y verás la gloria de Dios.",
    [
      "«Les aseguro que si alguien dice a este monte: Quítate y arrójate al mar, y no duda en su corazón, sino que cree que sucederá lo que dice, lo obtendrá» (Marcos 11:23). La fe genuina une la palabra con la confianza plena.",
      "Jesús enseñó este principio frente a la higuera seca: la oración eficaz nace de un corazón perdonador. Antes de pedir, el Señor nos invita a soltar toda ofensa y rencor.",
      "En la vida diaria, las montañas son las deudas, la enfermedad o la familia dividida. Declarar la Palabra cada mañana reprograma nuestra mente hacia la victoria.",
      "Oremos hoy: Señor, aumenta mi fe, enséñame a perdonar y a declarar tus promesas sin dudar. Amén. Comparte este devocional con alguien que necesite esperanza.",
      "El contexto de Marcos 11 es la entrada triunfal y la purificación del templo. Jesús vincula la fe con la autoridad sobre toda circunstancia.",
      "Memorizar un versículo semanal fortalece la vida devocional, según pastores consultados. Recomiendan orar en voz alta cada mañana antes de revisar el celular.",
    ],
    [
      { medio: "Redacción Noticias Cristianas", nota: "Devocional diario verificado con texto bíblico Reina Valera." },
    ],
    "20 sep 2026",
    "Ministerio Devocional"),
  art("noticias-cristianas-devocional", 2,
    "Marcha por Jesús reúne a 200 000 fieles en Lima",
    "Evangélicos y católicos marcharon juntos por la familia y la paz.",
    [
      "Más de 200 000 fieles participaron en la Marcha por Jesús que recorrió la avenida Brasil. Evangélicos y católicos marcharon unidos por la familia, la vida y la paz del país.",
      "La movilización, de carácter pacífico y festivo, incluyó carrozas, bandas y oración por las autoridades. El tránsito se restableció sin incidentes al mediodía.",
      "Los organizadores entregaron un memorial al Gobierno con propuestas sobre valores en la educación. Pidieron diálogo permanente con las iglesias.",
      "Marchas similares se realizaron en 15 regiones con miles de asistentes. Los líderes anunciaron una jornada nacional de ayuno y oración para octubre.",
      "La Marcha por Jesús nació en Brasil en 1993 e inspiró ediciones en 170 países. En Lima se realiza desde hace dos décadas cada setiembre.",
      "El memorial entregado propone educación en valores y capellanías hospitalarias. Las iglesias ofrecen 2 000 voluntarios para ollas comunes.",
    ],
    [
      { medio: "Concilio Evangélico del Perú", nota: "Balance oficial de asistencia." },
      { medio: "Arzobispado de Lima", nota: "Comunicado de adhesión." },
    ],
    "18 sep 2026"),
  art("noticias-cristianas-devocional", 3,
    "Misioneros peruanos llevan agua y Biblias a comunidades amazónicas",
    "Brigadas atienden a 5 000 familias en Loreto y Ucayali.",
    [
      "Brigadas misioneras peruanas atienden a 5 000 familias ribereñas de Loreto y Ucayali. Llevan filtros de agua, medicinas y Biblias en español y lenguas originarias.",
      "La misión incluye médicos voluntarios que realizan 300 atenciones diarias. Las comunidades más alejadas solo se alcanzan en pequepeque tras horas de navegación.",
      "Los líderes asháninkas agradecieron el respeto a sus costumbres y la ayuda sin condiciones. Piden continuidad frente a la crecida de los ríos.",
      "La campaña se financia con ofrendas de iglesias de todo el país. La meta es llegar a 12 000 familias antes de fin de año.",
      "Cada brigada lleva 200 filtros de cerámica que potabilizan 20 litros diarios por familia. El costo unitario es de 25 soles con vida útil de dos años.",
      "Las Biblias en asháninka y shipibo se imprimieron con apoyo de traductores nativos. Ya circulan 10 000 ejemplares en 200 comunidades.",
    ],
    [
      { medio: "Red de Misiones Amazónicas", nota: "Reporte de brigadas 2026." },
      { medio: "Agencia Andina", nota: "Cobertura de la misión." },
    ],
    "16 sep 2026"),
  // ── 21 · Educación ──
  art("educacion", 1,
    "Sunedu otorga licenciamiento a cinco universidades regionales",
    "Más de 40 000 estudiantes se benefician con la autorización.",
    [
      "La Sunedu otorgó el licenciamiento institucional a cinco universidades de regiones tras verificar condiciones básicas de calidad. El beneficio alcanza a 40 000 estudiantes.",
      "Las casas de estudio cumplieron con docentes a tiempo completo, laboratorios y líneas de investigación. Dos de ellas destacan en investigación amazónica y andina.",
      "El superintendente informó que 12 universidades siguen en proceso con plazo hasta diciembre. Las que no cumplan deberán cesar admisiones.",
      "Rectores piden que el licenciamiento incluya financiamiento para infraestructura. El Minedu evalúa un fondo concursable de 300 millones de soles.",
      "Las condiciones básicas exigen 25% de docentes a tiempo completo y líneas de investigación activas. Solo 60 de 140 universidades las cumplen hoy.",
      "El ranking Sunedu premia producción científica en Scopus y patentes. La Cayetano, la UNI y San Marcos lideran por tercer año consecutivo.",
    ],
    [
      { medio: "Sunedu", nota: "Resoluciones de licenciamiento." },
      { medio: "Minedu", nota: "Plan de fortalecimiento universitario." },
    ],
    "18 sep 2026"),
  art("educacion", 2,
    "Admisión 2027: San Marcos ofrece 5 000 vacantes y examen descentralizado",
    "El examen se rendirá en 10 sedes regionales por primera vez.",
    [
      "La Universidad Nacional Mayor de San Marcos ofrecerá 5 000 vacantes para el proceso 2027. Por primera vez, el examen de admisión se rendirá en diez sedes regionales.",
      "La descentralización busca que talentos de provincias no viajen a Lima. Medicina, Ingeniería y Derecho concentran la mayor demanda con ratios de 30 a 1.",
      "La decana anunció becas integrales para los primeros puestos de colegios públicos. También habrá ingreso directo para medallistas de olimpiadas científicas.",
      "Academias preuniversitarias proyectan 80 000 postulantes. La prueba se realizará en marzo con estrictas medidas de seguridad biométrica.",
      "El examen consta de 100 preguntas con puntaje diferenciado por área. Medicina exige 1 400 puntos sobre 2 000; el último ingresante rozó esa cifra.",
      "San Marcos ofrece 68 carreras con Ingeniería de Sistemas a la cabeza en demanda. El 70% de ingresantes proviene de colegios públicos.",
    ],
    [
      { medio: "UNMSM – OCA", nota: "Prospecto de admisión 2027." },
      { medio: "Agencia Andina", nota: "Cobertura del anuncio." },
    ],
    "16 sep 2026"),
  art("educacion", 3,
    "Tabletas con internet llegan a 200 000 escolares rurales",
    "El programa incluye contenidos offline y tutorías virtuales.",
    [
      "El Minedu distribuye 200 000 tabletas con internet a escolares de zonas rurales. Los equipos incluyen contenidos offline de matemática y comprensión lectora.",
      "Cada tableta viene con un plan de datos educativo y tutorías virtuales dos veces por semana. Los docentes reciben capacitación en aulas híbridas.",
      "La brecha digital rural aún es amplia: solo el 35% de colegios tiene conectividad. El programa prioriza escuelas unidocentes y multigrado.",
      "Padres de familia firman compromisos de cuidado y uso pedagógico. En pilotos previos, la comprensión lectora subió 12 puntos.",
      "Las tabletas bloquean redes sociales y juegos en horario escolar por MDM. El contenido offline pesa 32 GB con videos y simuladores.",
      "El programa Aprendo en Casa digital suma 5 000 sesiones grabadas. Los tutores atienden dudas por WhatsApp con respuesta en 24 horas.",
    ],
    [
      { medio: "Minedu", nota: "Programa de conectividad rural." },
      { medio: "Defensoría del Pueblo", nota: "Supervisión de brecha digital." },
    ],
    "15 sep 2026"),
  // ── 22 · Medio Ambiente y Clima ──
  art("medio-ambiente-clima", 1,
    "Senamhi: lluvias sobre lo normal en el norte por Niño costero débil",
    "Piura, Lambayeque y Tumbes activan planes de contingencia.",
    [
      "El Senamhi pronostica lluvias sobre lo normal en la costa norte por un Niño costero de magnitud débil. Piura, Lambayeque y Tumbes ya activaron sus planes de contingencia.",
      "Se esperan precipitaciones 30% superiores entre diciembre y marzo. Las quebradas activadas en 2023 están bajo vigilancia con sensores de caudal.",
      "Indeci preposiciona maquinaria, carpas y alimentos en 50 almacenes. Los gobiernos regionales deben limpiar drenes antes de noviembre.",
      "Agricultores piden seguros agrarios subsidiados ante posibles pérdidas. El Midagri activará el fondo de contingencia de 200 millones de soles.",
      "El Niño costero débil eleva la temperatura del mar entre 1 y 1,5 grados. Ese calentamiento multiplica por tres la probabilidad de lluvias extremas.",
      "El seguro catastrófico cubre 600 000 hectáreas con prima estatal del 100%. El pago se activa por satélite sin necesidad de inspección en campo.",
    ],
    [
      { medio: "Senamhi", nota: "Pronóstico climático trimestral." },
      { medio: "Indeci", nota: "Plan de preparación." },
    ],
    "19 sep 2026"),
  art("medio-ambiente-clima", 2,
    "Incendios forestales arrasan 12 000 hectáreas en la sierra sur",
    "Cusco y Apurímac concentran el 60% de los focos de calor.",
    [
      "Los incendios forestales arrasaron 12 000 hectáreas en la sierra sur durante la temporada seca. Cusco y Apurímac concentran el 60% de los focos, la mayoría por quemas agrícolas.",
      "El Serfor desplegó 40 brigadas y dos helicópteros con helibaldes. El humo afectó la calidad del aire en ciudades y obligó a suspender clases.",
      "Las penas por provocar incendios llegan a 6 años de cárcel, pero casi no hay sentencias. Fiscales ambientales piden juzgados especializados.",
      "Comunidades campesinas ensayan quemas controladas con calendarios y cortafuegos. Donde se aplican, los incendios bajan 70%.",
      "El 98% de los incendios es de origen humano, la mitad por quemas agrícolas. Agosto y setiembre concentran el 60% de los focos anuales.",
      "Los satélites del Indeci detectan focos de 30 metros con alerta en 3 horas. Las brigadas comunales reciben kits con mochilas y batefuegos.",
    ],
    [
      { medio: "Serfor", nota: "Reporte de incendios 2026." },
      { medio: "Senamhi", nota: "Calidad del aire." },
    ],
    "17 sep 2026"),
  art("medio-ambiente-clima", 3,
    "Rímac: plan de descontaminación con 10 plantas de tratamiento",
    "Sedapal y municipios limpiarán el río que abastece a Lima.",
    [
      "Sedapal y cinco municipalidades lanzaron el plan de descontaminación del río Rímac con diez plantas de tratamiento. El río abastece al 80% de Lima y hoy recibe descargas mineras e industriales.",
      "La inversión es de 900 millones de soles en cinco años, con fiscalización de la ANA a 300 vertimientos. Las empresas que incumplan serán multadas y clausuradas.",
      "El plan incluye reforestación de riberas y un corredor ecológico de 20 kilómetros. Vecinos participarán como vigilantes ambientales.",
      "Especialistas consideran la meta ambiciosa pero alcanzable si hay continuidad. Recuerdan que tres planes anteriores fracasaron por falta de presupuesto.",
      "El Rímac recibe 28 toneladas diarias de residuos sólidos y 350 descargas informales. El monitoreo de la ANA cubre 40 puntos con sensores continuos.",
      "La PTAR Santa Clara tratará 4 m³/s de desagües de Lima este. Con las diez plantas, el 80% de las aguas servidas recibirá tratamiento.",
    ],
    [
      { medio: "Sedapal", nota: "Plan Rímac limpio." },
      { medio: "Autoridad Nacional del Agua", nota: "Fiscalización de vertimientos." },
    ],
    "15 sep 2026"),
  // ── 23 · Transporte e Infraestructura ──
  art("transporte-infraestructura", 1,
    "Puerto de Chancay moviliza su contenedor un millón antes de lo previsto",
    "La carga hacia Asia crece 40% y se anuncian dos muelles más.",
    [
      "El puerto de Chancay alcanzó su contenedor un millón, seis meses antes de lo proyectado. La carga hacia Asia crece 40% impulsada por arándanos, paltas y cobre.",
      "El terminal opera con grúas automatizadas y tiempos de atención 50% menores que el Callao. Navieras de tres alianzas globales ya recalan semanalmente.",
      "El MTC anunció la ampliación con dos muelles adicionales y un antepuerto logístico en Ancón. La inversión de la segunda fase es de 1 300 millones de dólares.",
      "Transportistas piden culminar la vía de evitamiento para no saturar la Panamericana. El estudio definitivo se entrega en diciembre.",
      "Chancay opera con 4 grúas STS automatizadas y 25 RTG eléctricas. Su calado de 18 metros recibe buques de 24 000 TEU sin aligerar.",
      "El antepuerto de Ancón concentrará 2 000 camiones diarios fuera de la ciudad. El túnel de 2 kilómetros conectará directo con el terminal.",
    ],
    [
      { medio: "Autoridad Portuaria Nacional", nota: "Estadística portuaria." },
      { medio: "MTC", nota: "Plan de ampliación." },
    ],
    "19 sep 2026"),
  art("transporte-infraestructura", 2,
    "Línea 2 del Metro: seis estaciones nuevas abren en diciembre",
    "Ate y Santa Anita se conectan en 20 minutos al centro de Lima.",
    [
      "La Línea 2 del Metro abrirá seis estaciones nuevas en diciembre entre Ate y Santa Anita. El tramo reducirá a 20 minutos un viaje que hoy toma una hora.",
      "La ATU informó que el sistema transporta ya 300 000 pasajeros diarios en su tramo parcial. Con la ampliación llegará a 500 000.",
      "Las obras de la etapa central avanzan bajo el centro histórico con tuneladoras alemanas. Arqueólogos supervisan cada metro por los hallazgos coloniales.",
      "La tarifa integrada con corredores se definirá antes de la apertura. Colectivos piden que no supere los 2,50 soles.",
      "La Línea 2 recorrerá 27 kilómetros con 27 estaciones de Ate al Callao. Los trenes sin conductor circularán cada 90 segundos en hora punta.",
      "El tramo central bajo el Rímac usa tuneladora de 10 metros con dovelas de concreto. Ya se excavaron 12 de los 16 kilómetros totales.",
    ],
    [
      { medio: "ATU", nota: "Cronograma de apertura." },
      { medio: "MTC – Línea 2", nota: "Avance de obra." },
    ],
    "17 sep 2026"),
  art("transporte-infraestructura", 3,
    "Nuevo aeropuerto Jorge Chávez recibe 25 millones de pasajeros al año",
    "El terminal duplicó su capacidad y estrena segunda pista.",
    [
      "El nuevo terminal del aeropuerto Jorge Chávez opera a plena capacidad con 25 millones de pasajeros anuales. La segunda pista permite 65 operaciones por hora.",
      "Lima se consolida como hub regional con 40 destinos internacionales directos. Las aerolíneas low cost aportan ya el 35% del tráfico.",
      "El MTC licita el tren de cercanías al aeropuerto para 2028. Mientras tanto, buses expresos conectan con Miraflores y el centro.",
      "Pasajeros reportan mejoras pero piden más personal en migraciones en hora punta. El operador sumará 200 agentes antes de fin de año.",
      "El terminal tiene 270 000 m² con 67 mangas y hotel de tránsito. La segunda pista permite aterrizajes simultáneos con 1,5 kilómetros de separación.",
      "El retail aeroportuario factura 400 millones anuales con 120 locales. La ciudad aeropuerto sumará oficinas y logística en 300 hectáreas.",
    ],
    [
      { medio: "Lima Airport Partners", nota: "Estadística operacional." },
      { medio: "MTC", nota: "Plan de accesos." },
    ],
    "15 sep 2026"),
  // ── 24 · Cultura y Entretenimiento ──
  art("cultura-entretenimiento", 1,
    "Cine peruano bate récord con 3 millones de espectadores",
    "Tres películas nacionales superan el medio millón de vistas cada una.",
    [
      "El cine peruano vive su mejor año con 3 millones de espectadores acumulados. Tres producciones nacionales superaron el medio millón de boletos cada una.",
      "Comedias familiares y dramas históricos lideran la taquilla, con rodajes en Cusco, Arequipa e Iquitos. El 60% del público tiene menos de 30 años.",
      "El Ministerio de Cultura duplicó los estímulos a 20 millones de soles anuales. La cuota de pantalla en salas comerciales subirá al 15%.",
      "Cineastas piden incentivos para plataformas de streaming que produzcan en el país. Dos series peruanas ya fueron renovadas para segunda temporada.",
      "El cine regional aporta el 30% de la taquilla nacional con presupuestos menores a 500 000 soles. Ayacucho y Puno lideran la producción quechua.",
      "Los estímulos DAFO financian desarrollo, producción y distribución con 60 ganadores anuales. La devolución por taquilla reinvierte en nuevos proyectos.",
    ],
    [
      { medio: "Ministerio de Cultura – DAFO", nota: "Balance cinematográfico." },
      { medio: "Diario El Comercio", nota: "Taquilla nacional." },
    ],
    "18 sep 2026"),
  art("cultura-entretenimiento", 2,
    "Gastronomía: Perú es elegido mejor destino culinario por 12° año",
    "Los World Travel Awards premian a Lima y a la cocina amazónica.",
    [
      "El Perú fue elegido mejor destino culinario del mundo por duodécimo año en los World Travel Awards. Lima concentró los premios a mejor restaurante y mejor chef.",
      "La cocina amazónica fue la revelación con ingredientes como el paiche y el camu camu. Chefs de Iquitos lideran la nueva ola gastronómica.",
      "PromPerú estima que la gastronomía atrae al 40% de los turistas extranjeros. La ruta del pisco y el café suma 200 000 visitantes anuales.",
      "Restauranteros piden formalizar a 50 000 puestos de comida callejera con capacitación sanitaria. El programa Mercados Saludables ya certificó 300 locales.",
      "Central y Maido figuran entre los 10 mejores del mundo por octavo año. Sus menús degustación superan los 1 000 soles con reservas de meses.",
      "La Despensa Amazónica abastece a 200 restaurantes con insumos de 40 comunidades. El paiche manejado genera 5 millones anuales a pescadores.",
    ],
    [
      { medio: "PromPerú", nota: "Premios World Travel Awards." },
      { medio: "Ministerio de Comercio Exterior", nota: "Impacto turístico." },
    ],
    "16 sep 2026"),
  art("cultura-entretenimiento", 3,
    "Fiesta de la Candelaria postula a patrimonio inmaterial de la humanidad",
    "Puno prepara la festividad más grande de su historia para febrero.",
    [
      "La Festividad de la Virgen de la Candelaria postula al reconocimiento de patrimonio inmaterial de la humanidad. El expediente se presenta ante la Unesco en diciembre.",
      "Puno prepara su edición más grande con 200 comparsas y 40 000 danzarines. Se esperan 150 000 visitantes y un movimiento de 100 millones de soles.",
      "El Ministerio de Cultura financia la salvaguardia de trajes y máscaras con 5 millones de soles. Artesanos de 13 distritos participan en los talleres.",
      "Hoteles y transporte ya reportan reservas al 90%. La Dircetur instaló puestos de información y seguridad en accesos.",
      "La Candelaria moviliza 200 conjuntos con trajes bordados que pesan hasta 20 kilos. Cada danzarín invierte 5 000 soles en su vestimenta.",
      "El expediente Unesco documenta 250 años de sincretismo aimara-católico. La festividad fue declarada Patrimonio Cultural de la Nación en 2003.",
    ],
    [
      { medio: "Ministerio de Cultura", nota: "Expediente Unesco." },
      { medio: "Gobierno Regional de Puno", nota: "Plan Candelaria." },
    ],
    "15 sep 2026"),
  // ── 25 · Migración ──
  art("migracion", 1,
    "Remesas baten récord: 5 200 millones de dólares en doce meses",
    "EE.UU., España y Chile concentran el 75% de los envíos.",
    [
      "Las remesas de peruanos en el exterior alcanzaron 5 200 millones de dólares en doce meses, un récord histórico. Representan ya el 1,8% del PBI nacional.",
      "Estados Unidos, España y Chile concentran tres de cada cuatro dólares enviados. El costo promedio de envío bajó a 3,5% gracias a las billeteras digitales.",
      "El BCRP destaca que las remesas sostienen el consumo de 800 000 hogares. Cajamarca, Piura y Lima son las regiones más receptoras.",
      "Economistas piden canalizar parte de los flujos hacia ahorro y vivienda. El Fondo MiVivienda lanzará un producto para receptores de remesas.",
      "El costo de envío cayó de 8% a 3,5% en una década por la competencia digital. Cada punto ahorrado deja 50 millones anuales en los hogares.",
      "EE.UU. aporta 2 000 millones con envíos promedio de 300 dólares mensuales. España sigue con 900 millones pese a la desaceleración europea.",
    ],
    [
      { medio: "BCRP", nota: "Estadística de remesas." },
      { medio: "Cancillería del Perú", nota: "Atención a connacionales." },
    ],
    "17 sep 2026"),
  art("migracion", 2,
    "Migraciones regulariza a 300 000 venezolanos con nuevo carné",
    "El permiso permite trabajar y acceder a salud pública.",
    [
      "Migraciones culminó la regularización de 300 000 ciudadanos venezolanos con el nuevo carné de extranjería. El documento permite trabajar formalmente y acceder a salud pública.",
      "El 60% de los regularizados tiene entre 20 y 39 años y trabaja en comercio y servicios. La planilla electrónica registra ya 90 000 contratos.",
      "Organismos internacionales financian la segunda fase con 40 millones de dólares. Incluirá verificación de antecedentes y carné digital.",
      "Especialistas piden políticas de integración educativa para 120 000 niños migrantes. El Minedu incorporó a 85 000 al sistema escolar.",
      "El carné de extranjería se tramita en 30 días con antecedentes y preinscripción Reniec. Habilita SIS, planilla y cuentas bancarias.",
      "La xenofobia bajó de 45% a 32% según encuestas recientes. Las ferias de integración laboral colocaron a 20 000 migrantes este año.",
    ],
    [
      { medio: "Migraciones Perú", nota: "Balance de regularización." },
      { medio: "ACNUR Perú", nota: "Apoyo a la integración." },
    ],
    "16 sep 2026"),
  art("migracion", 3,
    "Peruanos en el exterior podrán votar por internet en 2027",
    "La ONPE implementará el voto digital para 1,2 millones de electores.",
    [
      "La ONPE implementará el voto por internet para 1,2 millones de peruanos en el exterior desde 2027. El sistema usará identidad digital y auditoría internacional.",
      "En las últimas elecciones solo votó el 35% de los residentes fuera, por distancias a consulados. El voto digital apunta a duplicar la participación.",
      "El JNE supervisará el padrón y la fiscalización partidaria del software. Habrá una prueba piloto en tres países este año.",
      "Colectivos de peruanos en el exterior celebran la medida largamente esperada. Piden además escaños reservados en el Congreso.",
      "El sistema usará DNI electrónico con certificados digitales y voto cifrado de extremo a extremo. Auditorías internacionales certificarán cada elección.",
      "Argentina, Chile e Italia concentran 500 000 electores con padrón activo. El voto exterior representa el 5% del padrón nacional.",
    ],
    [
      { medio: "ONPE", nota: "Plan de voto digital." },
      { medio: "JNE", nota: "Fiscalización del padrón." },
    ],
    "15 sep 2026"),
];
