import type { Insumo, RecursoKind } from "./types";

type Row = [string, RecursoKind, string, string, string, number, number, string];

function i(id: string, kind: RecursoKind, codigo: string, nombre: string, und: string, precio: number, iu: number, categoria: string): Insumo {
  return { id, kind, codigo, nombre, und, precio, iu, categoria };
}

/**
 * Catálogo de instalaciones (IE, IS, IM, COM): detallado (sección, diámetro, potencia)
 * y no detallado (partida alzada / suministro e instalación). Precios de referencia S/ Lima.
 */
const RAW: Row[] = [
  // —— Mano de obra especializada ——
  ["MO-FRI", "mo", "MO-041", "Operario", "hh", 24.42, 47, "Mano de obra"],
  ["MO-HVAC", "mo", "MO-042", "Operario", "hh", 24.42, 47, "Mano de obra"],
  ["MO-GASN", "mo", "MO-043", "Operario", "hh", 24.42, 47, "Mano de obra"],
  ["MO-CABL", "mo", "MO-044", "Operario", "hh", 24.42, 47, "Mano de obra"],
  ["MO-AYUF", "mo", "MO-045", "Oficial", "hh", 19.12, 47, "Mano de obra"],

  // —— Replanteo y topografía ——
  ["MAT-CALR", "mat", "MAT-801", "Cal para trazo y replanteo", "kg", 1.15, 21, "Replanteo y topografía"],
  ["MAT-ESTC", "mat", "MAT-802", "Estaca de madera 2\"×2\"×0.60 m", "und", 2.8, 43, "Replanteo y topografía"],
  ["MAT-PINTT", "mat", "MAT-803", "Pintura de trazo / spray de ejes", "und", 8.5, 54, "Replanteo y topografía"],
  ["MAT-HILN", "mat", "MAT-804", "Hilo de nylon para replanteo", "rollo", 6.5, 39, "Replanteo y topografía"],
  ["MAT-CLAVR", "mat", "MAT-805", "Clavo de acero para ejes", "kg", 8.2, 37, "Replanteo y topografía"],
  ["MAT-YESR", "mat", "MAT-806", "Yeso para marcas de eje", "kg", 1.1, 39, "Replanteo y topografía"],
  ["MAT-JALON", "mat", "MAT-807", "Jalón / mira de replanteo", "und", 28, 39, "Replanteo y topografía"],
  ["MAT-CINTM", "mat", "MAT-808", "Cinta métrica 30 m", "und", 22, 37, "Replanteo y topografía"],
  ["MAT-PLM", "mat", "MAT-809", "Plomada de albañil", "und", 12, 37, "Replanteo y topografía"],
  ["MAT-ND-REP", "mat", "MAT-810", "Replanteo de instalaciones (no detallado)", "m²", 2.4, 39, "Insumos no detallados"],

  // —— Conductores: no detallado + TW / THHN / THW ——
  ["MAT-ND-CAB", "mat", "MAT-811", "Conductor eléctrico (no detallado)", "m", 3.2, 7, "Insumos no detallados"],
  ["MAT-TW16", "mat", "MAT-812", "Cable TW 16 AWG", "m", 1.35, 7, "Instalaciones eléctricas"],
  ["MAT-THHN14", "mat", "MAT-813", "Cable THHN/THWN-2 14 AWG (~2.08 mm²) 600 V 90 °C", "m", 2.15, 7, "Instalaciones eléctricas"],
  ["MAT-THHN10", "mat", "MAT-814", "Cable THHN/THWN-2 10 AWG (~5.26 mm²) 600 V 90 °C", "m", 4.2, 7, "Instalaciones eléctricas"],
  ["MAT-THHN8", "mat", "MAT-815", "Cable THHN/THWN 8 AWG", "m", 6.4, 7, "Instalaciones eléctricas"],
  ["MAT-THHN6", "mat", "MAT-816", "Cable THHN/THWN 6 AWG", "m", 9.8, 7, "Instalaciones eléctricas"],
  ["MAT-THHN4", "mat", "MAT-817", "Cable THHN/THWN 4 AWG", "m", 14.5, 7, "Instalaciones eléctricas"],
  ["MAT-THHN2", "mat", "MAT-818", "Cable THHN/THWN 2 AWG", "m", 22, 7, "Instalaciones eléctricas"],
  ["MAT-THW6", "mat", "MAT-819", "Cable THW-90 6 AWG (~13 mm²) 600 V PVC 90 °C", "m", 8.9, 7, "Instalaciones eléctricas"],
  ["MAT-THW4", "mat", "MAT-820", "Cable THW-90 4 AWG (~21 mm²) 600 V PVC 90 °C", "m", 13.2, 7, "Instalaciones eléctricas"],
  ["MAT-CU6", "mat", "MAT-821", "Alambre de cobre desnudo 6 AWG", "m", 11.5, 6, "Instalaciones eléctricas"],
  ["MAT-CU4", "mat", "MAT-822", "Alambre de cobre desnudo 4 AWG", "m", 16.8, 6, "Instalaciones eléctricas"],
  ["MAT-CU2", "mat", "MAT-823", "Cable de cobre desnudo 2 AWG", "m", 24, 6, "Instalaciones eléctricas"],
  ["MAT-WP6", "mat", "MAT-824", "Cable tipo WP 6 AWG", "m", 9.5, 8, "Instalaciones eléctricas"],
  ["MAT-WP4", "mat", "MAT-825", "Cable tipo WP 4 AWG", "m", 14.2, 8, "Instalaciones eléctricas"],
  ["MAT-XLPE", "mat", "MAT-826", "Cable XLPE 0.6/1 kV 1×16 mm²", "m", 12.5, 19, "Instalaciones eléctricas"],

  // —— Cables de fuerza NYY / N2XY (detallado) ——
  ["MAT-NYY210", "mat", "MAT-827", "Cable NYY 2×10 mm² 0.6/1 kV (PVC/PVC)", "m", 14.5, 19, "Instalaciones eléctricas"],
  ["MAT-NYY310", "mat", "MAT-828", "Cable NYY 3×10 mm² 0.6/1 kV (PVC/PVC)", "m", 19.5, 19, "Instalaciones eléctricas"],
  ["MAT-NYY325", "mat", "MAT-829", "Cable NYY 3×25 mm² 0.6/1 kV (PVC/PVC)", "m", 38, 19, "Instalaciones eléctricas"],
  ["MAT-NYY335", "mat", "MAT-830", "Cable NYY 3×35 mm² 0.6/1 kV (PVC/PVC)", "m", 52, 19, "Instalaciones eléctricas"],
  ["MAT-NYY350", "mat", "MAT-831", "Cable NYY 3×50 mm²", "m", 72, 19, "Instalaciones eléctricas"],
  ["MAT-NYY416", "mat", "MAT-832", "Cable NYY 4×16 mm²", "m", 32, 19, "Instalaciones eléctricas"],
  ["MAT-NYY425", "mat", "MAT-833", "Cable NYY 4×25 mm²", "m", 48, 19, "Instalaciones eléctricas"],
  ["MAT-N2XY35", "mat", "MAT-834", "Cable N2XY 3×35 mm²", "m", 58, 19, "Instalaciones eléctricas"],
  ["MAT-N2XY50", "mat", "MAT-835", "Cable N2XY 3×50 mm² XLPE 0.6/1 kV", "m", 82, 19, "Instalaciones eléctricas"],
  ["MAT-N2XY70", "mat", "MAT-836", "Cable N2XY 3×70 mm²", "m", 118, 19, "Instalaciones eléctricas"],
  ["MAT-N2XY95", "mat", "MAT-837", "Cable N2XY 3×95 mm²", "m", 165, 19, "Instalaciones eléctricas"],
  ["MAT-ND-ALIM", "mat", "MAT-838", "Alimentador eléctrico (no detallado)", "m", 22, 19, "Insumos no detallados"],

  // —— Canalizaciones PVC, EMT, IMC, bandejas ——
  ["MAT-ND-CAN", "mat", "MAT-839", "Canalización eléctrica (no detallada)", "m", 6.5, 72, "Insumos no detallados"],
  ["MAT-PVC15", "mat", "MAT-840", "Tubería PVC-P conduit Ø15 mm (½\")", "m", 2.8, 72, "Instalaciones eléctricas"],
  ["MAT-PVC20", "mat", "MAT-841", "Tubería PVC-P conduit rígido Ø20 mm (¾\") — canalización empotrada", "m", 3.6, 72, "Instalaciones eléctricas"],
  ["MAT-PVC32C", "mat", "MAT-842", "Tubería PVC-P conduit Ø32 mm (1¼\")", "m", 6.8, 72, "Instalaciones eléctricas"],
  ["MAT-PVC40C", "mat", "MAT-843", "Tubería PVC-P conduit Ø40 mm (1½\")", "m", 9.2, 72, "Instalaciones eléctricas"],
  ["MAT-PVC50C", "mat", "MAT-844", "Tubería PVC-P conduit Ø50 mm (2\")", "m", 12.5, 72, "Instalaciones eléctricas"],
  ["MAT-EMT12", "mat", "MAT-845", "Tubería EMT Ø½\"", "m", 7.8, 65, "Instalaciones eléctricas"],
  ["MAT-EMT34", "mat", "MAT-846", "Tubería EMT Ø¾\"", "m", 11.5, 65, "Instalaciones eléctricas"],
  ["MAT-EMT1", "mat", "MAT-847", "Tubería EMT Ø1\"", "m", 16.5, 65, "Instalaciones eléctricas"],
  ["MAT-IMC34", "mat", "MAT-848", "Tubería IMC Ø¾\"", "m", 18, 65, "Instalaciones eléctricas"],
  ["MAT-RMC1", "mat", "MAT-849", "Tubería RMC (rígida) Ø1\"", "m", 28, 65, "Instalaciones eléctricas"],
  ["MAT-FLEXM", "mat", "MAT-850", "Tubo flexible metálico Ø¾\"", "m", 12, 65, "Instalaciones eléctricas"],
  ["MAT-CAN40", "mat", "MAT-851", "Canaleta PVC 40×25 mm", "m", 6.5, 72, "Instalaciones eléctricas"],
  ["MAT-CAN60", "mat", "MAT-852", "Canaleta PVC 60×40 mm", "m", 11, 72, "Instalaciones eléctricas"],
  ["MAT-BAND200", "mat", "MAT-853", "Bandeja portacables 200×100 mm", "m", 78, 51, "Instalaciones eléctricas"],
  ["MAT-BAND300", "mat", "MAT-854", "Bandeja portacables 300×100 mm", "m", 115, 51, "Instalaciones eléctricas"],
  ["MAT-DUCTP", "mat", "MAT-855", "Ducto de piso PVC 50×25 mm", "m", 18, 73, "Instalaciones eléctricas"],
  ["MAT-CURV20", "mat", "MAT-856", "Curva PVC conduit Ø20 mm", "und", 2.2, 72, "Instalaciones eléctricas"],
  ["MAT-CURV25", "mat", "MAT-857", "Curva PVC conduit Ø25 mm", "und", 2.8, 72, "Instalaciones eléctricas"],
  ["MAT-UNI20", "mat", "MAT-858", "Unión / copa PVC conduit Ø20 mm", "und", 1.4, 72, "Instalaciones eléctricas"],
  ["MAT-BUSH", "mat", "MAT-859", "Bushing / contratuerca EMT", "und", 2.6, 65, "Instalaciones eléctricas"],
  ["MAT-CAJA4", "mat", "MAT-860", "Caja cuadrada 4\"×4\" metálica", "und", 8.5, 39, "Instalaciones eléctricas"],
  ["MAT-CAJA6", "mat", "MAT-861", "Caja de registro 6\"×6\"", "und", 18, 39, "Instalaciones eléctricas"],
  ["MAT-CAJAOCT", "mat", "MAT-862", "Caja octogonal de piso / techo", "und", 5.5, 39, "Instalaciones eléctricas"],
  ["MAT-CAJAREC", "mat", "MAT-863", "Caja rectangular de pared", "und", 4.2, 39, "Instalaciones eléctricas"],
  ["MAT-TAPAEM", "mat", "MAT-864", "Tapa ciega / plaqueta ciega", "und", 3.8, 39, "Instalaciones eléctricas"],

  // —— Aparatos y protecciones (suministro; la partida suma instalación) ——
  ["MAT-ND-APT", "mat", "MAT-865", "Aparato eléctrico (no detallado)", "und", 35, 39, "Insumos no detallados"],
  ["MAT-INTD", "mat", "MAT-866", "Interruptor bipolar / doble", "und", 22, 39, "Instalaciones eléctricas"],
  ["MAT-INT4", "mat", "MAT-867", "Interruptor de 4 vías", "und", 28, 39, "Instalaciones eléctricas"],
  ["MAT-DIMM", "mat", "MAT-868", "Dimmer / regulador de luz", "und", 42, 39, "Instalaciones eléctricas"],
  ["MAT-TIMB", "mat", "MAT-869", "Timbre / zumbador", "und", 28, 39, "Instalaciones eléctricas"],
  ["MAT-TOMAGFCI", "mat", "MAT-870", "Tomacorriente GFCI 15 A", "und", 48, 39, "Instalaciones eléctricas"],
  ["MAT-TOMAUSB", "mat", "MAT-871", "Tomacorriente con USB", "und", 38, 39, "Instalaciones eléctricas"],
  ["MAT-TOMATRI", "mat", "MAT-872", "Tomacorriente trifásico 32 A", "und", 65, 39, "Instalaciones eléctricas"],
  ["MAT-TERM10", "mat", "MAT-873", "Termomagnético 10 A 1P", "und", 22, 39, "Instalaciones eléctricas"],
  ["MAT-TERM16", "mat", "MAT-874", "Termomagnético 16 A 1P", "und", 24, 39, "Instalaciones eléctricas"],
  ["MAT-TERM25", "mat", "MAT-875", "Termomagnético 25 A 1P", "und", 32, 39, "Instalaciones eléctricas"],
  ["MAT-TERM32", "mat", "MAT-876", "Termomagnético 32 A 2P", "und", 48, 39, "Instalaciones eléctricas"],
  ["MAT-TERM40", "mat", "MAT-877", "Termomagnético 40 A 2P", "und", 58, 39, "Instalaciones eléctricas"],
  ["MAT-TERM63", "mat", "MAT-878", "Termomagnético 63 A 2P", "und", 85, 39, "Instalaciones eléctricas"],
  ["MAT-DIF25", "mat", "MAT-879", "Interruptor diferencial 25 A 30 mA", "und", 72, 39, "Instalaciones eléctricas"],
  ["MAT-DIF63", "mat", "MAT-880", "Interruptor diferencial 63 A 30 mA", "und", 125, 39, "Instalaciones eléctricas"],
  ["MAT-MCCB100", "mat", "MAT-881", "Breaker caja moldeada 100 A", "und", 280, 39, "Instalaciones eléctricas"],
  ["MAT-MCCB160", "mat", "MAT-882", "Breaker caja moldeada 160 A", "und", 420, 39, "Instalaciones eléctricas"],
  ["MAT-MCCB250", "mat", "MAT-883", "Breaker caja moldeada 250 A", "und", 680, 39, "Instalaciones eléctricas"],
  ["MAT-TAB8", "mat", "MAT-884", "Tablero de distribución 8 polos", "und", 145, 39, "Instalaciones eléctricas"],
  ["MAT-TAB18", "mat", "MAT-885", "Tablero de distribución 18 polos", "und", 240, 39, "Instalaciones eléctricas"],
  ["MAT-TAB36", "mat", "MAT-886", "Tablero de distribución 36 polos", "und", 980, 39, "Instalaciones eléctricas"],
  ["MAT-TGBT", "mat", "MAT-887", "Tablero general TGBT (no detallado)", "und", 1850, 39, "Insumos no detallados"],
  ["MAT-RELE", "mat", "MAT-888", "Relé térmico / auxiliar", "und", 55, 39, "Instalaciones eléctricas"],
  ["MAT-TIMER", "mat", "MAT-889", "Temporizador astronómico / horario", "und", 95, 39, "Instalaciones eléctricas"],
  ["MAT-PHOTO", "mat", "MAT-890", "Fotocelda para alumbrado", "und", 38, 39, "Instalaciones eléctricas"],
  ["MAT-LUM9", "mat", "MAT-891", "Luminaria LED empotrada 9 W", "und", 32, 12, "Instalaciones eléctricas"],
  ["MAT-LUM12", "mat", "MAT-892", "Luminaria LED empotrada 12 W", "und", 38, 12, "Instalaciones eléctricas"],
  ["MAT-LUM24", "mat", "MAT-893", "Luminaria LED empotrada 24 W", "und", 58, 12, "Instalaciones eléctricas"],
  ["MAT-PLAFO", "mat", "MAT-894", "Plafón LED 18 W sobrepuesto", "und", 42, 12, "Instalaciones eléctricas"],
  ["MAT-TUBLED", "mat", "MAT-895", "Tubo LED T8 18 W 1.20 m", "und", 18, 12, "Instalaciones eléctricas"],
  ["MAT-SPOT", "mat", "MAT-896", "Spot LED 7 W riel / empotrado", "und", 28, 12, "Instalaciones eléctricas"],
  ["MAT-APLIQ", "mat", "MAT-897", "Aplique de muro LED 12 W", "und", 55, 12, "Instalaciones eléctricas"],
  ["MAT-FAROL", "mat", "MAT-898", "Farol de jardín LED 20 W", "und", 95, 11, "Instalaciones eléctricas"],
  ["MAT-REFL200", "mat", "MAT-899", "Proyector LED 200 W", "und", 185, 11, "Instalaciones eléctricas"],
  ["MAT-VENTIL", "mat", "MAT-900", "Ventilador de techo c/lámpara", "und", 280, 12, "Instalaciones eléctricas"],

  // —— Comunicaciones y corrientes débiles ——
  ["MAT-UTP5", "mat", "MAT-901", "Cable UTP Cat 5e", "m", 1.45, 18, "Comunicaciones"],
  ["MAT-UTP6A", "mat", "MAT-902", "Cable UTP Cat 6A", "m", 3.4, 18, "Comunicaciones"],
  ["MAT-FIB12", "mat", "MAT-903", "Fibra óptica 12 hilos", "m", 6.8, 18, "Comunicaciones"],
  ["MAT-FIB24", "mat", "MAT-904", "Fibra óptica 24 hilos", "m", 9.5, 18, "Comunicaciones"],
  ["MAT-RG11", "mat", "MAT-905", "Cable coaxial RG-11", "m", 3.2, 18, "Comunicaciones"],
  ["MAT-PATCH", "mat", "MAT-906", "Patch cord UTP Cat 6 2 m", "und", 12, 18, "Comunicaciones"],
  ["MAT-PATCHP", "mat", "MAT-907", "Patch panel 24 puertos Cat 6", "und", 185, 18, "Comunicaciones"],
  ["MAT-SW24", "mat", "MAT-908", "Switch 24 puertos", "und", 480, 39, "Comunicaciones"],
  ["MAT-RACK24", "mat", "MAT-909", "Rack de comunicaciones 24 U", "und", 980, 39, "Comunicaciones"],
  ["MAT-CAMIP", "mat", "MAT-910", "Cámara IP interior", "und", 280, 39, "Comunicaciones"],
  ["MAT-CAMIPE", "mat", "MAT-911", "Cámara IP exterior / bullet", "und", 420, 39, "Comunicaciones"],
  ["MAT-NVR", "mat", "MAT-912", "NVR 8 canales + HDD 2 TB", "und", 1450, 39, "Comunicaciones"],
  ["MAT-DETH", "mat", "MAT-913", "Detector de humo fotoeléctrico", "und", 85, 39, "Seguridad e incendio"],
  ["MAT-CINC", "mat", "MAT-914", "Central de incendio 4 zonas", "und", 1850, 39, "Seguridad e incendio"],
  ["MAT-SIRENA", "mat", "MAT-915", "Sirena / strobe de incendio", "und", 95, 39, "Seguridad e incendio"],
  ["MAT-PULS", "mat", "MAT-916", "Pulsador de emergencia / palanca", "und", 45, 39, "Seguridad e incendio"],
  ["MAT-ACCARD", "mat", "MAT-917", "Control de acceso / lector de tarjeta", "und", 380, 39, "Comunicaciones"],
  ["MAT-ND-COM", "mat", "MAT-918", "Sistema de comunicaciones (no detallado)", "pnto", 85, 18, "Insumos no detallados"],

  // —— Tuberías sanitarias detalladas ——
  ["MAT-ND-TUB", "mat", "MAT-919", "Tubería sanitaria (no detallada)", "m", 12, 66, "Insumos no detallados"],
  ["MAT-SAP15", "mat", "MAT-920", "Tubería PVC SAP Ø15 mm (½\")", "m", 3.2, 66, "Tuberías y accesorios"],
  ["MAT-SAP40", "mat", "MAT-921", "Tubería PVC SAP Ø40 mm (1½\")", "m", 8.8, 66, "Tuberías y accesorios"],
  ["MAT-SAP50", "mat", "MAT-922", "Tubería PVC SAP Ø50 mm (2\")", "m", 10.5, 66, "Tuberías y accesorios"],
  ["MAT-SAL40", "mat", "MAT-923", "Tubería PVC SAL Ø40 mm", "m", 6.5, 66, "Tuberías y accesorios"],
  ["MAT-SAL50", "mat", "MAT-924", "Tubería PVC SAL Ø50 mm", "m", 8.2, 66, "Tuberías y accesorios"],
  ["MAT-SAL75", "mat", "MAT-925", "Tubería PVC SAL Ø75 mm", "m", 14, 66, "Tuberías y accesorios"],
  ["MAT-CPVC25", "mat", "MAT-926", "Tubería CPVC Ø25 mm (¾\")", "m", 11.5, 72, "Tuberías y accesorios"],
  ["MAT-CPVC32", "mat", "MAT-927", "Tubería CPVC Ø32 mm (1\")", "m", 15.5, 72, "Tuberías y accesorios"],
  ["MAT-PPR20", "mat", "MAT-928", "Tubería PPR Ø20 mm", "m", 7.2, 72, "Tuberías y accesorios"],
  ["MAT-PPR32", "mat", "MAT-929", "Tubería PPR Ø32 mm", "m", 12.8, 72, "Tuberías y accesorios"],
  ["MAT-PPR40", "mat", "MAT-930", "Tubería PPR Ø40 mm", "m", 18.5, 72, "Tuberías y accesorios"],
  ["MAT-CU38", "mat", "MAT-931", "Tubería de cobre Ø⅜\" tipo L", "m", 22, 68, "Tuberías y accesorios"],
  ["MAT-CU34", "mat", "MAT-932", "Tubería de cobre Ø¾\" tipo L", "m", 42, 68, "Tuberías y accesorios"],
  ["MAT-CU1", "mat", "MAT-933", "Tubería de cobre Ø1\" tipo L", "m", 58, 68, "Tuberías y accesorios"],
  ["MAT-CODO90", "mat", "MAT-934", "Codo 90° PVC SAP", "und", 3.8, 72, "Tuberías y accesorios"],
  ["MAT-CODO45", "mat", "MAT-935", "Codo 45° PVC SAP", "und", 3.5, 72, "Tuberías y accesorios"],
  ["MAT-YEE", "mat", "MAT-936", "Yee PVC SAL", "und", 12, 72, "Tuberías y accesorios"],
  ["MAT-TRAMP", "mat", "MAT-937", "Trampa / sifón PVC Ø50 mm", "und", 14, 72, "Tuberías y accesorios"],
  ["MAT-TAPPVC", "mat", "MAT-938", "Tapón PVC", "und", 2.2, 72, "Tuberías y accesorios"],
  ["MAT-BUSHP", "mat", "MAT-939", "Bushing / reducción bushing PVC", "und", 4.5, 72, "Tuberías y accesorios"],
  ["MAT-VALBOL", "mat", "MAT-940", "Válvula de bola bronce ½\"", "und", 28, 77, "Tuberías y accesorios"],
  ["MAT-VALGL", "mat", "MAT-941", "Válvula de globo ½\"", "und", 38, 77, "Tuberías y accesorios"],
  ["MAT-VALFL", "mat", "MAT-942", "Válvula flotador ½\"", "und", 45, 77, "Tuberías y accesorios"],
  ["MAT-VALAL", "mat", "MAT-943", "Válvula de alivio / seguridad", "und", 65, 77, "Tuberías y accesorios"],
  ["MAT-LAVM", "mat", "MAT-944", "Lavamanos mural", "und", 125, 10, "Aparatos sanitarios y grifería"],
  ["MAT-INODS", "mat", "MAT-945", "Inodoro suspendido", "und", 520, 10, "Aparatos sanitarios y grifería"],
  ["MAT-DUCHT", "mat", "MAT-946", "Ducha teléfono / flexible", "und", 55, 10, "Aparatos sanitarios y grifería"],
  ["MAT-CALPAS", "mat", "MAT-947", "Calentador de paso a gas 10 L/min", "und", 680, 10, "Aparatos sanitarios y grifería"],
  ["MAT-ND-APA", "mat", "MAT-948", "Aparato sanitario (no detallado)", "und", 180, 10, "Insumos no detallados"],

  // —— HVAC: minisplit, condensadora, ductos, refrigerante ——
  ["MAT-ND-AA", "mat", "MAT-949", "Sistema de aire acondicionado (no detallado)", "glb", 4500, 49, "Insumos no detallados"],
  ["MAT-MS9", "mat", "MAT-950", "Minisplit inverter 9 000 BTU (suministro)", "und", 1450, 49, "Instalaciones mecánicas y HVAC"],
  ["MAT-MS12", "mat", "MAT-951", "Minisplit inverter 12 000 BTU (suministro)", "und", 1850, 49, "Instalaciones mecánicas y HVAC"],
  ["MAT-MS18", "mat", "MAT-952", "Minisplit inverter 18 000 BTU (suministro)", "und", 2450, 49, "Instalaciones mecánicas y HVAC"],
  ["MAT-MS24", "mat", "MAT-953", "Minisplit inverter 24 000 BTU (suministro)", "und", 3250, 49, "Instalaciones mecánicas y HVAC"],
  ["MAT-MS36", "mat", "MAT-954", "Minisplit inverter 36 000 BTU (suministro)", "und", 4850, 49, "Instalaciones mecánicas y HVAC"],
  ["MAT-COND12", "mat", "MAT-955", "Unidad condensadora 12 000 BTU", "und", 1250, 49, "Instalaciones mecánicas y HVAC"],
  ["MAT-COND18", "mat", "MAT-956", "Unidad condensadora 18 000 BTU", "und", 1680, 49, "Instalaciones mecánicas y HVAC"],
  ["MAT-COND24", "mat", "MAT-957", "Unidad condensadora 24 000 BTU", "und", 2250, 49, "Instalaciones mecánicas y HVAC"],
  ["MAT-COND36", "mat", "MAT-958", "Unidad condensadora 36 000 BTU", "und", 3450, 49, "Instalaciones mecánicas y HVAC"],
  ["MAT-EVAP12", "mat", "MAT-959", "Evaporadora / fan coil 12 000 BTU", "und", 780, 49, "Instalaciones mecánicas y HVAC"],
  ["MAT-EVAP18", "mat", "MAT-960", "Evaporadora / fan coil 18 000 BTU", "und", 980, 49, "Instalaciones mecánicas y HVAC"],
  ["MAT-EVAP24", "mat", "MAT-961", "Evaporadora / fan coil 24 000 BTU", "und", 1280, 49, "Instalaciones mecánicas y HVAC"],
  ["MAT-CASS18", "mat", "MAT-962", "Split cassette 18 000 BTU", "und", 2850, 49, "Instalaciones mecánicas y HVAC"],
  ["MAT-CASS24", "mat", "MAT-963", "Split cassette 24 000 BTU", "und", 3650, 49, "Instalaciones mecánicas y HVAC"],
  ["MAT-PISO18", "mat", "MAT-964", "Equipo piso-techo 18 000 BTU", "und", 2650, 49, "Instalaciones mecánicas y HVAC"],
  ["MAT-VRF", "mat", "MAT-965", "Unidad exterior VRF/VRV (no detallado)", "und", 12500, 49, "Insumos no detallados"],
  ["MAT-DUCTGI", "mat", "MAT-966", "Ducto de chapa GI e=0.6 mm", "m²", 85, 61, "Instalaciones mecánicas y HVAC"],
  ["MAT-DUCTFL", "mat", "MAT-967", "Ducto flexible aislado Ø200 mm", "m", 38, 60, "Instalaciones mecánicas y HVAC"],
  ["MAT-REJIMP", "mat", "MAT-968", "Rejilla de impulsión 300×150 mm", "und", 65, 39, "Instalaciones mecánicas y HVAC"],
  ["MAT-REJRET", "mat", "MAT-969", "Rejilla de retorno 400×200 mm", "und", 78, 39, "Instalaciones mecánicas y HVAC"],
  ["MAT-DIFUS", "mat", "MAT-970", "Difusor de techo 300×300 mm", "und", 95, 39, "Instalaciones mecánicas y HVAC"],
  ["MAT-AISLEL", "mat", "MAT-971", "Aislamiento elastomérico e=13 mm", "m", 14, 60, "Instalaciones mecánicas y HVAC"],
  ["MAT-R410", "mat", "MAT-972", "Refrigerante R-410A", "kg", 85, 39, "Instalaciones mecánicas y HVAC"],
  ["MAT-R32", "mat", "MAT-973", "Refrigerante R-32", "kg", 92, 39, "Instalaciones mecánicas y HVAC"],
  ["MAT-CU14", "mat", "MAT-974", "Tubería de cobre refrigeración Ø¼\"", "m", 18, 68, "Instalaciones mecánicas y HVAC"],
  ["MAT-CU38R", "mat", "MAT-975", "Tubería de cobre refrigeración Ø⅜\"", "m", 24, 68, "Instalaciones mecánicas y HVAC"],
  ["MAT-CU12R", "mat", "MAT-976", "Tubería de cobre refrigeración Ø½\"", "m", 32, 68, "Instalaciones mecánicas y HVAC"],
  ["MAT-CU58", "mat", "MAT-977", "Tubería de cobre refrigeración Ø⅝\"", "m", 42, 68, "Instalaciones mecánicas y HVAC"],
  ["MAT-DESCOND", "mat", "MAT-978", "Tubería desagüe de condensado Ø20 mm", "m", 4.5, 72, "Instalaciones mecánicas y HVAC"],
  ["MAT-SOPCOND", "mat", "MAT-979", "Soporte / ménsula de condensadora", "und", 85, 51, "Instalaciones mecánicas y HVAC"],
  ["MAT-CABLEAA", "mat", "MAT-980", "Cable de interconexión A/A 4×1.5 mm²", "m", 4.8, 7, "Instalaciones mecánicas y HVAC"],
  ["MAT-EXT200", "mat", "MAT-981", "Extractor de aire Ø200 mm", "und", 245, 48, "Instalaciones mecánicas y HVAC"],
  ["MAT-EXT300", "mat", "MAT-982", "Extractor de aire Ø300 mm", "und", 380, 48, "Instalaciones mecánicas y HVAC"],
  ["MAT-EXTHEL", "mat", "MAT-983", "Extractor helicoidal mural 1 200 m³/h", "und", 680, 48, "Instalaciones mecánicas y HVAC"],
  ["MAT-EXTCEN", "mat", "MAT-984", "Extractor centrífugo 2 000 m³/h", "und", 1450, 48, "Instalaciones mecánicas y HVAC"],
  ["MAT-CAMPANA", "mat", "MAT-985", "Campana extractora de cocina 90 cm", "und", 420, 48, "Instalaciones mecánicas y HVAC"],
  ["MAT-ND-EXT", "mat", "MAT-986", "Sistema de extracción (no detallado)", "glb", 1850, 49, "Insumos no detallados"],

  // —— Gas natural / GLP ——
  ["MAT-TUBGAS", "mat", "MAT-987", "Tubería de acero para gas Ø½\"", "m", 18, 65, "Instalaciones mecánicas y HVAC"],
  ["MAT-TUBGASC", "mat", "MAT-988", "Tubería de cobre para gas Ø½\"", "m", 32, 68, "Instalaciones mecánicas y HVAC"],
  ["MAT-REGGAS", "mat", "MAT-989", "Regulador de gas 2 etapas", "und", 95, 77, "Instalaciones mecánicas y HVAC"],
  ["MAT-MEDGAS", "mat", "MAT-990", "Medidor de gas residencial", "und", 280, 39, "Instalaciones mecánicas y HVAC"],
  ["MAT-LLGAS", "mat", "MAT-991", "Llave de paso de gas ½\"", "und", 42, 77, "Instalaciones mecánicas y HVAC"],
  ["MAT-FLEXGAS", "mat", "MAT-992", "Flexible de gas para cocina", "und", 28, 77, "Instalaciones mecánicas y HVAC"],
  ["MAT-ND-GAS", "mat", "MAT-993", "Instalación de gas (no detallada)", "pnto", 185, 39, "Insumos no detallados"],

  // —— Equipos de instalación ——
  ["EQ-VAC", "eq", "EQ-051", "Bomba de vacío HVAC", "hm", 18, 48, "Equipos y herramientas"],
  ["EQ-MANIF", "eq", "EQ-052", "Manifold / manómetros de refrigeración", "día", 22, 37, "Equipos y herramientas"],
  ["EQ-DOBCU", "eq", "EQ-053", "Dobladora de tubos de cobre", "día", 16, 37, "Equipos y herramientas"],
  ["EQ-TERRA", "eq", "EQ-054", "Terraja / roscadora de tubos", "hm", 14, 37, "Equipos y herramientas"],
  ["EQ-SOPL", "eq", "EQ-055", "Sopladora / pescador de cables", "día", 12, 37, "Equipos y herramientas"],
  ["EQ-MEG", "eq", "EQ-056", "Megóhmetro / telurometro", "día", 35, 49, "Equipos y herramientas"],
  ["EQ-MULT", "eq", "EQ-057", "Multímetro / pinza amperimétrica", "día", 8, 37, "Equipos y herramientas"],
];

export const INSUMOS_INSTALACIONES: Insumo[] = RAW.map((row) => i(...row));
