import type { Partida } from "./types";
import { p, r } from "./partidaBuilder";

/** IEM: planta electromecánica. Distinto de IE (salidas/luminarias) e IM (bombeo, CI, HVAC). */
export const PARTIDAS_ELECTROMECANICAS: Partida[] = [
  p("electromecanicas", "00 Trabajos preliminares", "IEM-00.01.01", "Trazo y replanteo de instalaciones electromecánicas", "m²", r(["MO-TOPO", 0.01], ["MO-TEC", 0.02], ["MO-PEO", 0.03], ["MAT-CALR", 0.05], ["EQ-NIV", 0.005], ["EQ-HIN", 4])),

  p("electromecanicas", "01 Subestación y transformación", "IEM-01.01.01", "Local / caseta de subestación (suministro e instalación de equipos de sala)", "glb", r(["MO-TEC", 24], ["MO-ELE", 16], ["MO-MEC", 12], ["EQ-HIN", 3])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.02.01", "Suministro e instalación de transformador seco 100 kVA", "und", r(["MO-TEC", 16], ["MO-ELE", 10], ["MO-MEC", 8], ["MAT-TRAFO100", 1], ["EQ-GRU", 4], ["EQ-HIN", 3])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.02.02", "Suministro e instalación de transformador seco 250 kVA", "und", r(["MO-TEC", 20], ["MO-ELE", 12], ["MO-MEC", 10], ["MAT-TRAFO250", 1], ["EQ-GRU", 6], ["EQ-HIN", 3])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.02.03", "Suministro e instalación de transformador seco 500 kVA", "und", r(["MO-TEC", 28], ["MO-ELE", 16], ["MO-MEC", 12], ["MAT-TRAFO500", 1], ["EQ-GRU", 8], ["EQ-HIN", 3])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.02.04", "Suministro e instalación de transformador seco 750 kVA", "und", r(["MO-TEC", 36], ["MO-ELE", 20], ["MO-MEC", 14], ["MAT-TRAFO750", 1], ["EQ-GRU", 10], ["EQ-HIN", 3])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.02.05", "Suministro e instalación de transformador en aceite 160 kVA", "und", r(["MO-TEC", 18], ["MO-ELE", 12], ["MO-MEC", 10], ["MAT-TRAFOA160", 1], ["EQ-GRU", 6], ["EQ-HIN", 3])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.02.06", "Suministro e instalación de transformador en aceite 400 kVA", "und", r(["MO-TEC", 26], ["MO-ELE", 16], ["MO-MEC", 12], ["MAT-TRAFOA400", 1], ["EQ-GRU", 8], ["EQ-HIN", 3])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.02.07", "Suministro e instalación de transformador en aceite 630 kVA", "und", r(["MO-TEC", 32], ["MO-ELE", 18], ["MO-MEC", 14], ["MAT-TRAFOA630", 1], ["EQ-GRU", 10], ["EQ-HIN", 3])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.03.01", "Celda de media tensión 13.2 kV suministro e instalación", "und", r(["MO-TEC", 20], ["MO-ELE", 12], ["MAT-CELDA13", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.03.02", "Interruptor de potencia de media tensión", "und", r(["MO-TEC", 16], ["MO-ELE", 10], ["MAT-INTMT", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.04.01", "Tablero general de baja tensión TGBT de planta", "und", r(["MO-TEC", 24], ["MO-ELE", 16], ["MAT-TGBTIEM", 1], ["EQ-HIN", 4])),

  p("electromecanicas", "02 Tableros de potencia y MCC", "IEM-02.01.01", "Centro de control de motores MCC 6 arrancadores", "und", r(["MO-TEC", 28], ["MO-ELE", 16], ["MAT-MCC6", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "02 Tableros de potencia y MCC", "IEM-02.01.02", "Centro de control de motores MCC 12 arrancadores", "und", r(["MO-TEC", 40], ["MO-ELE", 22], ["MAT-MCC12", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "02 Tableros de potencia y MCC", "IEM-02.02.01", "Tablero de control de procesos / automatismo", "und", r(["MO-TEC", 18], ["MO-ELE", 10], ["MAT-TABPROC", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "02 Tableros de potencia y MCC", "IEM-02.03.01", "Variador de frecuencia 10 HP suministro e instalación", "und", r(["MO-TEC", 8], ["MO-ELE", 5], ["MAT-VFD10", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "02 Tableros de potencia y MCC", "IEM-02.03.02", "Variador de frecuencia 25 HP suministro e instalación", "und", r(["MO-TEC", 10], ["MO-ELE", 6], ["MAT-VFD25", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "02 Tableros de potencia y MCC", "IEM-02.03.03", "Variador de frecuencia 50 HP suministro e instalación", "und", r(["MO-TEC", 14], ["MO-ELE", 8], ["MAT-VFD50", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "02 Tableros de potencia y MCC", "IEM-02.04.01", "Arrancador estrella-triángulo 15 HP", "und", r(["MO-TEC", 6], ["MO-ELE", 4], ["MAT-ARRAN15", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "02 Tableros de potencia y MCC", "IEM-02.04.02", "Arrancador suave (soft starter) 40 HP", "und", r(["MO-TEC", 8], ["MO-ELE", 5], ["MAT-SOFT40", 1], ["EQ-HIN", 4])),

  p("electromecanicas", "03 Transferencia automática ATS", "IEM-03.01.01", "Suministro e instalación de ATS 100 A 3P+N transición abierta", "und", r(["MO-TEC", 12], ["MO-ELE", 8], ["MO-AYU", 6], ["MAT-ATS100", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "03 Transferencia automática ATS", "IEM-03.01.02", "Suministro e instalación de ATS 160 A 3P+N transición abierta", "und", r(["MO-TEC", 14], ["MO-ELE", 9], ["MO-AYU", 7], ["MAT-ATS160", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "03 Transferencia automática ATS", "IEM-03.01.03", "Suministro e instalación de ATS 250 A 3P+N transición abierta", "und", r(["MO-TEC", 16], ["MO-ELE", 10], ["MO-AYU", 8], ["MAT-ATS250", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "03 Transferencia automática ATS", "IEM-03.01.04", "Suministro e instalación de ATS 400 A 3P+N transición abierta", "und", r(["MO-TEC", 20], ["MO-ELE", 12], ["MO-AYU", 10], ["MAT-ATS400", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "03 Transferencia automática ATS", "IEM-03.01.05", "Suministro e instalación de ATS 630 A 3P+N transición abierta", "und", r(["MO-TEC", 24], ["MO-ELE", 14], ["MO-AYU", 12], ["MAT-ATS630", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "03 Transferencia automática ATS", "IEM-03.02.01", "Suministro e instalación de ATS 800 A 3P+N transición cerrada", "und", r(["MO-TEC", 32], ["MO-ELE", 18], ["MO-AYU", 14], ["MAT-ATS800", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "03 Transferencia automática ATS", "IEM-03.02.02", "Suministro e instalación de ATS 1 000 A 3P+N con bypass", "und", r(["MO-TEC", 40], ["MO-ELE", 22], ["MO-AYU", 16], ["MAT-ATS1000", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "03 Transferencia automática ATS", "IEM-03.02.03", "Suministro e instalación de ATS 1 600 A 3P+N con bypass", "und", r(["MO-TEC", 48], ["MO-ELE", 26], ["MO-AYU", 20], ["MAT-ATS1600", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "03 Transferencia automática ATS", "IEM-03.03.01", "Tablero de transferencia manual 3P+N", "und", r(["MO-TEC", 10], ["MO-ELE", 6], ["MAT-TAB18", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "03 Transferencia automática ATS", "IEM-03.04.01", "Bypass de ATS / seccionador de mantenimiento", "und", r(["MO-TEC", 8], ["MO-ELE", 5], ["MAT-BYPASSATS", 1], ["EQ-HIN", 4])),

  p("electromecanicas", "04 Grupo electrógeno", "IEM-04.01.01", "Suministro e instalación de grupo electrógeno diésel 30 kVA cabinado", "und", r(["MO-GE", 24], ["MO-TEC", 16], ["MO-ELE", 12], ["MAT-GE30", 1], ["MAT-ESCGE", 1], ["EQ-GRU", 4], ["EQ-HIN", 3])),
  p("electromecanicas", "04 Grupo electrógeno", "IEM-04.01.02", "Suministro e instalación de grupo electrógeno diésel 50 kVA cabinado", "und", r(["MO-GE", 28], ["MO-TEC", 18], ["MO-ELE", 14], ["MAT-GE50", 1], ["MAT-ESCGE", 1], ["EQ-GRU", 4], ["EQ-HIN", 3])),
  p("electromecanicas", "04 Grupo electrógeno", "IEM-04.01.03", "Suministro e instalación de grupo electrógeno diésel 80 kVA cabinado", "und", r(["MO-GE", 32], ["MO-TEC", 20], ["MO-ELE", 16], ["MAT-GE80", 1], ["MAT-ESCGE", 1], ["EQ-GRU", 6], ["EQ-HIN", 3])),
  p("electromecanicas", "04 Grupo electrógeno", "IEM-04.01.04", "Suministro e instalación de grupo electrógeno diésel 100 kVA cabinado", "und", r(["MO-GE", 36], ["MO-TEC", 22], ["MO-ELE", 16], ["MAT-GE100", 1], ["MAT-ESCGE", 1], ["MAT-TANQGE", 1], ["EQ-GRU", 6], ["EQ-HIN", 3])),
  p("electromecanicas", "04 Grupo electrógeno", "IEM-04.01.05", "Suministro e instalación de grupo electrógeno diésel 150 kVA cabinado", "und", r(["MO-GE", 40], ["MO-TEC", 24], ["MO-ELE", 18], ["MAT-GE150", 1], ["MAT-ESCGE", 1], ["MAT-TANQGE", 1], ["EQ-GRU", 8], ["EQ-HIN", 3])),
  p("electromecanicas", "04 Grupo electrógeno", "IEM-04.01.06", "Suministro e instalación de grupo electrógeno diésel 250 kVA cabinado", "und", r(["MO-GE", 48], ["MO-TEC", 28], ["MO-ELE", 20], ["MAT-GE250", 1], ["MAT-ESCGE", 1], ["MAT-TANQGE", 1], ["EQ-GRU", 10], ["EQ-HIN", 3])),
  p("electromecanicas", "04 Grupo electrógeno", "IEM-04.01.07", "Suministro e instalación de grupo electrógeno diésel 350 kVA cabinado", "und", r(["MO-GE", 56], ["MO-TEC", 32], ["MO-ELE", 22], ["MAT-GE350", 1], ["MAT-ESCGE", 1], ["MAT-TANQGE", 1], ["EQ-GRU", 12], ["EQ-HIN", 3])),
  p("electromecanicas", "04 Grupo electrógeno", "IEM-04.01.08", "Suministro e instalación de grupo electrógeno diésel 500 kVA cabinado", "und", r(["MO-GE", 64], ["MO-TEC", 36], ["MO-ELE", 24], ["MAT-GE500", 1], ["MAT-ESCGE", 1], ["MAT-TANQGE", 1], ["EQ-GRU", 16], ["EQ-HIN", 3])),
  p("electromecanicas", "04 Grupo electrógeno", "IEM-04.02.01", "Losa de fundación para grupo electrógeno f'c 210", "m³", r(["MO-OPE", 3.2], ["MO-PEO", 3.8], ["MO-FIE", 0.8], ["MAT-CEM", 8.4], ["MAT-ARE", 0.52], ["MAT-PIE", 0.92], ["MAT-FY42", 90], ["EQ-MEZ", 0.55], ["EQ-HIN", 5])),
  p("electromecanicas", "04 Grupo electrógeno", "IEM-04.02.02", "Tanque de combustible diario 1 000 L c/cubeto", "und", r(["MO-GE", 8], ["MO-MEC", 6], ["MAT-TANQGE", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "04 Grupo electrógeno", "IEM-04.03.01", "Escape, silenciador y descarga de gases del grupo", "und", r(["MO-GE", 10], ["MO-MEC", 6], ["MAT-ESCGE", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "04 Grupo electrógeno", "IEM-04.03.02", "Banco de baterías de arranque del grupo", "und", r(["MO-GE", 4], ["MO-ELE", 3], ["MAT-BATGE", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "04 Grupo electrógeno", "IEM-04.03.03", "Interconexión de potencia grupo–ATS", "glb", r(["MO-TEC", 12], ["MO-ELE", 8], ["MAT-INTERGE", 1], ["EQ-HIN", 4])),

  p("electromecanicas", "05 UPS y respaldo", "IEM-05.01.01", "Suministro e instalación de UPS online 10 kVA", "und", r(["MO-TEC", 12], ["MO-ELE", 8], ["MAT-UPS10", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "05 UPS y respaldo", "IEM-05.01.02", "Suministro e instalación de UPS online 20 kVA", "und", r(["MO-TEC", 16], ["MO-ELE", 10], ["MAT-UPS20", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "05 UPS y respaldo", "IEM-05.01.03", "Suministro e instalación de UPS online 60 kVA", "und", r(["MO-TEC", 24], ["MO-ELE", 14], ["MAT-UPS60", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "05 UPS y respaldo", "IEM-05.01.04", "Suministro e instalación de UPS online 100 kVA", "und", r(["MO-TEC", 32], ["MO-ELE", 18], ["MAT-UPS100", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "05 UPS y respaldo", "IEM-05.02.01", "Banco de baterías para UPS", "und", r(["MO-TEC", 8], ["MO-ELE", 6], ["MAT-BATUPS", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "05 UPS y respaldo", "IEM-05.03.01", "Tablero de by-pass de UPS", "und", r(["MO-TEC", 8], ["MO-ELE", 5], ["MAT-BYPASSATS", 1], ["EQ-HIN", 4])),

  p("electromecanicas", "06 Motores y accionamientos", "IEM-06.01.01", "Suministro e instalación de motor trifásico 5 HP", "und", r(["MO-MEC", 6], ["MO-ELE", 4], ["MAT-MOT5", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "06 Motores y accionamientos", "IEM-06.01.02", "Suministro e instalación de motor trifásico 10 HP", "und", r(["MO-MEC", 8], ["MO-ELE", 5], ["MAT-MOT10", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "06 Motores y accionamientos", "IEM-06.01.03", "Suministro e instalación de motor trifásico 25 HP", "und", r(["MO-MEC", 12], ["MO-ELE", 6], ["MAT-MOT25", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "06 Motores y accionamientos", "IEM-06.01.04", "Suministro e instalación de motor trifásico 50 HP", "und", r(["MO-MEC", 16], ["MO-ELE", 8], ["MAT-MOT50", 1], ["EQ-GRU", 2], ["EQ-HIN", 4])),
  p("electromecanicas", "06 Motores y accionamientos", "IEM-06.01.05", "Suministro e instalación de motor trifásico 100 HP", "und", r(["MO-MEC", 22], ["MO-ELE", 10], ["MAT-MOT100", 1], ["EQ-GRU", 4], ["EQ-HIN", 4])),
  p("electromecanicas", "06 Motores y accionamientos", "IEM-06.02.01", "Bancada, alineamiento y acople de motor", "und", r(["MO-MEC", 8], ["MO-AYU", 6], ["MAT-BANCADA", 1], ["EQ-HIN", 4])),

  p("electromecanicas", "07 Izaje y transporte", "IEM-07.01.01", "Suministro e instalación de puente grúa 5 t", "und", r(["MO-MEC", 80], ["MO-TEC", 24], ["MO-ELE", 16], ["MAT-GRUA5", 1], ["EQ-GRU", 16], ["EQ-HIN", 3])),
  p("electromecanicas", "07 Izaje y transporte", "IEM-07.01.02", "Suministro e instalación de puente grúa 10 t", "und", r(["MO-MEC", 110], ["MO-TEC", 32], ["MO-ELE", 20], ["MAT-GRUA10", 1], ["EQ-GRU", 20], ["EQ-HIN", 3])),
  p("electromecanicas", "07 Izaje y transporte", "IEM-07.02.01", "Suministro e instalación de polipasto eléctrico 2 t", "und", r(["MO-MEC", 16], ["MO-ELE", 8], ["MAT-POLI2", 1], ["EQ-GRU", 4], ["EQ-HIN", 4])),
  p("electromecanicas", "07 Izaje y transporte", "IEM-07.03.01", "Suministro e instalación de montacargas de obra / servicio", "und", r(["MO-MEC", 40], ["MO-TEC", 16], ["MO-ELE", 12], ["MAT-MONTAC", 1], ["EQ-GRU", 8], ["EQ-HIN", 3])),

  p("electromecanicas", "08 Tierra y protecciones de planta", "IEM-08.01.01", "Malla de tierra de subestación", "m²", r(["MO-ELE", 0.35], ["MO-PEO", 0.4], ["MAT-MALLAT", 1.05], ["EQ-HIN", 4])),
  p("electromecanicas", "08 Tierra y protecciones de planta", "IEM-08.01.02", "Pozo a tierra de potencia", "und", r(["MO-ELE", 8], ["MO-PEO", 10], ["MAT-POZOP", 1], ["EQ-HIN", 5])),
  p("electromecanicas", "08 Tierra y protecciones de planta", "IEM-08.02.01", "Pararrayos / DPS de media tensión", "und", r(["MO-TEC", 6], ["MO-ELE", 4], ["MAT-DPSMT", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "08 Tierra y protecciones de planta", "IEM-08.03.01", "Equipotencialización de sala técnica", "glb", r(["MO-ELE", 12], ["MO-AYU", 8], ["MAT-EQUIPOT", 1], ["EQ-HIN", 4])),

  p("electromecanicas", "09 Canalizaciones de potencia", "IEM-09.01.01", "Bandeja portacable 200 mm suministro e instalación", "m", r(["MO-ELE", 0.45], ["MO-AYU", 0.35], ["MAT-BAND200", 1.05], ["EQ-HIN", 4])),
  p("electromecanicas", "09 Canalizaciones de potencia", "IEM-09.01.02", "Bandeja portacable 300 mm suministro e instalación", "m", r(["MO-ELE", 0.55], ["MO-AYU", 0.4], ["MAT-BAND300", 1.05], ["EQ-HIN", 4])),
  p("electromecanicas", "09 Canalizaciones de potencia", "IEM-09.01.03", "Bandeja portacable 400 mm suministro e instalación", "m", r(["MO-ELE", 0.65], ["MO-AYU", 0.48], ["MAT-BAND400", 1.05], ["EQ-HIN", 4])),
  p("electromecanicas", "09 Canalizaciones de potencia", "IEM-09.02.01", "Canalización EMT Ø1½\" para potencia", "m", r(["MO-ELE", 0.28], ["MO-AYU", 0.2], ["MAT-EMT15", 1.05], ["EQ-HIN", 4])),
  p("electromecanicas", "09 Canalizaciones de potencia", "IEM-09.03.01", "Cable NYY 3×70+35 mm² suministro e instalación", "m", r(["MO-ELE", 0.22], ["MO-AYU", 0.16], ["MAT-NYY70", 1.05], ["EQ-HIN", 3])),
  p("electromecanicas", "09 Canalizaciones de potencia", "IEM-09.03.02", "Cable NYY 3×120+70 mm² suministro e instalación", "m", r(["MO-ELE", 0.28], ["MO-AYU", 0.2], ["MAT-NYY120", 1.05], ["EQ-HIN", 3])),
  p("electromecanicas", "09 Canalizaciones de potencia", "IEM-09.03.03", "Cable NYY 3×185+95 mm² suministro e instalación", "m", r(["MO-ELE", 0.34], ["MO-AYU", 0.24], ["MAT-NYY185", 1.05], ["EQ-HIN", 3])),
  p("electromecanicas", "09 Canalizaciones de potencia", "IEM-09.03.04", "Cable N2XSY 12/20 kV 3×70 mm² (media tensión)", "m", r(["MO-TEC", 0.45], ["MO-ELE", 0.3], ["MAT-N2XSY70", 1.05], ["EQ-HIN", 3])),

  p("electromecanicas", "10 Pruebas y puesta en marcha", "IEM-10.01.01", "Pruebas de aislamiento y continuidad de planta", "glb", r(["MO-TEC", 16], ["MO-ELE", 10], ["EQ-HIN", 3])),
  p("electromecanicas", "10 Pruebas y puesta en marcha", "IEM-10.01.02", "Protocolo de puesta en marcha de grupo y ATS", "glb", r(["MO-GE", 12], ["MO-TEC", 8], ["EQ-HIN", 3])),
  p("electromecanicas", "10 Pruebas y puesta en marcha", "IEM-10.01.03", "Termografía de tableros de potencia", "glb", r(["MO-TEC", 8], ["EQ-HIN", 3])),
];
