import type { Partida } from "./types";
import { p, r } from "./partidaBuilder";

export const PARTIDAS_CATALOGO_DETALLE: Partida[] = [
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.02.08", "Suministro e instalación de transformador seco 160 kVA", "und", r(["MO-TEC", 18], ["MO-ELE", 11], ["MO-MEC", 9], ["MAT-TRAFO160S", 1], ["EQ-GRU", 5], ["EQ-HIN", 3])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.02.09", "Suministro e instalación de transformador en aceite 1 000 kVA", "und", r(["MO-TEC", 40], ["MO-ELE", 22], ["MO-MEC", 16], ["MAT-TRAFO1000A", 1], ["EQ-GRU", 14], ["EQ-HIN", 3])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.03.03", "Celda de media tensión 22.9 kV suministro e instalación", "und", r(["MO-TEC", 24], ["MO-ELE", 14], ["MAT-CELDA22", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.05.01", "Banco de condensadores 50 kVAR suministro e instalación", "und", r(["MO-TEC", 8], ["MO-ELE", 5], ["MAT-CAP50", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.05.02", "Banco de condensadores 100 kVAR suministro e instalación", "und", r(["MO-TEC", 10], ["MO-ELE", 6], ["MAT-CAP100", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.06.01", "Transformador de corriente 400/5 A", "und", r(["MO-TEC", 3], ["MO-ELE", 2], ["MAT-TC400", 1], ["EQ-HIN", 3])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.06.02", "Transformador de potencial 13.2 kV", "und", r(["MO-TEC", 6], ["MO-ELE", 4], ["MAT-TP13", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.06.03", "Relé de protección multifunción", "und", r(["MO-TEC", 8], ["MO-ELE", 4], ["MAT-RELE67", 1], ["EQ-HIN", 3])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.07.01", "Barra de cobre electrolítico 80×10 mm", "m", r(["MO-ELE", 0.55], ["MO-AYU", 0.35], ["MAT-BARCU", 1.05], ["EQ-HIN", 4])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.08.01", "Fosa / cubeto de contención de aceite de transformador", "und", r(["MO-OPE", 12], ["MO-PEO", 16], ["MAT-FOSACE", 1], ["EQ-HIN", 5])),

  p("electromecanicas", "02 Tableros de potencia y MCC", "IEM-02.01.03", "Centro de control de motores MCC 18 arrancadores", "und", r(["MO-TEC", 52], ["MO-ELE", 28], ["MAT-MCC18", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "02 Tableros de potencia y MCC", "IEM-02.03.04", "Variador de frecuencia 75 HP suministro e instalación", "und", r(["MO-TEC", 16], ["MO-ELE", 10], ["MAT-VFD75", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "02 Tableros de potencia y MCC", "IEM-02.05.01", "Interruptor caja moldeada 250 A 3P instalado", "und", r(["MO-TEC", 2.5], ["MO-ELE", 1.5], ["MAT-MCCB250", 1], ["EQ-HIN", 3])),
  p("electromecanicas", "02 Tableros de potencia y MCC", "IEM-02.05.02", "Interruptor caja moldeada 400 A 3P instalado", "und", r(["MO-TEC", 3], ["MO-ELE", 2], ["MAT-MCCB400", 1], ["EQ-HIN", 3])),
  p("electromecanicas", "02 Tableros de potencia y MCC", "IEM-02.05.03", "Interruptor caja moldeada 630 A 3P instalado", "und", r(["MO-TEC", 4], ["MO-ELE", 2.5], ["MAT-MCCB630", 1], ["EQ-HIN", 3])),
  p("electromecanicas", "02 Tableros de potencia y MCC", "IEM-02.06.01", "PLC / automatismo de planta suministro e instalación", "und", r(["MO-TEC", 20], ["MO-ELE", 10], ["MAT-PLC", 1], ["EQ-HIN", 3])),

  p("electromecanicas", "03 Transferencia automática ATS", "IEM-03.05.01", "Tablero de sincronismo de grupos electrógenos", "und", r(["MO-TEC", 28], ["MO-ELE", 16], ["MO-GE", 10], ["MAT-SINC", 1], ["EQ-HIN", 4])),

  p("electromecanicas", "04 Grupo electrógeno", "IEM-04.01.09", "Suministro e instalación de grupo electrógeno diésel 20 kVA cabinado", "und", r(["MO-GE", 20], ["MO-TEC", 14], ["MO-ELE", 10], ["MAT-GE20", 1], ["MAT-ESCGE", 1], ["EQ-GRU", 3], ["EQ-HIN", 3])),
  p("electromecanicas", "04 Grupo electrógeno", "IEM-04.01.10", "Suministro e instalación de grupo electrógeno diésel 600 kVA cabinado", "und", r(["MO-GE", 72], ["MO-TEC", 40], ["MO-ELE", 26], ["MAT-GE600", 1], ["MAT-ESCGE", 1], ["MAT-TANQGE", 1], ["EQ-GRU", 18], ["EQ-HIN", 3])),
  p("electromecanicas", "04 Grupo electrógeno", "IEM-04.01.11", "Suministro e instalación de grupo electrógeno diésel 800 kVA cabinado", "und", r(["MO-GE", 84], ["MO-TEC", 46], ["MO-ELE", 30], ["MAT-GE800", 1], ["MAT-ESCGE", 1], ["MAT-TANQGE", 1], ["EQ-GRU", 22], ["EQ-HIN", 3])),

  p("electromecanicas", "09 Canalizaciones de potencia", "IEM-09.01.04", "Bandeja portacable 100 mm suministro e instalación", "m", r(["MO-ELE", 0.35], ["MO-AYU", 0.28], ["MAT-BAND100", 1.05], ["EQ-HIN", 4])),
  p("electromecanicas", "09 Canalizaciones de potencia", "IEM-09.01.05", "Bandeja portacable 600 mm suministro e instalación", "m", r(["MO-ELE", 0.85], ["MO-AYU", 0.6], ["MAT-BAND600", 1.05], ["EQ-HIN", 4])),
  p("electromecanicas", "09 Canalizaciones de potencia", "IEM-09.02.02", "Canalización IMC Ø2\" para potencia", "m", r(["MO-ELE", 0.32], ["MO-AYU", 0.22], ["MAT-IMC2", 1.05], ["EQ-HIN", 4])),
  p("electromecanicas", "09 Canalizaciones de potencia", "IEM-09.03.05", "Cable NYY 3×25+16 mm² suministro e instalación", "m", r(["MO-ELE", 0.16], ["MO-AYU", 0.12], ["MAT-NYY25", 1.05], ["EQ-HIN", 3])),
  p("electromecanicas", "09 Canalizaciones de potencia", "IEM-09.03.06", "Cable NYY 3×50+25 mm² suministro e instalación", "m", r(["MO-ELE", 0.2], ["MO-AYU", 0.14], ["MAT-NYY50", 1.05], ["EQ-HIN", 3])),
  p("electromecanicas", "09 Canalizaciones de potencia", "IEM-09.03.07", "Cable NYY 3×240+120 mm² suministro e instalación", "m", r(["MO-ELE", 0.4], ["MO-AYU", 0.28], ["MAT-NYY240", 1.05], ["EQ-HIN", 3])),
  p("electromecanicas", "09 Canalizaciones de potencia", "IEM-09.03.08", "Cable N2XOH 0.6/1 kV 3×70+35 mm² (no propagante)", "m", r(["MO-ELE", 0.24], ["MO-AYU", 0.18], ["MAT-N2XOH70", 1.05], ["EQ-HIN", 3])),
  p("electromecanicas", "09 Canalizaciones de potencia", "IEM-09.03.09", "Cable N2XSY 12/20 kV 3×95 mm² (media tensión)", "m", r(["MO-TEC", 0.52], ["MO-ELE", 0.35], ["MAT-N2XSY95", 1.05], ["EQ-HIN", 3])),

  p("electromecanicas", "11 Generación fotovoltaica", "IEM-11.01.01", "Suministro e instalación de sistema fotovoltaico 10 kWp", "und", r(["MO-TEC", 40], ["MO-ELE", 24], ["MO-PEO", 16], ["MAT-FV10", 1], ["EQ-GRU", 6], ["EQ-HIN", 3])),

  p("electromecanicas", "10 Pruebas y puesta en marcha", "IEM-10.01.04", "Prueba hipot / aislamiento de media tensión", "glb", r(["MO-TEC", 20], ["MO-ELE", 12], ["EQ-HIN", 3])),
  p("electromecanicas", "10 Pruebas y puesta en marcha", "IEM-10.01.05", "Protocolo de factor de potencia y armónicos", "glb", r(["MO-TEC", 10], ["EQ-HIN", 3])),

  p("comunicaciones", "01 Salidas de señal", "COM-01.02.02", "Cable UTP Cat 6 en canalización existente", "m", r(["MO-TEL", 0.06], ["MO-AYU", 0.04], ["MAT-UTP", 1.05], ["EQ-HIN", 3])),
  p("comunicaciones", "01 Salidas de señal", "COM-01.02.03", "Cable UTP Cat 6A en canalización existente", "m", r(["MO-TEL", 0.065], ["MO-AYU", 0.045], ["MAT-UTP6A", 1.05], ["EQ-HIN", 3])),
  p("comunicaciones", "01 Salidas de señal", "COM-01.03.01", "Canalización PVC-P Ø20 mm para data / TV", "m", r(["MO-TEL", 0.14], ["MO-AYU", 0.12], ["MAT-PVC20COM", 1.05], ["EQ-HIN", 4])),

  p("comunicaciones", "09 Fibra óptica", "COM-09.01.01", "Cable de fibra óptica 6 hilos (backbone)", "m", r(["MO-TEL", 0.12], ["MO-AYU", 0.08], ["MAT-FO6", 1.05], ["EQ-HIN", 3])),
  p("comunicaciones", "09 Fibra óptica", "COM-09.01.02", "Cable de fibra óptica 12 hilos (backbone)", "m", r(["MO-TEL", 0.14], ["MO-AYU", 0.09], ["MAT-FO12", 1.05], ["EQ-HIN", 3])),
  p("comunicaciones", "09 Fibra óptica", "COM-09.02.01", "Caja de empalme / splitter óptico", "und", r(["MO-TEL", 3], ["MO-AYU", 2], ["MAT-SPLITFO", 1], ["EQ-HIN", 3])),
  p("comunicaciones", "09 Fibra óptica", "COM-09.03.01", "ONT / ONU de abonado suministro e instalación", "und", r(["MO-TEL", 1.5], ["MO-AYU", 1], ["MAT-ONT", 1], ["EQ-HIN", 3])),

  p("comunicaciones", "03 Cuarto de comunicaciones", "COM-03.01.02", "Rack 42 U de piso + organización", "und", r(["MO-TEL", 8], ["MO-AYU", 6], ["MAT-RACK42", 1], ["EQ-HIN", 4])),
  p("comunicaciones", "03 Cuarto de comunicaciones", "COM-03.04.01", "Patch panel 24 puertos Cat 6", "und", r(["MO-TEL", 2.5], ["MO-AYU", 1.5], ["MAT-PATCH24", 1], ["EQ-HIN", 3])),
  p("comunicaciones", "03 Cuarto de comunicaciones", "COM-03.05.01", "Patch panel 48 puertos Cat 6", "und", r(["MO-TEL", 3.5], ["MO-AYU", 2], ["MAT-PATCH48", 1], ["EQ-HIN", 3])),
  p("comunicaciones", "03 Cuarto de comunicaciones", "COM-03.06.01", "Switch PoE 24 puertos suministro e instalación", "und", r(["MO-TEL", 4], ["MO-AYU", 2], ["MAT-SWITCH24", 1], ["EQ-HIN", 3])),
  p("comunicaciones", "03 Cuarto de comunicaciones", "COM-03.07.01", "Access point Wi-Fi 6 suministro e instalación", "und", r(["MO-TEL", 2], ["MO-AYU", 1.2], ["MAT-APWIFI", 1], ["MAT-UTP", 12], ["EQ-HIN", 3])),

  p("comunicaciones", "04 CCTV y seguridad", "COM-04.01.03", "Cámara IP exterior IK10 suministro e instalación", "und", r(["MO-TEL", 3], ["MO-AYU", 2], ["MAT-CAMEXT", 1], ["MAT-UTP", 22], ["EQ-HIN", 3])),
  p("comunicaciones", "04 CCTV y seguridad", "COM-04.02.02", "NVR 16 canales + HDD", "und", r(["MO-TEL", 6], ["MO-AYU", 3], ["MAT-NVR16", 1], ["EQ-HIN", 3])),
  p("comunicaciones", "04 CCTV y seguridad", "COM-04.02.03", "NVR 32 canales + HDD", "und", r(["MO-TEL", 8], ["MO-AYU", 4], ["MAT-NVR32", 1], ["EQ-HIN", 3])),

  p("comunicaciones", "06 Control de acceso", "COM-06.01.01", "Controlador de acceso 2 puertas", "und", r(["MO-TEL", 5], ["MO-AYU", 3], ["MAT-CTRACC", 1], ["EQ-HIN", 3])),
  p("comunicaciones", "06 Control de acceso", "COM-06.02.01", "Lector biométrico / tarjeta", "und", r(["MO-TEL", 2], ["MO-AYU", 1.2], ["MAT-LECTBIO", 1], ["EQ-HIN", 3])),
  p("comunicaciones", "06 Control de acceso", "COM-06.03.01", "Cerradura electromagnética 600 lb", "und", r(["MO-TEL", 1.8], ["MO-AYU", 1.2], ["MAT-CERRACC", 1], ["EQ-HIN", 3])),
  p("comunicaciones", "02 Portería e intercomunicación", "COM-02.03.01", "Videoportero IP suministro e instalación", "und", r(["MO-TEL", 4], ["MO-AYU", 2.5], ["MAT-VIDINT", 1], ["MAT-UTP", 24], ["EQ-HIN", 3])),

  p("comunicaciones", "07 Alarma contra incendio", "COM-07.01.01", "Central de alarma contra incendio direccionable", "und", r(["MO-TEL", 12], ["MO-ELE", 6], ["MAT-CENTAL", 1], ["EQ-HIN", 3])),
  p("comunicaciones", "07 Alarma contra incendio", "COM-07.02.01", "Detector de humo direccionable", "und", r(["MO-TEL", 0.8], ["MO-AYU", 0.5], ["MAT-DETHUMO", 1], ["EQ-HIN", 3])),
  p("comunicaciones", "07 Alarma contra incendio", "COM-07.02.02", "Detector de calor direccionable", "und", r(["MO-TEL", 0.8], ["MO-AYU", 0.5], ["MAT-DETCAL", 1], ["EQ-HIN", 3])),
  p("comunicaciones", "07 Alarma contra incendio", "COM-07.03.01", "Estrobo / sirena de alarma", "und", r(["MO-TEL", 0.7], ["MO-AYU", 0.4], ["MAT-ESTROB", 1], ["EQ-HIN", 3])),
  p("comunicaciones", "07 Alarma contra incendio", "COM-07.04.01", "Estación manual de incendio", "und", r(["MO-TEL", 0.6], ["MO-AYU", 0.4], ["MAT-PULINC", 1], ["EQ-HIN", 3])),

  p("comunicaciones", "08 Perifoneo", "COM-08.01.01", "Amplificador de perifoneo 240 W", "und", r(["MO-TEL", 4], ["MO-ELE", 2], ["MAT-AMPPA", 1], ["EQ-HIN", 3])),
  p("comunicaciones", "08 Perifoneo", "COM-08.02.01", "Altavoz de perifoneo 10 W", "und", r(["MO-TEL", 1.2], ["MO-AYU", 0.8], ["MAT-PERIF", 1], ["EQ-HIN", 3])),

  p("estructuras", "04 Obras de concreto armado", "EST-04.01.17", "Concreto para vigas f'c=280 kg/cm²", "m³", r(["MO-OPE", 3.6], ["MO-PEO", 4.1], ["MAT-CEM", 10.2], ["MAT-ARE", 0.5], ["MAT-PIE", 0.9], ["MAT-AGU", 0.2], ["EQ-MEZ", 0.6], ["EQ-VIB", 0.48], ["EQ-HIN", 5])),
  p("estructuras", "04 Obras de concreto armado", "EST-04.01.18", "Concreto para columnas f'c=350 kg/cm²", "m³", r(["MO-OPE", 4], ["MO-PEO", 4.4], ["MAT-CEM", 12], ["MAT-ARE", 0.48], ["MAT-PIE", 0.88], ["MAT-AGU", 0.19], ["EQ-MEZ", 0.65], ["EQ-VIB", 0.55], ["EQ-HIN", 5])),
  p("estructuras", "04 Obras de concreto armado", "EST-04.01.19", "Concreto para placas y muros de corte f'c=280 kg/cm²", "m³", r(["MO-OPE", 3.7], ["MO-PEO", 4.2], ["MAT-CEM", 10.2], ["MAT-ARE", 0.5], ["MAT-PIE", 0.9], ["MAT-AGU", 0.2], ["EQ-MEZ", 0.6], ["EQ-VIB", 0.5], ["EQ-HIN", 5])),
  p("estructuras", "04 Obras de concreto armado", "EST-04.07.02", "Losa colaborante / metal deck e=0.75 mm + concreto", "m²", r(["MO-OPE", 0.35], ["MO-PEO", 0.4], ["MO-FIE", 0.12], ["MAT-MDECK", 1.05], ["MAT-CEM", 0.42], ["MAT-ARE", 0.03], ["EQ-HIN", 5])),
  p("estructuras", "05 Acero de refuerzo", "EST-05.01.01", "Acero fy 4200 Ø3/8\" cortado y colocado", "kg", r(["MO-FIE", 0.014], ["MO-PEO", 0.01], ["MAT-FY38", 1.05], ["EQ-HIN", 3])),
  p("estructuras", "05 Acero de refuerzo", "EST-05.01.02", "Acero fy 4200 Ø1/2\" cortado y colocado", "kg", r(["MO-FIE", 0.013], ["MO-PEO", 0.01], ["MAT-FY12P", 1.05], ["EQ-HIN", 3])),
  p("estructuras", "05 Acero de refuerzo", "EST-05.01.03", "Acero fy 4200 Ø5/8\" cortado y colocado", "kg", r(["MO-FIE", 0.012], ["MO-PEO", 0.009], ["MAT-FY58", 1.05], ["EQ-HIN", 3])),
  p("estructuras", "05 Acero de refuerzo", "EST-05.01.04", "Acero fy 4200 Ø3/4\" cortado y colocado", "kg", r(["MO-FIE", 0.011], ["MO-PEO", 0.009], ["MAT-FY34", 1.05], ["EQ-HIN", 3])),
  p("estructuras", "05 Acero de refuerzo", "EST-05.01.05", "Acero fy 4200 Ø1\" cortado y colocado", "kg", r(["MO-FIE", 0.01], ["MO-PEO", 0.008], ["MAT-FY1", 1.05], ["EQ-HIN", 3])),
  p("estructuras", "06 Estructura metálica", "EST-06.01.01", "Suministro y montaje de acero estructural (perfiles)", "kg", r(["MO-SOLD", 0.018], ["MO-PEO", 0.014], ["MAT-PERFIP", 1.05], ["EQ-SOL", 0.004], ["EQ-GRU", 0.002], ["EQ-HIN", 4])),

  p("electromecanicas", "01 Subestación y transformación", "IEM-01.01.02", "Subestación compacta tipo pedestal suministro e instalación", "und", r(["MO-TEC", 48], ["MO-ELE", 28], ["MO-MEC", 20], ["MAT-SECOMP", 1], ["EQ-GRU", 12], ["EQ-HIN", 3])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.02.10", "Suministro e instalación de transformador seco 200 kVA", "und", r(["MO-TEC", 20], ["MO-ELE", 12], ["MO-MEC", 10], ["MAT-TRAFO200S", 1], ["EQ-GRU", 6], ["EQ-HIN", 3])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.02.11", "Suministro e instalación de transformador seco 315 kVA", "und", r(["MO-TEC", 24], ["MO-ELE", 14], ["MO-MEC", 11], ["MAT-TRAFO315S", 1], ["EQ-GRU", 7], ["EQ-HIN", 3])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.02.12", "Suministro e instalación de transformador seco 1 000 kVA", "und", r(["MO-TEC", 42], ["MO-ELE", 24], ["MO-MEC", 16], ["MAT-TRAFO1000S", 1], ["EQ-GRU", 14], ["EQ-HIN", 3])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.02.13", "Suministro e instalación de transformador en aceite 250 kVA", "und", r(["MO-TEC", 22], ["MO-ELE", 14], ["MO-MEC", 11], ["MAT-TRAFOA250", 1], ["EQ-GRU", 7], ["EQ-HIN", 3])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.02.14", "Suministro e instalación de transformador en aceite 800 kVA", "und", r(["MO-TEC", 36], ["MO-ELE", 20], ["MO-MEC", 15], ["MAT-TRAFOA800", 1], ["EQ-GRU", 12], ["EQ-HIN", 3])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.03.04", "Celda de medida de media tensión", "und", r(["MO-TEC", 18], ["MO-ELE", 12], ["MAT-CELDAMED", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.05.03", "Banco de condensadores 200 kVAR suministro e instalación", "und", r(["MO-TEC", 14], ["MO-ELE", 8], ["MAT-CAP200", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "01 Subestación y transformación", "IEM-01.09.01", "Tablero de compensación de factor de potencia", "und", r(["MO-TEC", 16], ["MO-ELE", 10], ["MAT-TABCOMP", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "02 Tableros de potencia y MCC", "IEM-02.05.04", "Interruptor caja moldeada 800 A 3P instalado", "und", r(["MO-TEC", 5], ["MO-ELE", 3], ["MAT-MCCB800", 1], ["EQ-HIN", 3])),
  p("electromecanicas", "04 Grupo electrógeno", "IEM-04.01.12", "Suministro e instalación de grupo electrógeno diésel 40 kVA cabinado", "und", r(["MO-GE", 26], ["MO-TEC", 16], ["MO-ELE", 12], ["MAT-GE40", 1], ["MAT-ESCGE", 1], ["EQ-GRU", 4], ["EQ-HIN", 3])),
  p("electromecanicas", "04 Grupo electrógeno", "IEM-04.01.13", "Suministro e instalación de grupo electrógeno diésel 200 kVA cabinado", "und", r(["MO-GE", 44], ["MO-TEC", 26], ["MO-ELE", 18], ["MAT-GE200", 1], ["MAT-ESCGE", 1], ["MAT-TANQGE", 1], ["EQ-GRU", 9], ["EQ-HIN", 3])),
  p("electromecanicas", "04 Grupo electrógeno", "IEM-04.01.14", "Suministro e instalación de grupo electrógeno diésel 1 000 kVA cabinado", "und", r(["MO-GE", 96], ["MO-TEC", 52], ["MO-ELE", 34], ["MAT-GE1000", 1], ["MAT-ESCGE", 1], ["MAT-TANQGE", 1], ["EQ-GRU", 26], ["EQ-HIN", 3])),
  p("electromecanicas", "04 Grupo electrógeno", "IEM-04.03.04", "Radiador / intercambiador de calor del grupo", "und", r(["MO-GE", 8], ["MO-MEC", 6], ["MAT-RADGE", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "05 UPS y respaldo", "IEM-05.01.05", "Suministro e instalación de UPS online 30 kVA", "und", r(["MO-TEC", 18], ["MO-ELE", 12], ["MAT-UPS30", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "05 UPS y respaldo", "IEM-05.01.06", "Suministro e instalación de UPS online 80 kVA", "und", r(["MO-TEC", 28], ["MO-ELE", 16], ["MAT-UPS80", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "05 UPS y respaldo", "IEM-05.01.07", "Suministro e instalación de UPS online 200 kVA", "und", r(["MO-TEC", 40], ["MO-ELE", 22], ["MAT-UPS200", 1], ["EQ-GRU", 4], ["EQ-HIN", 4])),
  p("electromecanicas", "06 Motores y accionamientos", "IEM-06.01.06", "Suministro e instalación de motor trifásico 3 HP", "und", r(["MO-MEC", 5], ["MO-ELE", 3], ["MAT-MOT3", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "06 Motores y accionamientos", "IEM-06.01.07", "Suministro e instalación de motor trifásico 15 HP", "und", r(["MO-MEC", 10], ["MO-ELE", 5], ["MAT-MOT15", 1], ["EQ-HIN", 4])),
  p("electromecanicas", "06 Motores y accionamientos", "IEM-06.01.08", "Suministro e instalación de motor trifásico 75 HP", "und", r(["MO-MEC", 20], ["MO-ELE", 9], ["MAT-MOT75", 1], ["EQ-GRU", 3], ["EQ-HIN", 4])),
  p("electromecanicas", "09 Canalizaciones de potencia", "IEM-09.01.06", "Bandeja portacable 150 mm suministro e instalación", "m", r(["MO-ELE", 0.4], ["MO-AYU", 0.3], ["MAT-BAND150", 1.05], ["EQ-HIN", 4])),
  p("electromecanicas", "09 Canalizaciones de potencia", "IEM-09.03.10", "Cable NYY 3×16+10 mm² suministro e instalación", "m", r(["MO-ELE", 0.14], ["MO-AYU", 0.1], ["MAT-NYY16", 1.05], ["EQ-HIN", 3])),
  p("electromecanicas", "09 Canalizaciones de potencia", "IEM-09.03.11", "Cable NYY 3×35+16 mm² suministro e instalación", "m", r(["MO-ELE", 0.18], ["MO-AYU", 0.13], ["MAT-NYY35", 1.05], ["EQ-HIN", 3])),
  p("electromecanicas", "09 Canalizaciones de potencia", "IEM-09.03.12", "Cable NYY 3×95+50 mm² suministro e instalación", "m", r(["MO-ELE", 0.26], ["MO-AYU", 0.18], ["MAT-NYY95", 1.05], ["EQ-HIN", 3])),
  p("electromecanicas", "09 Canalizaciones de potencia", "IEM-09.03.13", "Cable N2XSY 12/20 kV 3×50 mm² (media tensión)", "m", r(["MO-TEC", 0.42], ["MO-ELE", 0.28], ["MAT-N2XSY50", 1.05], ["EQ-HIN", 3])),
  p("electromecanicas", "09 Canalizaciones de potencia", "IEM-09.03.14", "Cable N2XSY 12/20 kV 3×120 mm² (media tensión)", "m", r(["MO-TEC", 0.58], ["MO-ELE", 0.4], ["MAT-N2XSY120", 1.05], ["EQ-HIN", 3])),
  p("electromecanicas", "09 Canalizaciones de potencia", "IEM-09.04.01", "Cable de control 7×1.5 mm² suministro e instalación", "m", r(["MO-ELE", 0.1], ["MO-AYU", 0.07], ["MAT-CCTRL", 1.05], ["EQ-HIN", 3])),
  p("electromecanicas", "11 Generación fotovoltaica", "IEM-11.01.02", "Suministro e instalación de sistema fotovoltaico 30 kWp", "und", r(["MO-TEC", 72], ["MO-ELE", 40], ["MO-PEO", 28], ["MAT-FV30", 1], ["EQ-GRU", 10], ["EQ-HIN", 3])),
  p("electromecanicas", "10 Pruebas y puesta en marcha", "IEM-10.01.06", "Prueba y ajuste de relés de protección", "glb", r(["MO-TEC", 16], ["MO-ELE", 8], ["EQ-HIN", 3])),

  p("comunicaciones", "09 Fibra óptica", "COM-09.01.03", "Cable de fibra óptica 24 hilos (backbone)", "m", r(["MO-TEL", 0.16], ["MO-AYU", 0.1], ["MAT-FO24", 1.05], ["EQ-HIN", 3])),
  p("comunicaciones", "04 CCTV y seguridad", "COM-04.01.04", "Cámara IP PTZ exterior suministro e instalación", "und", r(["MO-TEL", 4], ["MO-AYU", 2.5], ["MAT-CAMPTZ", 1], ["MAT-UTP", 30], ["EQ-HIN", 3])),
  p("comunicaciones", "04 CCTV y seguridad", "COM-04.02.04", "NVR 8 canales + HDD", "und", r(["MO-TEL", 4], ["MO-AYU", 2], ["MAT-NVR8", 1], ["EQ-HIN", 3])),
  p("comunicaciones", "07 Alarma contra incendio", "COM-07.01.02", "Central de alarma contra incendio convencional", "und", r(["MO-TEL", 8], ["MO-ELE", 4], ["MAT-CENTCONV", 1], ["EQ-HIN", 3])),
];
