import type { Partida } from "./types";
import { p, r } from "./partidaBuilder";

function thw(n: string, mm: string, mat: string, mo: number): Partida {
  return p(
    "electricas",
    "06 Conductores",
    `IE-04.10.${n}`,
    `Conductor THW-90 ${mm} mm² 600 V (aislado PVC 90 °C) en canalización existente — circuitos interiores desde tablero`,
    "m",
    r(["MO-ELE", mo], ["MO-AYU", mo * 0.7], [mat, 1.05], ["EQ-HIN", 3]),
  );
}

function lsoh(n: string, mm: string, mat: string, mo: number): Partida {
  return p(
    "electricas",
    "06 Conductores",
    `IE-04.11.${n}`,
    `Conductor LSOH / N2XOH ${mm} mm² 0.6/1 kV (bajo humo, no halogenado) en canalización existente — áreas públicas / evacuación`,
    "m",
    r(["MO-ELE", mo], ["MO-AYU", mo * 0.75], [mat, 1.05], ["EQ-HIN", 3]),
  );
}

export const PARTIDAS_AMPLIADO: Partida[] = [
  thw("01", "1.5", "MAT-THW15", 0.05),
  thw("02", "2.5", "MAT-THW25", 0.055),
  thw("03", "4", "MAT-THW4", 0.06),
  thw("04", "6", "MAT-THW6M", 0.07),
  thw("05", "10", "MAT-THW10", 0.08),
  thw("06", "16", "MAT-THW16", 0.09),
  thw("07", "25", "MAT-THW25M", 0.1),
  thw("08", "35", "MAT-THW35", 0.12),
  thw("09", "50", "MAT-THW50", 0.14),
  thw("10", "70", "MAT-THW70", 0.16),
  thw("11", "95", "MAT-THW95", 0.18),
  thw("12", "120", "MAT-THW120", 0.2),
  thw("13", "150", "MAT-THW150", 0.22),
  thw("14", "185", "MAT-THW185", 0.25),
  thw("15", "240", "MAT-THW240", 0.28),

  lsoh("01", "1.5", "MAT-LSOH15", 0.055),
  lsoh("02", "2.5", "MAT-LSOH25", 0.06),
  lsoh("03", "4", "MAT-LSOH4", 0.065),
  lsoh("04", "6", "MAT-LSOH6", 0.075),
  lsoh("05", "10", "MAT-LSOH10", 0.09),
  lsoh("06", "16", "MAT-LSOH16", 0.1),

  p("electricas", "05 Canalizaciones", "IE-04.12.01", "Canalización empotrada PVC-P Ø16 mm (conduit rígido) — circuitos interiores", "m", r(["MO-ELE", 0.14], ["MO-AYU", 0.12], ["MAT-PVC16C", 1.05], ["EQ-TAL", 0.04], ["EQ-HIN", 4])),
  p("electricas", "05 Canalizaciones", "IE-04.12.02", "Canalización empotrada PVC-P Ø40 mm (conduit rígido) — alimentadores de piso", "m", r(["MO-ELE", 0.22], ["MO-AYU", 0.17], ["MAT-PVC40C", 1.05], ["EQ-TAL", 0.07], ["EQ-HIN", 4])),
  p("electricas", "05 Canalizaciones", "IE-04.12.03", "Canalización empotrada PVC-P Ø63 mm (conduit rígido)", "m", r(["MO-ELE", 0.28], ["MO-AYU", 0.22], ["MAT-PVC63C", 1.05], ["EQ-TAL", 0.09], ["EQ-HIN", 4])),
  p("electricas", "05 Canalizaciones", "IE-04.12.04", "Canalización empotrada PVC-P Ø75 mm (conduit rígido)", "m", r(["MO-ELE", 0.32], ["MO-AYU", 0.24], ["MAT-PVC75C", 1.05], ["EQ-HIN", 4])),
  p("electricas", "05 Canalizaciones", "IE-04.12.05", "Canalización empotrada PVC-P Ø90 mm (conduit rígido)", "m", r(["MO-ELE", 0.36], ["MO-AYU", 0.26], ["MAT-PVC90C", 1.05], ["EQ-HIN", 4])),
  p("electricas", "05 Canalizaciones", "IE-04.12.06", "Canalización empotrada PVC-P Ø110 mm (conduit rígido)", "m", r(["MO-ELE", 0.42], ["MO-AYU", 0.3], ["MAT-PVC110C", 1.05], ["EQ-HIN", 4])),

  p("electricas", "08 Sistema de transferencia de carga", "IE-06.01.01", "Suministro e instalación de ATS 100 A 3P+N transición abierta", "und", r(["MO-TEC", 12], ["MO-ELE", 8], ["MO-AYU", 6], ["MAT-ATS100", 1], ["EQ-HIN", 4])),
  p("electricas", "08 Sistema de transferencia de carga", "IE-06.01.02", "Suministro e instalación de ATS 160 A 3P+N transición abierta", "und", r(["MO-TEC", 14], ["MO-ELE", 9], ["MO-AYU", 7], ["MAT-ATS160", 1], ["EQ-HIN", 4])),
  p("electricas", "08 Sistema de transferencia de carga", "IE-06.01.03", "Suministro e instalación de ATS 250 A 3P+N transición abierta", "und", r(["MO-TEC", 16], ["MO-ELE", 10], ["MO-AYU", 8], ["MAT-ATS250", 1], ["EQ-HIN", 4])),
  p("electricas", "08 Sistema de transferencia de carga", "IE-06.01.04", "Suministro e instalación de ATS 400 A 3P+N transición abierta", "und", r(["MO-TEC", 20], ["MO-ELE", 12], ["MO-AYU", 10], ["MAT-ATS400", 1], ["EQ-HIN", 4])),
  p("electricas", "08 Sistema de transferencia de carga", "IE-06.01.05", "Suministro e instalación de ATS 630 A 3P+N transición abierta", "und", r(["MO-TEC", 24], ["MO-ELE", 14], ["MO-AYU", 12], ["MAT-ATS630", 1], ["EQ-HIN", 4])),
  p("electricas", "08 Sistema de transferencia de carga", "IE-06.02.01", "Suministro e instalación de ATS 800 A 3P+N transición cerrada", "und", r(["MO-TEC", 32], ["MO-ELE", 18], ["MO-AYU", 14], ["MAT-ATS800", 1], ["EQ-HIN", 4])),
  p("electricas", "08 Sistema de transferencia de carga", "IE-06.02.02", "Suministro e instalación de ATS 1 000 A 3P+N con bypass", "und", r(["MO-TEC", 40], ["MO-ELE", 22], ["MO-AYU", 16], ["MAT-ATS1000", 1], ["EQ-HIN", 4])),
  p("electricas", "08 Sistema de transferencia de carga", "IE-06.02.03", "Suministro e instalación de ATS 1 600 A 3P+N con bypass", "und", r(["MO-TEC", 48], ["MO-ELE", 26], ["MO-AYU", 20], ["MAT-ATS1600", 1], ["EQ-HIN", 4])),
  p("electricas", "08 Sistema de transferencia de carga", "IE-06.03.01", "Tablero de transferencia manual 3P+N (no automático)", "und", r(["MO-TEC", 10], ["MO-ELE", 6], ["MAT-TAB18", 1], ["EQ-HIN", 4])),
  p("electricas", "08 Sistema de transferencia de carga", "IE-06.04.01", "UPS online 20 kVA suministro e instalación", "und", r(["MO-TEC", 16], ["MO-ELE", 10], ["MAT-UPS20", 1], ["EQ-HIN", 4])),
  p("electricas", "08 Sistema de transferencia de carga", "IE-06.04.02", "UPS online 60 kVA suministro e instalación", "und", r(["MO-TEC", 24], ["MO-ELE", 14], ["MAT-UPS60", 1], ["EQ-HIN", 4])),

  p("electricas", "09 Grupo electrógeno", "IE-07.01.01", "Suministro e instalación de grupo electrógeno diésel 30 kVA cabinado", "und", r(["MO-GE", 24], ["MO-TEC", 16], ["MO-ELE", 12], ["MAT-GE30", 1], ["MAT-ESCGE", 1], ["EQ-GRU", 4], ["EQ-HIN", 3])),
  p("electricas", "09 Grupo electrógeno", "IE-07.01.02", "Suministro e instalación de grupo electrógeno diésel 50 kVA cabinado", "und", r(["MO-GE", 28], ["MO-TEC", 18], ["MO-ELE", 14], ["MAT-GE50", 1], ["MAT-ESCGE", 1], ["EQ-GRU", 4], ["EQ-HIN", 3])),
  p("electricas", "09 Grupo electrógeno", "IE-07.01.03", "Suministro e instalación de grupo electrógeno diésel 80 kVA cabinado", "und", r(["MO-GE", 32], ["MO-TEC", 20], ["MO-ELE", 16], ["MAT-GE80", 1], ["MAT-ESCGE", 1], ["EQ-GRU", 6], ["EQ-HIN", 3])),
  p("electricas", "09 Grupo electrógeno", "IE-07.01.04", "Suministro e instalación de grupo electrógeno diésel 100 kVA cabinado", "und", r(["MO-GE", 36], ["MO-TEC", 22], ["MO-ELE", 16], ["MAT-GE100", 1], ["MAT-ESCGE", 1], ["MAT-TANQGE", 1], ["EQ-GRU", 6], ["EQ-HIN", 3])),
  p("electricas", "09 Grupo electrógeno", "IE-07.01.05", "Suministro e instalación de grupo electrógeno diésel 150 kVA cabinado", "und", r(["MO-GE", 40], ["MO-TEC", 24], ["MO-ELE", 18], ["MAT-GE150", 1], ["MAT-ESCGE", 1], ["MAT-TANQGE", 1], ["EQ-GRU", 8], ["EQ-HIN", 3])),
  p("electricas", "09 Grupo electrógeno", "IE-07.01.06", "Suministro e instalación de grupo electrógeno diésel 250 kVA cabinado", "und", r(["MO-GE", 48], ["MO-TEC", 28], ["MO-ELE", 20], ["MAT-GE250", 1], ["MAT-ESCGE", 1], ["MAT-TANQGE", 1], ["EQ-GRU", 10], ["EQ-HIN", 3])),
  p("electricas", "09 Grupo electrógeno", "IE-07.01.07", "Suministro e instalación de grupo electrógeno diésel 350 kVA cabinado", "und", r(["MO-GE", 56], ["MO-TEC", 32], ["MO-ELE", 22], ["MAT-GE350", 1], ["MAT-ESCGE", 1], ["MAT-TANQGE", 1], ["EQ-GRU", 12], ["EQ-HIN", 3])),
  p("electricas", "09 Grupo electrógeno", "IE-07.01.08", "Suministro e instalación de grupo electrógeno diésel 500 kVA cabinado", "und", r(["MO-GE", 64], ["MO-TEC", 36], ["MO-ELE", 24], ["MAT-GE500", 1], ["MAT-ESCGE", 1], ["MAT-TANQGE", 1], ["EQ-GRU", 16], ["EQ-HIN", 3])),
  p("electricas", "09 Grupo electrógeno", "IE-07.02.01", "Losa de fundación para grupo electrógeno f'c 210", "m³", r(["MO-OPE", 3.2], ["MO-PEO", 3.8], ["MO-FIE", 0.8], ["MAT-CEM", 8.4], ["MAT-ARE", 0.52], ["MAT-PIE", 0.92], ["MAT-FY42", 90], ["EQ-MEZ", 0.55], ["EQ-HIN", 5])),
  p("electricas", "09 Grupo electrógeno", "IE-07.02.02", "Tanque de combustible diario 1 000 L c/cubeto", "und", r(["MO-GE", 8], ["MO-MEC", 6], ["MAT-TANQGE", 1], ["EQ-HIN", 4])),

  p("electricas", "05 Artefactos", "IE-05.10.01", "Suministro e instalación de luminaria LED empotrada 6 W", "und", r(["MO-ELE", 0.38], ["MO-AYU", 0.22], ["MAT-LUM06", 1], ["EQ-HIN", 3])),
  p("electricas", "05 Artefactos", "IE-05.10.02", "Suministro e instalación de luminaria LED empotrada 36 W", "und", r(["MO-ELE", 0.52], ["MO-AYU", 0.34], ["MAT-LUM36", 1], ["EQ-HIN", 3])),
  p("electricas", "05 Artefactos", "IE-05.10.03", "Suministro e instalación de panel LED 60×60 cm 40 W", "und", r(["MO-ELE", 0.55], ["MO-AYU", 0.35], ["MAT-PAN6060", 1], ["EQ-HIN", 3])),
  p("electricas", "05 Artefactos", "IE-05.10.04", "Suministro e instalación de panel LED 30×120 cm 36 W", "und", r(["MO-ELE", 0.52], ["MO-AYU", 0.34], ["MAT-PAN30120", 1], ["EQ-HIN", 3])),
  p("electricas", "05 Artefactos", "IE-05.10.05", "Suministro e instalación de downlight LED IP65 18 W", "und", r(["MO-ELE", 0.5], ["MO-AYU", 0.32], ["MAT-IP65", 1], ["EQ-HIN", 3])),
  p("electricas", "05 Artefactos", "IE-05.10.06", "Suministro e instalación de luminaria estanca LED 36 W", "und", r(["MO-ELE", 0.55], ["MO-AYU", 0.35], ["MAT-HERM", 1], ["EQ-HIN", 3])),
  p("electricas", "05 Artefactos", "IE-05.10.07", "Suministro e instalación de luminaria de emergencia 8 W 90 min", "und", r(["MO-ELE", 0.6], ["MO-AYU", 0.35], ["MAT-EMERG", 1], ["EQ-HIN", 3])),
  p("electricas", "05 Artefactos", "IE-05.10.08", "Suministro e instalación de señal de salida LED", "und", r(["MO-ELE", 0.45], ["MO-AYU", 0.28], ["MAT-EXIT", 1], ["EQ-HIN", 3])),
  p("electricas", "05 Artefactos", "IE-05.11.01", "Suministro e instalación de luminaria LED vial 70 W", "und", r(["MO-ELE", 1.8], ["MO-AYU", 1.2], ["MAT-AP70", 1], ["EQ-HIN", 4])),
  p("electricas", "05 Artefactos", "IE-05.11.02", "Suministro e instalación de luminaria LED vial 100 W", "und", r(["MO-ELE", 2], ["MO-AYU", 1.3], ["MAT-AP100", 1], ["EQ-HIN", 4])),
  p("electricas", "05 Artefactos", "IE-05.11.03", "Suministro e instalación de luminaria LED vial 150 W", "und", r(["MO-ELE", 2.2], ["MO-AYU", 1.4], ["MAT-AP150", 1], ["EQ-HIN", 4])),
  p("electricas", "05 Artefactos", "IE-05.11.04", "Suministro e instalación de luminaria LED vial 250 W", "und", r(["MO-ELE", 2.6], ["MO-AYU", 1.6], ["MAT-AP250", 1], ["EQ-HIN", 4])),
  p("electricas", "05 Artefactos", "IE-05.12.01", "Suministro e instalación de proyector LED 50 W", "und", r(["MO-ELE", 0.7], ["MO-AYU", 0.4], ["MAT-PROJ50", 1], ["EQ-HIN", 3])),
  p("electricas", "05 Artefactos", "IE-05.12.02", "Suministro e instalación de proyector LED 100 W", "und", r(["MO-ELE", 0.8], ["MO-AYU", 0.5], ["MAT-PROJ100", 1], ["EQ-HIN", 3])),
  p("electricas", "05 Artefactos", "IE-05.12.03", "Suministro e instalación de proyector LED 200 W", "und", r(["MO-ELE", 1], ["MO-AYU", 0.6], ["MAT-PROJ200", 1], ["EQ-HIN", 3])),
  p("electricas", "05 Artefactos", "IE-05.12.04", "Suministro e instalación de proyector LED 400 W", "und", r(["MO-ELE", 1.2], ["MO-AYU", 0.7], ["MAT-PROJ400", 1], ["EQ-HIN", 3])),
  p("electricas", "05 Artefactos", "IE-05.13.01", "Suministro e instalación de high bay LED 150 W", "und", r(["MO-ELE", 1.4], ["MO-AYU", 0.9], ["MAT-HIGBAY", 1], ["EQ-AND", 0.2], ["EQ-HIN", 3])),
  p("electricas", "05 Artefactos", "IE-05.13.02", "Suministro e instalación de wall pack LED 30 W", "und", r(["MO-ELE", 0.7], ["MO-AYU", 0.4], ["MAT-WALLP", 1], ["EQ-HIN", 3])),
  p("electricas", "05 Artefactos", "IE-05.13.03", "Suministro e instalación de baliza / bollard LED 12 W", "und", r(["MO-ELE", 0.9], ["MO-AYU", 0.6], ["MAT-BOLL", 1], ["EQ-HIN", 3])),
  p("electricas", "05 Artefactos", "IE-05.14.01", "Suministro e instalación de lámpara quirúrgica LED de techo", "und", r(["MO-BIO", 16], ["MO-ELE", 8], ["MO-AYU", 8], ["MAT-LUMQX", 1], ["EQ-AND", 0.5], ["EQ-HIN", 3])),
  p("electricas", "05 Artefactos", "IE-05.14.02", "Suministro e instalación de lámpara de examen LED", "und", r(["MO-ELE", 2], ["MO-AYU", 1.2], ["MAT-LUMEX", 1], ["EQ-HIN", 3])),
  p("electricas", "05 Artefactos", "IE-05.14.03", "Suministro e instalación de luminaria sala limpia IP65 60×60", "und", r(["MO-ELE", 0.7], ["MO-AYU", 0.45], ["MAT-CLEAN", 1], ["EQ-HIN", 3])),
  p("electricas", "05 Artefactos", "IE-05.14.04", "Suministro e instalación de luminaria UV-C germicida", "und", r(["MO-ELE", 0.8], ["MO-AYU", 0.5], ["MAT-UV", 1], ["EQ-HIN", 3])),
  p("electricas", "05 Artefactos", "IE-05.14.05", "Suministro e instalación de luminaria industrial vapor 80 W", "und", r(["MO-ELE", 0.75], ["MO-AYU", 0.45], ["MAT-INDUS", 1], ["EQ-HIN", 3])),

  p("sanitarias", "08 Canalización de cobre tipo L (hospitalaria)", "IS-08.01.01", "Tubería de cobre tipo L Ø1/4\" suministro e instalación", "m", r(["MO-GAS", 0.28], ["MO-AYU", 0.18], ["MAT-CUL14", 1.05], ["EQ-HIN", 5])),
  p("sanitarias", "08 Canalización de cobre tipo L (hospitalaria)", "IS-08.01.02", "Tubería de cobre tipo L Ø3/8\" suministro e instalación", "m", r(["MO-GAS", 0.3], ["MO-AYU", 0.2], ["MAT-CUL38", 1.05], ["EQ-HIN", 5])),
  p("sanitarias", "08 Canalización de cobre tipo L (hospitalaria)", "IS-08.01.03", "Tubería de cobre tipo L Ø1/2\" suministro e instalación", "m", r(["MO-GAS", 0.32], ["MO-AYU", 0.22], ["MAT-CUL12", 1.05], ["EQ-HIN", 5])),
  p("sanitarias", "08 Canalización de cobre tipo L (hospitalaria)", "IS-08.01.04", "Tubería de cobre tipo L Ø5/8\" suministro e instalación", "m", r(["MO-GAS", 0.34], ["MO-AYU", 0.22], ["MAT-CUL58", 1.05], ["EQ-HIN", 5])),
  p("sanitarias", "08 Canalización de cobre tipo L (hospitalaria)", "IS-08.01.05", "Tubería de cobre tipo L Ø3/4\" suministro e instalación", "m", r(["MO-GAS", 0.36], ["MO-AYU", 0.24], ["MAT-CUL34", 1.05], ["EQ-HIN", 5])),
  p("sanitarias", "08 Canalización de cobre tipo L (hospitalaria)", "IS-08.01.06", "Tubería de cobre tipo L Ø1\" suministro e instalación", "m", r(["MO-GAS", 0.4], ["MO-AYU", 0.26], ["MAT-CUL1", 1.05], ["EQ-HIN", 5])),
  p("sanitarias", "08 Canalización de cobre tipo L (hospitalaria)", "IS-08.01.07", "Tubería de cobre tipo L Ø1¼\" suministro e instalación", "m", r(["MO-GAS", 0.45], ["MO-AYU", 0.3], ["MAT-CUL114", 1.05], ["EQ-HIN", 5])),
  p("sanitarias", "08 Canalización de cobre tipo L (hospitalaria)", "IS-08.01.08", "Tubería de cobre tipo L Ø1½\" suministro e instalación", "m", r(["MO-GAS", 0.5], ["MO-AYU", 0.32], ["MAT-CUL112", 1.05], ["EQ-HIN", 5])),
  p("sanitarias", "08 Canalización de cobre tipo L (hospitalaria)", "IS-08.01.09", "Tubería de cobre tipo L Ø2\" suministro e instalación", "m", r(["MO-GAS", 0.58], ["MO-AYU", 0.38], ["MAT-CUL2", 1.05], ["EQ-HIN", 5])),
  p("sanitarias", "08 Canalización de cobre tipo L (hospitalaria)", "IS-08.01.10", "Tubería de cobre tipo L Ø2½\" suministro e instalación", "m", r(["MO-GAS", 0.68], ["MO-AYU", 0.45], ["MAT-CUL212", 1.05], ["EQ-HIN", 5])),
  p("sanitarias", "08 Canalización de cobre tipo L (hospitalaria)", "IS-08.01.11", "Tubería de cobre tipo L Ø3\" suministro e instalación", "m", r(["MO-GAS", 0.78], ["MO-AYU", 0.52], ["MAT-CUL3", 1.05], ["EQ-HIN", 5])),
  p("sanitarias", "08 Canalización de cobre tipo L (hospitalaria)", "IS-08.01.12", "Tubería de cobre tipo L Ø4\" suministro e instalación", "m", r(["MO-GAS", 0.95], ["MO-AYU", 0.65], ["MAT-CUL4", 1.05], ["EQ-HIN", 5])),
  p("sanitarias", "08 Canalización de cobre tipo L (hospitalaria)", "IS-08.01.13", "Tubería de cobre tipo L Ø5\" suministro e instalación", "m", r(["MO-GAS", 1.1], ["MO-AYU", 0.75], ["MAT-CUL5", 1.05], ["EQ-HIN", 5])),
  p("sanitarias", "08 Canalización de cobre tipo L (hospitalaria)", "IS-08.01.14", "Tubería de cobre tipo L Ø6\" suministro e instalación", "m", r(["MO-GAS", 1.3], ["MO-AYU", 0.9], ["MAT-CUL6", 1.05], ["EQ-HIN", 5])),
  p("sanitarias", "08 Canalización de cobre tipo L (hospitalaria)", "IS-08.01.15", "Tubería de cobre tipo L Ø8\" suministro e instalación", "m", r(["MO-GAS", 1.6], ["MO-AYU", 1.1], ["MAT-CUL8", 1.05], ["EQ-HIN", 5])),
  p("sanitarias", "08 Canalización de cobre tipo L (hospitalaria)", "IS-08.02.01", "Tubería de cobre tipo K Ø1/2\" enterrada", "m", r(["MO-GAS", 0.38], ["MO-AYU", 0.26], ["MAT-CUK12", 1.05], ["EQ-HIN", 5])),
  p("sanitarias", "08 Canalización de cobre tipo L (hospitalaria)", "IS-08.02.02", "Tubería de cobre tipo K Ø1\" enterrada", "m", r(["MO-GAS", 0.48], ["MO-AYU", 0.32], ["MAT-CUK1", 1.05], ["EQ-HIN", 5])),
  p("sanitarias", "08 Canalización de cobre tipo L (hospitalaria)", "IS-08.02.03", "Tubería de cobre tipo K Ø2\" enterrada", "m", r(["MO-GAS", 0.68], ["MO-AYU", 0.45], ["MAT-CUK2", 1.05], ["EQ-HIN", 5])),
  p("sanitarias", "08 Canalización de cobre tipo L (hospitalaria)", "IS-08.02.04", "Tubería de cobre tipo K Ø4\" enterrada", "m", r(["MO-GAS", 1.05], ["MO-AYU", 0.7], ["MAT-CUK4", 1.05], ["EQ-HIN", 5])),

  p("sanitarias", "09 Válvulas de bronce y llaves especiales", "IS-09.01.01", "Válvula de compuerta bronce ½\" suministro e instalación", "und", r(["MO-GAS", 0.5], ["MO-AYU", 0.3], ["MAT-VBR12", 1], ["EQ-HIN", 4])),
  p("sanitarias", "09 Válvulas de bronce y llaves especiales", "IS-09.01.02", "Válvula de compuerta bronce ¾\" suministro e instalación", "und", r(["MO-GAS", 0.55], ["MO-AYU", 0.32], ["MAT-VBR34", 1], ["EQ-HIN", 4])),
  p("sanitarias", "09 Válvulas de bronce y llaves especiales", "IS-09.01.03", "Válvula de compuerta bronce 1\" suministro e instalación", "und", r(["MO-GAS", 0.7], ["MO-AYU", 0.4], ["MAT-VBR1", 1], ["EQ-HIN", 4])),
  p("sanitarias", "09 Válvulas de bronce y llaves especiales", "IS-09.01.04", "Válvula de compuerta bronce 1¼\" suministro e instalación", "und", r(["MO-GAS", 0.85], ["MO-AYU", 0.5], ["MAT-VBR114", 1], ["EQ-HIN", 4])),
  p("sanitarias", "09 Válvulas de bronce y llaves especiales", "IS-09.01.05", "Válvula de compuerta bronce 1½\" suministro e instalación", "und", r(["MO-GAS", 1], ["MO-AYU", 0.55], ["MAT-VBR112", 1], ["EQ-HIN", 4])),
  p("sanitarias", "09 Válvulas de bronce y llaves especiales", "IS-09.01.06", "Válvula de compuerta bronce 2\" suministro e instalación", "und", r(["MO-GAS", 1.2], ["MO-AYU", 0.7], ["MAT-VBR2", 1], ["EQ-HIN", 4])),
  p("sanitarias", "09 Válvulas de bronce y llaves especiales", "IS-09.01.07", "Válvula de compuerta bronce 2½\" suministro e instalación", "und", r(["MO-GAS", 1.6], ["MO-AYU", 0.9], ["MAT-VBR212", 1], ["EQ-HIN", 4])),
  p("sanitarias", "09 Válvulas de bronce y llaves especiales", "IS-09.01.08", "Válvula de compuerta bronce 3\" c/volante", "und", r(["MO-GAS", 2.2], ["MO-AYU", 1.2], ["MAT-VBR3", 1], ["EQ-HIN", 4])),
  p("sanitarias", "09 Válvulas de bronce y llaves especiales", "IS-09.01.09", "Válvula de compuerta bronce 4\" c/volante", "und", r(["MO-GAS", 3], ["MO-AYU", 1.8], ["MAT-VBR4", 1], ["EQ-HIN", 4])),
  p("sanitarias", "09 Válvulas de bronce y llaves especiales", "IS-09.01.10", "Válvula de compuerta bronce 6\" c/volante", "und", r(["MO-GAS", 4.5], ["MO-AYU", 2.5], ["MAT-VBR6", 1], ["EQ-HIN", 4])),
  p("sanitarias", "09 Válvulas de bronce y llaves especiales", "IS-09.01.11", "Válvula de compuerta bronce 8\" c/engranaje y llave especial", "und", r(["MO-GAS", 6], ["MO-AYU", 3.5], ["MAT-VBR8", 1], ["MAT-LLAVESP", 1], ["EQ-HIN", 4])),
  p("sanitarias", "09 Válvulas de bronce y llaves especiales", "IS-09.02.01", "Válvula de globo bronce 2\"", "und", r(["MO-GAS", 1.4], ["MO-AYU", 0.8], ["MAT-VGL2", 1], ["EQ-HIN", 4])),
  p("sanitarias", "09 Válvulas de bronce y llaves especiales", "IS-09.02.02", "Válvula de globo bronce 4\"", "und", r(["MO-GAS", 2.8], ["MO-AYU", 1.6], ["MAT-VGL4", 1], ["EQ-HIN", 4])),
  p("sanitarias", "09 Válvulas de bronce y llaves especiales", "IS-09.03.01", "Válvula mariposa 4\" brida", "und", r(["MO-GAS", 2.2], ["MO-AYU", 1.4], ["MAT-VMAR4", 1], ["EQ-HIN", 4])),
  p("sanitarias", "09 Válvulas de bronce y llaves especiales", "IS-09.03.02", "Válvula mariposa 6\" brida", "und", r(["MO-GAS", 2.8], ["MO-AYU", 1.8], ["MAT-VMAR6", 1], ["EQ-HIN", 4])),
  p("sanitarias", "09 Válvulas de bronce y llaves especiales", "IS-09.03.03", "Válvula mariposa 8\" brida", "und", r(["MO-GAS", 3.4], ["MO-AYU", 2], ["MAT-VMAR8", 1], ["EQ-HIN", 4])),
  p("sanitarias", "09 Válvulas de bronce y llaves especiales", "IS-09.04.01", "Válvula de retención bronce 2\"", "und", r(["MO-GAS", 1.2], ["MO-AYU", 0.7], ["MAT-VRET2", 1], ["EQ-HIN", 4])),
  p("sanitarias", "09 Válvulas de bronce y llaves especiales", "IS-09.04.02", "Válvula de retención 4\"", "und", r(["MO-GAS", 2.4], ["MO-AYU", 1.4], ["MAT-VRET4", 1], ["EQ-HIN", 4])),
  p("sanitarias", "09 Válvulas de bronce y llaves especiales", "IS-09.05.01", "Válvula reductora de presión 2\"", "und", r(["MO-GAS", 2.5], ["MO-AYU", 1.5], ["MAT-PRV2", 1], ["EQ-HIN", 4])),
  p("sanitarias", "09 Válvulas de bronce y llaves especiales", "IS-09.06.01", "Llave de operación de piso / vástago largo (llave especial)", "und", r(["MO-GAS", 1.2], ["MO-AYU", 0.8], ["MAT-LLAVESP", 1], ["EQ-HIN", 4])),

  p("mecanicas", "02 Sistema contra incendio", "IM-02.10.01", "Red contra incendio acero negro Sch.40 Ø1\"", "m", r(["MO-CI", 0.35], ["MO-SOLD", 0.25], ["MO-AYU", 0.22], ["MAT-ACSCH", 1.05], ["EQ-SOL", 0.15], ["EQ-HIN", 5])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.10.02", "Red contra incendio acero negro Sch.40 Ø1½\"", "m", r(["MO-CI", 0.4], ["MO-SOLD", 0.3], ["MO-AYU", 0.25], ["MAT-ACSCH", 1.15], ["EQ-SOL", 0.18], ["EQ-HIN", 5])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.10.03", "Red contra incendio acero negro Sch.40 Ø2\"", "m", r(["MO-CI", 0.45], ["MO-SOLD", 0.35], ["MO-AYU", 0.3], ["MAT-ACSCH", 1.25], ["EQ-SOL", 0.2], ["EQ-HIN", 5])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.10.04", "Red contra incendio acero negro Sch.40 Ø2½\"", "m", r(["MO-CI", 0.52], ["MO-SOLD", 0.4], ["MO-AYU", 0.35], ["MAT-ACSCH", 1.4], ["EQ-SOL", 0.24], ["EQ-HIN", 5])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.10.05", "Red contra incendio acero negro Sch.40 Ø3\"", "m", r(["MO-CI", 0.6], ["MO-SOLD", 0.45], ["MO-AYU", 0.4], ["MAT-ACSCH", 1.6], ["EQ-SOL", 0.28], ["EQ-HIN", 5])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.10.06", "Red contra incendio acero negro Sch.40 Ø4\"", "m", r(["MO-CI", 0.75], ["MO-SOLD", 0.55], ["MO-AYU", 0.48], ["MAT-ACSCH", 1.9], ["EQ-SOL", 0.32], ["EQ-HIN", 5])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.10.07", "Red contra incendio acero negro Sch.40 Ø6\"", "m", r(["MO-CI", 0.95], ["MO-SOLD", 0.7], ["MO-AYU", 0.6], ["MAT-ACSCH", 2.4], ["EQ-SOL", 0.4], ["EQ-HIN", 5])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.10.08", "Red contra incendio acero negro Sch.40 Ø8\"", "m", r(["MO-CI", 1.2], ["MO-SOLD", 0.85], ["MO-AYU", 0.75], ["MAT-ACSCH", 3.1], ["EQ-SOL", 0.5], ["EQ-HIN", 5])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.11.01", "Rociador sprinkler pendiente ½\" 68 °C", "und", r(["MO-CI", 0.45], ["MO-AYU", 0.25], ["MAT-SPRK", 1], ["EQ-HIN", 3])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.11.02", "Rociador sprinkler upright ½\"", "und", r(["MO-CI", 0.45], ["MO-AYU", 0.25], ["MAT-SPRKU", 1], ["EQ-HIN", 3])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.11.03", "Rociador sprinkler sidewall", "und", r(["MO-CI", 0.5], ["MO-AYU", 0.28], ["MAT-SPRKS", 1], ["EQ-HIN", 3])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.11.04", "Rociador sprinkler hidden / concealed", "und", r(["MO-CI", 0.7], ["MO-AYU", 0.35], ["MAT-SPRKH", 1], ["EQ-HIN", 3])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.12.01", "Siamesa de fachada 2×2½\"", "und", r(["MO-CI", 4], ["MO-AYU", 3], ["MAT-SIAM", 1], ["EQ-HIN", 4])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.12.02", "Gabinete contra incendio 45 mm c/manguera 30 m", "und", r(["MO-CI", 3.5], ["MO-AYU", 2.5], ["MAT-GAB45", 1], ["EQ-HIN", 4])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.12.03", "Gabinete contra incendio 65 mm c/manguera 30 m", "und", r(["MO-CI", 4], ["MO-AYU", 2.8], ["MAT-GAB65", 1], ["EQ-HIN", 4])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.13.01", "Bomba contra incendio eléctrica 15 HP", "und", r(["MO-CI", 16], ["MO-MEC", 10], ["MO-ELE", 8], ["MAT-BOMCI15", 1], ["EQ-HIN", 4])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.13.02", "Bomba contra incendio eléctrica 40 HP", "und", r(["MO-CI", 20], ["MO-MEC", 12], ["MO-ELE", 10], ["MAT-BOMCI40", 1], ["EQ-HIN", 4])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.13.03", "Bomba contra incendio diésel 75 HP", "und", r(["MO-CI", 28], ["MO-MEC", 16], ["MO-GE", 10], ["MAT-BOMCID", 1], ["EQ-HIN", 4])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.13.04", "Bomba jockey 1.5 HP", "und", r(["MO-CI", 6], ["MO-ELE", 4], ["MAT-JOCK", 1], ["EQ-HIN", 4])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.14.01", "Válvula OS&Y 4\" contra incendio", "und", r(["MO-CI", 3], ["MO-AYU", 2], ["MAT-OSY4", 1], ["EQ-HIN", 4])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.14.02", "Válvula OS&Y 6\" contra incendio", "und", r(["MO-CI", 4], ["MO-AYU", 2.5], ["MAT-OSY6", 1], ["EQ-HIN", 4])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.14.03", "Post indicator valve PIV 6\"", "und", r(["MO-CI", 5], ["MO-AYU", 3], ["MAT-PIV", 1], ["EQ-HIN", 4])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.14.04", "Válvula de alarma / flow switch", "und", r(["MO-CI", 2.5], ["MO-ELE", 1.5], ["MAT-ALMV", 1], ["EQ-HIN", 4])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.15.01", "Extintor CO2 5 kg colocado", "und", r(["MO-OPE", 0.4], ["MAT-EXTCO2", 1], ["EQ-HIN", 3])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.15.02", "Extintor acetato 6 L clase K (cocina)", "und", r(["MO-OPE", 0.4], ["MAT-EXTACE", 1], ["EQ-HIN", 3])),
  p("mecanicas", "02 Sistema contra incendio", "IM-02.15.03", "Manta ignífuga colocada", "und", r(["MO-OPE", 0.25], ["MAT-MANTCI", 1], ["EQ-HIN", 3])),

  p("mecanicas", "08 Gases medicinales y planta de oxígeno", "IM-08.01.01", "Suministro e instalación de planta de oxígeno PSA 10 Nm³/h", "und", r(["MO-MEC", 80], ["MO-BIO", 40], ["MO-ELE", 24], ["MAT-PSA10", 1], ["EQ-GRU", 8], ["EQ-HIN", 3])),
  p("mecanicas", "08 Gases medicinales y planta de oxígeno", "IM-08.01.02", "Suministro e instalación de planta de oxígeno PSA 20 Nm³/h", "und", r(["MO-MEC", 100], ["MO-BIO", 48], ["MO-ELE", 28], ["MAT-PSA20", 1], ["EQ-GRU", 10], ["EQ-HIN", 3])),
  p("mecanicas", "08 Gases medicinales y planta de oxígeno", "IM-08.01.03", "Tanque buffer / criogénico de oxígeno", "und", r(["MO-MEC", 24], ["MO-AYU", 16], ["MAT-TANQO2", 1], ["EQ-GRU", 4], ["EQ-HIN", 3])),
  p("mecanicas", "08 Gases medicinales y planta de oxígeno", "IM-08.01.04", "Manifold de cilindros O2 2×5", "und", r(["MO-MEC", 12], ["MO-AYU", 8], ["MAT-MANIFO2", 1], ["EQ-HIN", 4])),
  p("mecanicas", "08 Gases medicinales y planta de oxígeno", "IM-08.02.01", "Toma de oxígeno medicinal", "und", r(["MO-GAS", 1.8], ["MO-AYU", 1.1], ["MAT-TOMAGO2", 1], ["EQ-HIN", 4])),
  p("mecanicas", "08 Gases medicinales y planta de oxígeno", "IM-08.02.02", "Toma de vacío clínico", "und", r(["MO-GAS", 1.8], ["MO-AYU", 1.1], ["MAT-TOMAGVA", 1], ["EQ-HIN", 4])),
  p("mecanicas", "08 Gases medicinales y planta de oxígeno", "IM-08.02.03", "Toma de aire medicinal", "und", r(["MO-GAS", 1.8], ["MO-AYU", 1.1], ["MAT-TOMAGAR", 1], ["EQ-HIN", 4])),
  p("mecanicas", "08 Gases medicinales y planta de oxígeno", "IM-08.02.04", "Toma de óxido nitroso", "und", r(["MO-GAS", 2], ["MO-AYU", 1.2], ["MAT-TOMN2O", 1], ["EQ-HIN", 4])),
  p("mecanicas", "08 Gases medicinales y planta de oxígeno", "IM-08.03.01", "Válvula de zona de gases 4 servicios", "und", r(["MO-GAS", 4], ["MO-AYU", 2.5], ["MAT-VALZON", 1], ["EQ-HIN", 4])),
  p("mecanicas", "08 Gases medicinales y planta de oxígeno", "IM-08.03.02", "Panel de alarma de gases medicinales", "und", r(["MO-ELE", 4], ["MO-GAS", 2], ["MAT-ALMGAS", 1], ["EQ-HIN", 4])),
  p("mecanicas", "08 Gases medicinales y planta de oxígeno", "IM-08.04.01", "Bomba de vacío clínico 3 HP", "und", r(["MO-MEC", 10], ["MO-ELE", 6], ["MAT-VACCL", 1], ["EQ-HIN", 4])),
  p("mecanicas", "08 Gases medicinales y planta de oxígeno", "IM-08.04.02", "Compresor de aire medicinal 5 HP", "und", r(["MO-MEC", 12], ["MO-ELE", 6], ["MAT-COMPAIR", 1], ["EQ-HIN", 4])),
];
