import type { Partida, RecetaItem } from "./types";
import { p, r } from "./partidaBuilder";

function pue(
  codigo: string,
  descripcion: string,
  mat: string,
  hojas: 1 | 2,
  extra: [string, number][] = [],
  bisagras?: number,
): Partida {
  const bis = bisagras ?? (hojas === 1 ? 3 : 6);
  const receta: RecetaItem[] = r(
    ["MO-CAR", hojas === 1 ? 2.6 : 4.2],
    ["MO-PEO", hojas === 1 ? 1.3 : 2.2],
    [mat, 1],
    ["MAT-BIS", bis],
    ["MAT-CERJ", 1],
    ["MAT-PIC", hojas],
    ["MAT-TOPE", hojas],
    ["MAT-PASADOR", hojas === 2 ? 2 : 0],
    ["MAT-CLA", 0.16 * hojas],
    ["MAT-TACOMAD", 8 * hojas],
    ["MAT-ESPUMAPU", 0.4 * hojas],
    ["EQ-SIE", hojas === 1 ? 0.25 : 0.4],
    ["EQ-HIN", 5],
    ...extra,
  ).filter((x) => x.cantidad > 0);
  return p("arquitectura", "09 Carpintería de madera", codigo, descripcion, "und", receta);
}

function pueMet(
  codigo: string,
  descripcion: string,
  mat: string,
  hojas: 1 | 2,
): Partida {
  return p(
    "arquitectura",
    "10 Carpintería metálica y cerrajería",
    codigo,
    descripcion,
    "und",
    r(
      ["MO-HERR", hojas === 1 ? 3.2 : 5.5],
      ["MO-SOLD", hojas === 1 ? 1.2 : 2],
      ["MO-PEO", hojas === 1 ? 2 : 3.2],
      [mat, 1],
      ["MAT-CERJ", 1],
      ["MAT-PIC", hojas],
      ["MAT-PINA", 0.12 * hojas],
      ["EQ-SOL", hojas === 1 ? 0.8 : 1.4],
      ["EQ-HIN", 4],
    ),
  );
}

function ven(codigo: string, descripcion: string, mat: string, mo = 1.15): Partida {
  return p(
    "arquitectura",
    "10 Carpintería metálica y cerrajería",
    codigo,
    descripcion,
    "m²",
    r(
      ["MO-OPE", mo],
      ["MO-AYU", mo * 0.72],
      ["MO-VID", 0.32],
      [mat, 1],
      ["MAT-SILN", 0.45],
      ["MAT-ACCALU", 0.18],
      ["MAT-BURVID", 1.05],
      ["MAT-ANCLAALU", 6],
      ["EQ-HIN", 4],
    ),
  );
}

function vid(codigo: string, descripcion: string, mat: string, mo = 0.48): Partida {
  return p(
    "arquitectura",
    "11 Vidrios y mamparas",
    codigo,
    descripcion,
    "m²",
    r(["MO-VID", mo], ["MO-AYU", mo * 0.75], [mat, 1.06], ["MAT-SILN", 0.35], ["MAT-BURVID", 1.05], ["MAT-JUNVID", 0.8], ["EQ-HIN", 4]),
  );
}

export const PARTIDAS_PUERTAS_VENTANAS: Partida[] = [
  pue("ARQ-09.01.04", "Suministro e instalación de puerta contraplacada 1 hoja 0.60×2.10 m, e=35 mm, cara triplay okumé 3.2 mm, c/marco y herrajes", "MAT-PUECP60", 1),
  pue("ARQ-09.01.05", "Suministro e instalación de puerta contraplacada 1 hoja 1.00×2.10 m, e=40 mm, cara triplay okumé 3.2 mm, c/marco y herrajes", "MAT-PUE100", 1),
  pue("ARQ-09.01.06", "Suministro e instalación de puerta contraplacada 1 hoja 0.90×2.20 m, e=35 mm, cara triplay okumé 3.2 mm, c/marco y herrajes", "MAT-PUECP90H220", 1),
  pue("ARQ-09.01.07", "Suministro e instalación de puerta contraplacada 1 hoja 1.00×2.20 m, e=40 mm, c/marco y herrajes", "MAT-PUECP100H220", 1),
  pue("ARQ-09.01.08", "Suministro e instalación de puerta contraplacada 1 hoja 0.80×2.20 m, e=35 mm, cara triplay okumé 3.2 mm, c/marco y herrajes", "MAT-PUECP80H220", 1),
  pue("ARQ-09.01.09", "Suministro e instalación de puerta contraplacada 1 hoja 0.90×2.40 m, e=40 mm, cara triplay okumé 3.2 mm, c/marco y herrajes", "MAT-PUECP90H240", 1),

  pue("ARQ-09.05.01", "Suministro e instalación de puerta contraplacada 2 hojas 1.20×2.10 m (0.60+0.60), e=35 mm, c/marco, pasadores y herrajes", "MAT-PUECP2H120", 2),
  pue("ARQ-09.05.02", "Suministro e instalación de puerta contraplacada 2 hojas 1.40×2.10 m (0.70+0.70), e=35 mm, c/marco, pasadores y herrajes", "MAT-PUECP2H140", 2),
  pue("ARQ-09.05.03", "Suministro e instalación de puerta contraplacada 2 hojas 1.60×2.10 m (0.80+0.80), e=35 mm, c/marco, pasadores y herrajes", "MAT-PUECP2H160", 2),
  pue("ARQ-09.05.04", "Suministro e instalación de puerta contraplacada 2 hojas 1.80×2.10 m (0.90+0.90), e=40 mm, c/marco, pasadores y herrajes", "MAT-PUECP2H180", 2),
  pue("ARQ-09.05.05", "Suministro e instalación de puerta contraplacada 2 hojas 2.00×2.10 m (1.00+1.00), e=40 mm, c/marco, pasadores y herrajes", "MAT-PUECP2H200", 2),

  pue("ARQ-09.06.01", "Suministro e instalación de puerta de madera tornillo 1 hoja 0.90×2.10 m, e=40 mm, c/marco y herrajes", "MAT-PUEMAD", 1),
  pue("ARQ-09.06.02", "Suministro e instalación de puerta de madera cedro 1 hoja 0.90×2.10 m, e=45 mm, c/marco y herrajes", "MAT-PUECED", 1),
  pue("ARQ-09.06.03", "Suministro e instalación de puerta de madera caoba 1 hoja 0.90×2.10 m, e=45 mm, c/marco y herrajes", "MAT-PUECAO90", 1),
  pue("ARQ-09.06.04", "Suministro e instalación de puerta de madera pino 1 hoja 0.90×2.10 m, e=40 mm, c/marco y herrajes", "MAT-PUEPIN90", 1),
  pue("ARQ-09.06.05", "Suministro e instalación de puerta entablerada de madera 1 hoja 0.90×2.10 m, e=40 mm, c/marco y herrajes", "MAT-PUEENT90", 1),
  pue("ARQ-09.06.06", "Suministro e instalación de puerta de madera tornillo 2 hojas 1.60×2.10 m, e=45 mm, c/marco, pasadores y herrajes", "MAT-PUETOR2H", 2),
  pue("ARQ-09.06.07", "Suministro e instalación de puerta de madera cedro 2 hojas 1.80×2.10 m, e=45 mm, c/marco, pasadores y herrajes", "MAT-PUECED2H", 2),

  pue("ARQ-09.07.01", "Suministro e instalación de puerta de tablero MDF e=18 mm 1 hoja 0.90×2.10 m, c/marco de pino y herrajes", "MAT-PUEMDF90", 1),
  pue("ARQ-09.07.02", "Suministro e instalación de puerta de tablero HDF e=5.5 mm 1 hoja 0.90×2.10 m, c/marco y herrajes", "MAT-PUEHDF90", 1),
  pue("ARQ-09.07.03", "Suministro e instalación de puerta de melamina e=18 mm canto ABS 1 hoja 0.90×2.10 m, c/marco y herrajes", "MAT-PUEMEL90", 1),

  pue("ARQ-09.08.01", "Suministro e instalación de puerta corrediza de madera 1 hoja 0.90×2.10 m, riel superior y herrajes", "MAT-PUECOR", 1, [], 0),
  pue("ARQ-09.08.02", "Suministro e instalación de puerta plegable de madera / MDF 0.90×2.10 m, 4 tablillas, riel superior", "MAT-PUEPLEG90", 1, [], 0),
  pue("ARQ-09.08.03", "Suministro e instalación de puerta pivotante de madera 1.00×2.40 m, pivote de piso y herrajes", "MAT-PUEPIV", 1, [], 0),
  pue("ARQ-09.08.04", "Suministro e instalación de puerta vaivén tipo sándwich 0.90×2.10 m, doble acción, c/marco", "MAT-PUEVAH", 1),

  pue("ARQ-09.09.01", "Suministro e instalación de puerta de PVC 1 hoja 0.90×2.10 m, panel sándwich, c/marco y herrajes", "MAT-PUEPVC90", 1),
  pue("ARQ-09.09.02", "Suministro e instalación de puerta de PVC 2 hojas 1.60×2.10 m, panel sándwich, c/marco, pasadores y herrajes", "MAT-PUEPVC2H", 2),

  pue("ARQ-09.10.01", "Suministro e instalación de puerta de madera 1 hoja 0.90×2.10 m con luna (vidrio recocido float 4 mm 0.40×1.00 m), c/junquillo y herrajes", "MAT-PUEVID90", 1, [["MAT-JUNQMAD", 3], ["MAT-SILN", 0.2]]),
  pue("ARQ-09.10.02", "Suministro e instalación de puerta de madera 2 hojas 1.60×2.10 m con luna (vidrio recocido float 4 mm), c/junquillo, pasadores y herrajes", "MAT-PUEVID2H", 2, [["MAT-JUNQMAD", 6], ["MAT-SILN", 0.35]]),

  pue("ARQ-09.03.02", "Suministro e instalación de puerta cortafuego 60 min 0.90×2.10 m, c/marco, cierrapuertas y herrajes certificados", "MAT-PUECI60", 1, [["MAT-CIERRP", 1], ["MO-HERR", 1.5]]),
  pue("ARQ-09.03.03", "Suministro e instalación de puerta cortafuego 120 min 0.90×2.10 m, c/marco, cierrapuertas y herrajes certificados", "MAT-PUECI120", 1, [["MAT-CIERRP", 1], ["MO-HERR", 1.8]]),

  pueMet("ARQ-10.02.02", "Suministro e instalación de puerta metálica 1 hoja 0.90×2.10 m, chapa GI e=0.80 mm, alma de poliuretano, c/marco", "MAT-PUEMET90", 1),
  pueMet("ARQ-10.02.03", "Suministro e instalación de puerta metálica 2 hojas 1.60×2.10 m, chapa GI e=0.80 mm, c/marco", "MAT-PUEMET2H", 2),
  p(
    "arquitectura",
    "10 Carpintería metálica y cerrajería",
    "ARQ-10.02.04",
    "Suministro e instalación de puerta de aluminio serie 42 1 hoja 0.90×2.10 m + vidrio recocido float 6 mm, c/herrajes",
    "und",
    r(["MO-OPE", 3.2], ["MO-VID", 1.2], ["MO-AYU", 2], ["MAT-PUEALU1H", 1], ["MAT-SILN", 0.6], ["MAT-ACCALU", 1], ["MAT-ANCLAALU", 10], ["EQ-HIN", 4]),
  ),
  p(
    "arquitectura",
    "10 Carpintería metálica y cerrajería",
    "ARQ-10.02.05",
    "Suministro e instalación de puerta de aluminio serie 42 2 hojas 1.60×2.10 m + vidrio recocido float 6 mm, c/herrajes",
    "und",
    r(["MO-OPE", 5.2], ["MO-VID", 2], ["MO-AYU", 3.2], ["MAT-PUEALU2H", 1], ["MAT-SILN", 1], ["MAT-ACCALU", 2], ["MAT-ANCLAALU", 16], ["EQ-HIN", 4]),
  ),
  p(
    "arquitectura",
    "10 Carpintería metálica y cerrajería",
    "ARQ-10.02.06",
    "Suministro e instalación de puerta de aluminio serie 50 1 hoja 0.90×2.10 m + vidrio templado 8 mm, c/herrajes",
    "und",
    r(["MO-OPE", 3.6], ["MO-VID", 1.5], ["MO-AYU", 2.2], ["MAT-PUEALUT1H", 1], ["MAT-SILN", 0.7], ["MAT-ACCALU", 1], ["MAT-ANCLAALU", 10], ["EQ-HIN", 4]),
  ),
  p(
    "arquitectura",
    "11 Vidrios y mamparas",
    "ARQ-11.02.02",
    "Suministro e instalación de puerta de vidrio templado 10 mm 1 hoja 0.90×2.10 m, herrajes pivot / patch fitting inox, sin marco",
    "und",
    r(["MO-VID", 4.2], ["MO-AYU", 2.8], ["MAT-PUETEM10", 1], ["MAT-SILN", 0.4], ["EQ-HIN", 4]),
  ),
  p(
    "arquitectura",
    "11 Vidrios y mamparas",
    "ARQ-11.02.03",
    "Suministro e instalación de puerta de vidrio templado 10 mm 2 hojas 1.60×2.10 m, herrajes pivot / patch fitting inox",
    "und",
    r(["MO-VID", 7], ["MO-AYU", 4.5], ["MAT-PUETEM2H", 1], ["MAT-SILN", 0.7], ["EQ-HIN", 4]),
  ),
  p(
    "arquitectura",
    "11 Vidrios y mamparas",
    "ARQ-11.02.04",
    "Suministro e instalación de mampara de ducha de vidrio templado 10 mm, herrajes inox",
    "und",
    r(["MO-VID", 3.4], ["MO-AYU", 2.2], ["MAT-MAM10", 1], ["MAT-SILN", 1], ["EQ-HIN", 4]),
  ),
  p(
    "arquitectura",
    "11 Vidrios y mamparas",
    "ARQ-11.06.01",
    "Suministro e instalación de baranda de vidrio templado 10 mm + pasamano de aluminio",
    "m",
    r(["MO-VID", 1.4], ["MO-AYU", 1.1], ["MAT-BARVID", 1], ["MAT-SILN", 0.25], ["EQ-HIN", 4]),
  ),
  p(
    "arquitectura",
    "10 Carpintería metálica y cerrajería",
    "ARQ-10.09.01",
    "Suministro e instalación de muro cortina / fachada de aluminio serie 80 + vidrio recocido float 6 mm",
    "m²",
    r(["MO-OPE", 1.85], ["MO-VID", 0.55], ["MO-AYU", 1.4], ["MAT-FACHVID", 1], ["MAT-SILE", 0.6], ["MAT-ANCLAALU", 8], ["EQ-AND", 0.08], ["EQ-HIN", 4]),
  ),

  ven("ARQ-10.07.01", "Suministro e instalación de ventana corrediza de aluminio serie 25 + vidrio recocido float 4 mm (luna cruda)", "MAT-VENALU25C", 1.05),
  ven("ARQ-10.07.02", "Suministro e instalación de ventana corrediza de aluminio serie 32 + vidrio recocido float 6 mm (luna cruda)", "MAT-VENALU32C", 1.12),
  ven("ARQ-10.07.03", "Suministro e instalación de ventana corrediza de aluminio serie 42 + vidrio recocido float 6 mm (luna cruda)", "MAT-VENALU42C", 1.18),
  ven("ARQ-10.07.04", "Suministro e instalación de ventana corrediza de aluminio serie 50 + vidrio recocido float 6 mm (luna cruda)", "MAT-VENALU50C", 1.25),
  ven("ARQ-10.07.05", "Suministro e instalación de ventana batiente 1 hoja de aluminio serie 32 + vidrio recocido float 6 mm", "MAT-VENALU32B1", 1.22),
  ven("ARQ-10.07.06", "Suministro e instalación de ventana batiente 2 hojas de aluminio serie 32 + vidrio recocido float 6 mm", "MAT-VENALU32B2", 1.32),
  ven("ARQ-10.07.07", "Suministro e instalación de ventana proyectante de aluminio serie 42 + vidrio recocido float 6 mm", "MAT-VENALU42P", 1.28),
  ven("ARQ-10.07.08", "Suministro e instalación de ventana oscilobatiente de aluminio serie 42 + vidrio recocido float 6 mm", "MAT-VENALU42O", 1.38),
  ven("ARQ-10.07.09", "Suministro e instalación de paño fijo de aluminio serie 50 + vidrio recocido float 6 mm", "MAT-VENALU50F", 0.95),
  ven("ARQ-10.07.10", "Suministro e instalación de ventana corrediza de aluminio serie 50 + DVH 6/12/6 mm (unidad de vidrio aislante)", "MAT-VENALU50DVH", 1.42),
  ven("ARQ-10.07.11", "Suministro e instalación de ventana corrediza de aluminio serie 50 + vidrio templado 8 mm", "MAT-VENALU50TEM", 1.35),
  ven("ARQ-10.07.12", "Suministro e instalación de ventana de aluminio serie 32 + vidrio opaco / acidado 6 mm", "MAT-VENOSCU6", 1.2),
  ven("ARQ-10.07.13", "Suministro e instalación de ventana de aluminio serie 32 + espejo plateado 4 mm (luna espejo)", "MAT-VENESP4", 1.22),
  ven("ARQ-10.07.14", "Suministro e instalación de ventana guillotina de aluminio serie 32 + vidrio recocido float 6 mm", "MAT-VENGIL6", 1.3),
  ven("ARQ-10.07.15", "Suministro e instalación de ventana basculante de aluminio serie 32 + vidrio recocido float 6 mm", "MAT-VENBAS6", 1.26),
  ven("ARQ-10.07.16", "Suministro e instalación de ventana corrediza 3 hojas de aluminio serie 32 + vidrio recocido float 6 mm", "MAT-VENALU32C3", 1.28),
  ven("ARQ-10.07.17", "Suministro e instalación de ventana batiente 1 hoja de aluminio serie 42 + vidrio recocido float 6 mm", "MAT-VENALU42B1", 1.28),
  ven("ARQ-10.07.18", "Suministro e instalación de ventana batiente 2 hojas de aluminio serie 42 + vidrio recocido float 6 mm", "MAT-VENALU42B2", 1.38),
  ven("ARQ-10.07.19", "Suministro e instalación de ventana corrediza de aluminio serie 50 + DVH templado 6/12/6 mm", "MAT-VENALU50DVHT", 1.48),

  ven("ARQ-10.08.01", "Suministro e instalación de ventana corrediza de PVC + vidrio recocido float 4 mm", "MAT-VENPVC4", 1.1),
  ven("ARQ-10.08.02", "Suministro e instalación de ventana corrediza de PVC + vidrio recocido float 6 mm", "MAT-VENPVC6", 1.18),
  ven("ARQ-10.08.03", "Suministro e instalación de ventana de PVC + DVH 6/12/6 mm", "MAT-VENPVCDVH", 1.35),
  ven("ARQ-10.08.04", "Suministro e instalación de ventana de fierro / acero 1 hoja + vidrio recocido float 4 mm", "MAT-VENFIE4", 1.25),
  ven("ARQ-10.08.05", "Suministro e instalación de ventana de fierro / acero 2 hojas + vidrio recocido float 6 mm", "MAT-VENFIE6", 1.38),
  ven("ARQ-10.08.06", "Suministro e instalación de ventana de celosía / persiana de aluminio (sin vidrio)", "MAT-VENCEL", 0.95),
  p(
    "arquitectura",
    "09 Carpintería de madera",
    "ARQ-09.11.01",
    "Suministro e instalación de ventana de madera 1 hoja + vidrio recocido float 4 mm, c/junquillo",
    "m²",
    r(["MO-CAR", 1.4], ["MO-VID", 0.4], ["MO-PEO", 0.7], ["MAT-VENMAD4", 1], ["MAT-JUNQMAD", 2.4], ["MAT-SILN", 0.4], ["EQ-HIN", 5]),
  ),
  p(
    "arquitectura",
    "09 Carpintería de madera",
    "ARQ-09.11.02",
    "Suministro e instalación de ventana de madera 2 hojas + vidrio recocido float 6 mm, c/junquillo",
    "m²",
    r(["MO-CAR", 1.7], ["MO-VID", 0.5], ["MO-PEO", 0.85], ["MAT-VENMAD6", 1], ["MAT-JUNQMAD", 3.2], ["MAT-SILN", 0.5], ["EQ-HIN", 5]),
  ),
  p(
    "arquitectura",
    "09 Carpintería de madera",
    "ARQ-09.11.03",
    "Suministro e instalación de ventana batiente 1 hoja de madera + vidrio recocido float 4 mm, c/junquillo",
    "m²",
    r(["MO-CAR", 1.5], ["MO-VID", 0.42], ["MO-PEO", 0.75], ["MAT-VENMADB1", 1], ["MAT-JUNQMAD", 2.6], ["MAT-SILN", 0.42], ["EQ-HIN", 5]),
  ),
  p(
    "arquitectura",
    "09 Carpintería de madera",
    "ARQ-09.11.04",
    "Suministro e instalación de ventana batiente 2 hojas de madera + vidrio recocido float 6 mm, c/junquillo",
    "m²",
    r(["MO-CAR", 1.85], ["MO-VID", 0.55], ["MO-PEO", 0.9], ["MAT-VENMADB2", 1], ["MAT-JUNQMAD", 3.4], ["MAT-SILN", 0.55], ["EQ-HIN", 5]),
  ),

  vid("ARQ-11.03.01", "Suministro y colocación de vidrio recocido float 3 mm (luna cruda)", "MAT-VID3", 0.4),
  vid("ARQ-11.03.02", "Suministro y colocación de vidrio recocido float 4 mm (luna cruda)", "MAT-VID4", 0.42),
  vid("ARQ-11.03.03", "Suministro y colocación de vidrio recocido float 5 mm (luna cruda)", "MAT-VID5", 0.44),
  vid("ARQ-11.03.04", "Suministro y colocación de vidrio recocido float 6 mm (luna cruda)", "MAT-VID", 0.45),
  vid("ARQ-11.03.05", "Suministro y colocación de vidrio recocido float 8 mm (luna cruda)", "MAT-FLOAT8", 0.52),
  vid("ARQ-11.03.06", "Suministro y colocación de vidrio recocido float 10 mm (luna cruda)", "MAT-VID10", 0.58),
  vid("ARQ-11.03.07", "Suministro y colocación de vidrio recocido float 12 mm (luna cruda)", "MAT-VID12", 0.65),
  vid("ARQ-11.03.08", "Suministro y colocación de vidrio recocido float bronce 4 mm", "MAT-VIDBR4", 0.45),
  vid("ARQ-11.03.09", "Suministro y colocación de vidrio recocido float bronce 6 mm", "MAT-VIDBR6", 0.48),
  vid("ARQ-11.03.10", "Suministro y colocación de vidrio recocido float gris 4 mm", "MAT-VIDGR4", 0.45),
  vid("ARQ-11.03.11", "Suministro y colocación de vidrio recocido float gris 6 mm", "MAT-VIDGR6", 0.48),
  vid("ARQ-11.03.12", "Suministro y colocación de vidrio reflectivo / control solar 6 mm", "MAT-VIDREF6", 0.5),
  vid("ARQ-11.03.13", "Suministro y colocación de vidrio opaco / acidado 6 mm", "MAT-VIDOP6", 0.5),
  vid("ARQ-11.03.14", "Suministro y colocación de vidrio catedral / ornamentado 6 mm", "MAT-VIDCATH6", 0.48),
  vid("ARQ-11.03.15", "Suministro y colocación de vidrio polarizado 6 mm", "MAT-VIDPOL6", 0.5),
  vid("ARQ-11.03.16", "Suministro y colocación de vidrio serigrafiado 6 mm", "MAT-VIDSER6", 0.55),

  vid("ARQ-11.04.01", "Suministro y colocación de vidrio de seguridad templado 6 mm (NTP 333.001)", "MAT-VIDT6", 0.62),
  vid("ARQ-11.04.02", "Suministro y colocación de vidrio de seguridad templado 8 mm (NTP 333.001)", "MAT-TEMP8", 0.68),
  vid("ARQ-11.04.03", "Suministro y colocación de vidrio de seguridad templado 10 mm (NTP 333.001)", "MAT-VIDT10", 0.75),
  vid("ARQ-11.04.04", "Suministro y colocación de vidrio de seguridad templado 12 mm (NTP 333.001)", "MAT-VIDT12", 0.82),
  vid("ARQ-11.04.05", "Suministro y colocación de vidrio laminado de seguridad 3+3 mm (PVB 0.38 mm)", "MAT-LAM33", 0.7),
  vid("ARQ-11.04.06", "Suministro y colocación de vidrio laminado de seguridad 4+4 mm (PVB 0.38 mm)", "MAT-VIDL44", 0.72),
  vid("ARQ-11.04.07", "Suministro y colocación de vidrio laminado de seguridad 5+5 mm (PVB 0.38 mm)", "MAT-VIDL55", 0.78),
  vid("ARQ-11.04.08", "Suministro y colocación de vidrio laminado de seguridad 6+6 mm (PVB 0.38 mm)", "MAT-LAM66", 0.85),
  vid("ARQ-11.04.09", "Suministro y colocación de unidad de vidrio aislante DVH 6/12/6 mm", "MAT-VIDDVH", 0.9),
  vid("ARQ-11.04.10", "Suministro y colocación de unidad de vidrio aislante DVH 8/12/8 mm", "MAT-DVH8128", 0.98),
  vid("ARQ-11.04.11", "Suministro y colocación de vidrio laminado de seguridad 8+8 mm (PVB 0.38 mm)", "MAT-VIDL88", 0.92),
  vid("ARQ-11.04.12", "Suministro y colocación de unidad de vidrio aislante DVH templado 6/12/6 mm", "MAT-VIDDVHT", 0.95),

  vid("ARQ-11.05.01", "Suministro y colocación de espejo plateado 3 mm (luna espejo, canto pulido)", "MAT-ESP3", 0.55),
  vid("ARQ-11.05.02", "Suministro y colocación de espejo plateado 4 mm (luna espejo, canto pulido)", "MAT-ESPLUNA4", 0.58),
  vid("ARQ-11.05.03", "Suministro y colocación de espejo plateado 5 mm (luna espejo, canto pulido)", "MAT-ESP5", 0.62),
  vid("ARQ-11.05.04", "Suministro y colocación de espejo plateado 6 mm (luna espejo, canto pulido)", "MAT-ESP6", 0.68),
];
